package interceptors

import (
	gumav1 "github.com/kia280/guma/gen/proto/guma/v1"
	"github.com/kia280/guma/internal/authz"
)

var MethodPermissions = map[string]authz.Permission{
	gumav1.AnnouncementService_CreateAnnouncementDraft_FullMethodName: authz.ManageAnnouncements,
	gumav1.AnnouncementService_DeleteAnnouncementDraft_FullMethodName: authz.ManageAnnouncements,
	gumav1.AnnouncementService_GetAnnouncement_FullMethodName:         authz.View,
	gumav1.AnnouncementService_ListAnnouncements_FullMethodName:       authz.View,
	gumav1.AnnouncementService_PublishAnnouncement_FullMethodName:     authz.ManageAnnouncements,
	gumav1.AnnouncementService_UnpublishAnnouncement_FullMethodName:   authz.ManageAnnouncements,
	gumav1.AnnouncementService_UpdateAnnouncement_FullMethodName:      authz.ManageAnnouncements,

	gumav1.AuctionService_CancelAuction_FullMethodName: authz.View,
	gumav1.AuctionService_CreateAuction_FullMethodName: authz.View,
	gumav1.AuctionService_DeleteAuction_FullMethodName: authz.View,
	gumav1.AuctionService_GetAuction_FullMethodName:    authz.View,
	gumav1.AuctionService_GetBidHistory_FullMethodName: authz.View,
	gumav1.AuctionService_ListAuctions_FullMethodName:  authz.View,
	gumav1.AuctionService_PlaceBid_FullMethodName:      authz.View,
	gumav1.AuctionService_UpdateAuction_FullMethodName: authz.View,

	gumav1.BankService_ContributeFunds_FullMethodName:   authz.View,
	gumav1.BankService_DeleteBankItem_FullMethodName:    authz.DeleteBankItems,
	gumav1.BankService_DonateItem_FullMethodName:        authz.View,
	gumav1.BankService_GetBank_FullMethodName:           authz.View,
	gumav1.BankService_GetItemHistory_FullMethodName:    authz.View,
	gumav1.BankService_ListBankItems_FullMethodName:     authz.View,
	gumav1.BankService_ListContributions_FullMethodName: authz.View,
	gumav1.BankService_ListFundRequests_FullMethodName:  authz.View,
	gumav1.BankService_ListItemRequests_FullMethodName:  authz.View,
	gumav1.BankService_RequestFunds_FullMethodName:      authz.View,
	gumav1.BankService_RequestItem_FullMethodName:       authz.View,
	gumav1.BankService_ReviewFundRequest_FullMethodName: authz.ReviewBankRequests,
	gumav1.BankService_ReviewItemRequest_FullMethodName: authz.ReviewBankRequests,

	gumav1.EventService_CreateEvent_FullMethodName:        authz.View,
	gumav1.EventService_DeleteEvent_FullMethodName:        authz.View,
	gumav1.EventService_GetEvent_FullMethodName:           authz.View,
	gumav1.EventService_ListEvents_FullMethodName:         authz.View,
	gumav1.EventService_ListEventsByRange_FullMethodName:  authz.View,
	gumav1.EventService_ListUpcomingEvents_FullMethodName: authz.View,
	gumav1.EventService_UpdateEvent_FullMethodName:        authz.View,

	gumav1.GuildService_DeleteGuild_FullMethodName:         authz.DeleteGuild,
	gumav1.GuildService_DeleteGuildLogo_FullMethodName:     authz.ManageGuild,
	gumav1.GuildService_GetGuildSettings_FullMethodName:    authz.View,
	gumav1.GuildService_GetGuildStats_FullMethodName:       authz.ViewStats,
	gumav1.GuildService_LeaveGuild_FullMethodName:          authz.View,
	gumav1.GuildService_UpdateGuild_FullMethodName:         authz.ManageGuild,
	gumav1.GuildService_UpdateGuildSettings_FullMethodName: authz.ManageGuild,
	gumav1.GuildService_UploadGuildLogo_FullMethodName:     authz.ManageGuild,

	gumav1.GumaService_GetDashboardData_FullMethodName: authz.View,
	gumav1.GumaService_GetNavigation_FullMethodName:    authz.View,
	gumav1.GumaService_SearchGlobal_FullMethodName:     authz.View,

	gumav1.ItemTemplateService_CreateItemTemplate_FullMethodName: authz.ManageRollCallTemplates,
	gumav1.ItemTemplateService_DeleteItemTemplate_FullMethodName: authz.ManageRollCallTemplates,
	gumav1.ItemTemplateService_ListItemTemplates_FullMethodName:  authz.ManageRollCallTemplates,
	gumav1.ItemTemplateService_UpdateItemTemplate_FullMethodName: authz.ManageRollCallTemplates,

	gumav1.MemberService_GenerateInviteCode_FullMethodName: authz.View,
	gumav1.MemberService_GetMember_FullMethodName:          authz.View,
	gumav1.MemberService_InviteMember_FullMethodName:       authz.View,
	gumav1.MemberService_ListInvites_FullMethodName:        authz.View,
	gumav1.MemberService_ListMembers_FullMethodName:        authz.View,
	gumav1.MemberService_RemoveMember_FullMethodName:       authz.View,
	gumav1.MemberService_RevokeInvite_FullMethodName:       authz.View,
	gumav1.MemberService_UpdateMember_FullMethodName:       authz.View,
	gumav1.MemberService_UpdateMemberRole_FullMethodName:   authz.ManageRoles,

	gumav1.RaffleService_CancelRaffle_FullMethodName:     authz.ManageRaffles,
	gumav1.RaffleService_CreateRaffle_FullMethodName:     authz.ManageRaffles,
	gumav1.RaffleService_DeleteRaffle_FullMethodName:     authz.ManageRaffles,
	gumav1.RaffleService_DrawRaffle_FullMethodName:       authz.ManageRaffles,
	gumav1.RaffleService_GetRaffle_FullMethodName:        authz.View,
	gumav1.RaffleService_GetRaffleWinners_FullMethodName: authz.View,
	gumav1.RaffleService_ListMyTickets_FullMethodName:    authz.View,
	gumav1.RaffleService_ListRaffles_FullMethodName:      authz.View,
	gumav1.RaffleService_PurchaseTickets_FullMethodName:  authz.View,
	gumav1.RaffleService_UpdateRaffle_FullMethodName:     authz.ManageRaffles,

	gumav1.RollCallService_AssignLoot_FullMethodName:             authz.ManageRollCalls,
	gumav1.RollCallService_CancelRollCall_FullMethodName:         authz.DeleteRollCalls,
	gumav1.RollCallService_CheckIn_FullMethodName:                authz.View,
	gumav1.RollCallService_CompleteRollCall_FullMethodName:       authz.ManageRollCalls,
	gumav1.RollCallService_CreateRollCall_FullMethodName:         authz.ManageRollCalls,
	gumav1.RollCallService_DeleteRollCall_FullMethodName:         authz.DeleteRollCalls,
	gumav1.RollCallService_DistributeRollCallGold_FullMethodName: authz.ManageRollCalls,
	gumav1.RollCallService_GetRollCall_FullMethodName:            authz.View,
	gumav1.RollCallService_GetRollCallGold_FullMethodName:        authz.View,
	gumav1.RollCallService_ListAttendees_FullMethodName:          authz.View,
	gumav1.RollCallService_ListRollCalls_FullMethodName:          authz.View,
	gumav1.RollCallService_UpdateRollCall_FullMethodName:         authz.ManageRollCalls,
	gumav1.RollCallService_UpdateRollCallLoot_FullMethodName:     authz.ManageRollCalls,

	gumav1.RollCallTemplateService_CreateRollCallTemplate_FullMethodName: authz.ManageRollCallTemplates,
	gumav1.RollCallTemplateService_DeleteRollCallTemplate_FullMethodName: authz.ManageRollCallTemplates,
	gumav1.RollCallTemplateService_ListRollCallTemplates_FullMethodName:  authz.ManageRollCallTemplates,
	gumav1.RollCallTemplateService_UpdateRollCallTemplate_FullMethodName: authz.ManageRollCallTemplates,

	gumav1.WalletService_AdminTransferBackpackItems_FullMethodName: authz.ManageMemberAssets,
	gumav1.WalletService_AdminTransferFunds_FullMethodName:         authz.ManageMemberAssets,
	gumav1.WalletService_CancelBackpackWithdrawal_FullMethodName:   authz.View,
	gumav1.WalletService_CancelWithdrawalRequest_FullMethodName:    authz.View,
	gumav1.WalletService_ConfirmBackpackDelivery_FullMethodName:    authz.DeliverItems,
	gumav1.WalletService_DepositFunds_FullMethodName:               authz.View,
	gumav1.WalletService_GetBalanceTrend_FullMethodName:            authz.View,
	gumav1.WalletService_GetMemberAssets_FullMethodName:            authz.ManageMemberAssets,
	gumav1.WalletService_GetWallet_FullMethodName:                  authz.View,
	gumav1.WalletService_ListBackpackItems_FullMethodName:          authz.View,
	gumav1.WalletService_ListMemberAssets_FullMethodName:           authz.ManageMemberAssets,
	gumav1.WalletService_ListMyWithdrawalRequests_FullMethodName:   authz.View,
	gumav1.WalletService_ListPendingDeliveries_FullMethodName:      authz.DeliverItems,
	gumav1.WalletService_ListTransactions_FullMethodName:           authz.View,
	gumav1.WalletService_ListWithdrawalRequests_FullMethodName:     authz.ReviewWithdrawals,
	gumav1.WalletService_ReviewWithdrawalRequest_FullMethodName:    authz.ReviewWithdrawals,
	gumav1.WalletService_TransferBackpackItem_FullMethodName:       authz.View,
	gumav1.WalletService_TransferFunds_FullMethodName:              authz.View,
	gumav1.WalletService_WithdrawBackpackItem_FullMethodName:       authz.View,
	gumav1.WalletService_WithdrawFunds_FullMethodName:              authz.View,
}
