// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcement.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnouncementDraft = `-- name: CreateAnnouncementDraft :one
INSERT INTO announcements (guild_id, author_id)
VALUES ($1, $2)
RETURNING id
`

type CreateAnnouncementDraftParams struct {
	GuildID  uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) CreateAnnouncementDraft(ctx context.Context, arg CreateAnnouncementDraftParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAnnouncementDraft, arg.GuildID, arg.AuthorID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAnnouncementDraft = `-- name: DeleteAnnouncementDraft :execrows
DELETE FROM announcements
WHERE id = $1 AND guild_id = $2 AND status = 'draft'
`

type DeleteAnnouncementDraftParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteAnnouncementDraft(ctx context.Context, arg DeleteAnnouncementDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncementDraft, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnnouncement = `-- name: GetAnnouncement :one
SELECT a.id, a.guild_id, a.author_id,
       COALESCE(member_display_name(a.guild_id, a.author_id), '')::text AS author_name,
       a.title, a.content, a.pinned, a.status, a.published_at, a.created_at, a.updated_at
FROM announcements a
JOIN users u ON u.id = a.author_id
WHERE a.id = $1 AND a.guild_id = $2
`

type GetAnnouncementParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetAnnouncementRow struct {
	ID          uuid.UUID
	GuildID     uuid.UUID
	AuthorID    uuid.UUID
	AuthorName  string
	Title       string
	Content     string
	Pinned      bool
	Status      string
	PublishedAt pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetAnnouncement(ctx context.Context, arg GetAnnouncementParams) (GetAnnouncementRow, error) {
	row := q.db.QueryRow(ctx, getAnnouncement, arg.ID, arg.GuildID)
	var i GetAnnouncementRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.AuthorID,
		&i.AuthorName,
		&i.Title,
		&i.Content,
		&i.Pinned,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuildAnnouncements = `-- name: ListGuildAnnouncements :many
SELECT a.id, a.guild_id, a.author_id,
       COALESCE(member_display_name(a.guild_id, a.author_id), '')::text AS author_name,
       a.title, a.content, a.pinned, a.status, a.published_at, a.created_at, a.updated_at
FROM announcements a
JOIN users u ON u.id = a.author_id
WHERE a.guild_id = $1
  AND ($2::bool OR a.status = 'published')
ORDER BY (a.status = 'draft') DESC,
         CASE WHEN a.status = 'published' THEN a.pinned ELSE FALSE END DESC,
         COALESCE(a.published_at, a.updated_at) DESC,
         a.id DESC
LIMIT $3::int
`

type ListGuildAnnouncementsParams struct {
	GuildID       uuid.UUID
	IncludeDrafts bool
	PageSize      int32
}

type ListGuildAnnouncementsRow struct {
	ID          uuid.UUID
	GuildID     uuid.UUID
	AuthorID    uuid.UUID
	AuthorName  string
	Title       string
	Content     string
	Pinned      bool
	Status      string
	PublishedAt pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListGuildAnnouncements(ctx context.Context, arg ListGuildAnnouncementsParams) ([]ListGuildAnnouncementsRow, error) {
	rows, err := q.db.Query(ctx, listGuildAnnouncements, arg.GuildID, arg.IncludeDrafts, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildAnnouncementsRow{}
	for rows.Next() {
		var i ListGuildAnnouncementsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Title,
			&i.Content,
			&i.Pinned,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishAnnouncement = `-- name: PublishAnnouncement :execrows
UPDATE announcements
SET status = 'published', published_at = NOW(), updated_at = NOW()
WHERE id = $1 AND guild_id = $2 AND status = 'draft'
  AND btrim(title) <> '' AND btrim(content) <> ''
`

type PublishAnnouncementParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) PublishAnnouncement(ctx context.Context, arg PublishAnnouncementParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishAnnouncement, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unpublishAnnouncement = `-- name: UnpublishAnnouncement :execrows
UPDATE announcements
SET status = 'draft', published_at = NULL, updated_at = NOW()
WHERE id = $1 AND guild_id = $2 AND status = 'published'
`

type UnpublishAnnouncementParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) UnpublishAnnouncement(ctx context.Context, arg UnpublishAnnouncementParams) (int64, error) {
	result, err := q.db.Exec(ctx, unpublishAnnouncement, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :execrows
UPDATE announcements
SET title = $3, content = $4, pinned = $5, updated_at = NOW()
WHERE id = $1 AND guild_id = $2
  AND (status = 'draft' OR (btrim($3) <> '' AND btrim($4) <> ''))
`

type UpdateAnnouncementParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
	Title   string
	Content string
	Pinned  bool
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAnnouncement,
		arg.ID,
		arg.GuildID,
		arg.Title,
		arg.Content,
		arg.Pinned,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
