// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auction.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateDueAuctions = `-- name: ActivateDueAuctions :execrows
UPDATE auctions SET status = 'ACTIVE', updated_at = NOW()
WHERE status = 'UPCOMING' AND start_time <= NOW()
`

func (q *Queries) ActivateDueAuctions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, activateDueAuctions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const auctionExists = `-- name: AuctionExists :one
SELECT EXISTS(SELECT 1 FROM auctions WHERE id = $1 AND guild_id = $2)
`

type AuctionExistsParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) AuctionExists(ctx context.Context, arg AuctionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, auctionExists, arg.ID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAuctions = `-- name: CountAuctions :one
SELECT COUNT(*) FROM auctions
WHERE guild_id = $1
  AND ($2::text   = '' OR status             = $2::text)
  AND ($3::text = '' OR item->>'category'  = $3::text)
  AND ($4::text   = '' OR item->>'rarity'    = $4::text)
  AND ($5::text          = '%%' OR item->>'name'   ILIKE $5::text)
`

type CountAuctionsParams struct {
	GuildID        uuid.UUID
	StatusFilter   string
	CategoryFilter string
	RarityFilter   string
	Search         string
}

func (q *Queries) CountAuctions(ctx context.Context, arg CountAuctionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuctions,
		arg.GuildID,
		arg.StatusFilter,
		arg.CategoryFilter,
		arg.RarityFilter,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBids = `-- name: CountBids :one
SELECT COUNT(*) FROM bids WHERE auction_id = $1
`

func (q *Queries) CountBids(ctx context.Context, auctionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBids, auctionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuction = `-- name: CreateAuction :one
INSERT INTO auctions (
    id, guild_id, seller_id, item, starting_bid, current_bid,
    min_bid_increment, start_time, end_time, status, is_blind,
    source_type, source_item_id
) VALUES ($8::uuid, $1, $2, $9::jsonb, $3, 0, $4, $5, $6, $10::text, $7,
          NULLIF($11::text, ''), $12::uuid)
RETURNING id, guild_id, seller_id, item, starting_bid, current_bid,
          current_bidder_id, min_bid_increment, start_time, end_time,
          status, is_blind, created_at, updated_at,
          source_type, settled_at, source_item_id
`

type CreateAuctionParams struct {
	GuildID         uuid.UUID
	SellerID        uuid.UUID
	StartingBid     int64
	MinBidIncrement int64
	StartTime       time.Time
	EndTime         time.Time
	IsBlind         bool
	ID              uuid.UUID
	Item            []byte
	Status          string
	SourceType      string
	SourceItemID    *uuid.UUID
}

func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, createAuction,
		arg.GuildID,
		arg.SellerID,
		arg.StartingBid,
		arg.MinBidIncrement,
		arg.StartTime,
		arg.EndTime,
		arg.IsBlind,
		arg.ID,
		arg.Item,
		arg.Status,
		arg.SourceType,
		arg.SourceItemID,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.SellerID,
		&i.Item,
		&i.StartingBid,
		&i.CurrentBid,
		&i.CurrentBidderID,
		&i.MinBidIncrement,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.IsBlind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.SettledAt,
		&i.SourceItemID,
	)
	return i, err
}

const getAuction = `-- name: GetAuction :one
SELECT auctions.id, auctions.guild_id, auctions.seller_id, auctions.item, auctions.starting_bid, auctions.current_bid, auctions.current_bidder_id, auctions.min_bid_increment, auctions.start_time, auctions.end_time, auctions.status, auctions.is_blind, auctions.created_at, auctions.updated_at, auctions.source_type, auctions.settled_at, auctions.source_item_id,
       COALESCE(notification_user_name(auctions.seller_id), '')::text          AS seller_name,
       COALESCE(seller.avatar_url, '')::text                                   AS seller_avatar_url,
       COALESCE(notification_user_name(auctions.current_bidder_id), '')::text AS current_bidder_name,
       COALESCE(bidder.avatar_url, '')::text                                   AS current_bidder_avatar_url
FROM auctions
LEFT JOIN users seller ON seller.id = auctions.seller_id
LEFT JOIN users bidder ON bidder.id = auctions.current_bidder_id
WHERE auctions.id = $1 AND auctions.guild_id = $2
`

type GetAuctionParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetAuctionRow struct {
	Auction                Auction
	SellerName             string
	SellerAvatarUrl        string
	CurrentBidderName      string
	CurrentBidderAvatarUrl string
}

func (q *Queries) GetAuction(ctx context.Context, arg GetAuctionParams) (GetAuctionRow, error) {
	row := q.db.QueryRow(ctx, getAuction, arg.ID, arg.GuildID)
	var i GetAuctionRow
	err := row.Scan(
		&i.Auction.ID,
		&i.Auction.GuildID,
		&i.Auction.SellerID,
		&i.Auction.Item,
		&i.Auction.StartingBid,
		&i.Auction.CurrentBid,
		&i.Auction.CurrentBidderID,
		&i.Auction.MinBidIncrement,
		&i.Auction.StartTime,
		&i.Auction.EndTime,
		&i.Auction.Status,
		&i.Auction.IsBlind,
		&i.Auction.CreatedAt,
		&i.Auction.UpdatedAt,
		&i.Auction.SourceType,
		&i.Auction.SettledAt,
		&i.Auction.SourceItemID,
		&i.SellerName,
		&i.SellerAvatarUrl,
		&i.CurrentBidderName,
		&i.CurrentBidderAvatarUrl,
	)
	return i, err
}

const getAuctionForUpdate = `-- name: GetAuctionForUpdate :one
SELECT current_bid, current_bidder_id, min_bid_increment, status, end_time
FROM auctions WHERE id = $1 AND guild_id = $2 FOR UPDATE
`

type GetAuctionForUpdateParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetAuctionForUpdateRow struct {
	CurrentBid      int64
	CurrentBidderID *uuid.UUID
	MinBidIncrement int64
	Status          string
	EndTime         time.Time
}

func (q *Queries) GetAuctionForUpdate(ctx context.Context, arg GetAuctionForUpdateParams) (GetAuctionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuctionForUpdate, arg.ID, arg.GuildID)
	var i GetAuctionForUpdateRow
	err := row.Scan(
		&i.CurrentBid,
		&i.CurrentBidderID,
		&i.MinBidIncrement,
		&i.Status,
		&i.EndTime,
	)
	return i, err
}

const insertBackpackItem = `-- name: InsertBackpackItem :one
INSERT INTO backpack_items (id, owner_id, guild_id, item, source, source_id, note)
VALUES (COALESCE($1::uuid, uuid_generate_v4()), $2, $3, $4::jsonb,
        $5::text, $6, NULLIF($7::text, ''))
RETURNING id
`

type InsertBackpackItemParams struct {
	ID       *uuid.UUID
	OwnerID  uuid.UUID
	GuildID  uuid.UUID
	Item     []byte
	Source   string
	SourceID *uuid.UUID
	Note     string
}

func (q *Queries) InsertBackpackItem(ctx context.Context, arg InsertBackpackItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertBackpackItem,
		arg.ID,
		arg.OwnerID,
		arg.GuildID,
		arg.Item,
		arg.Source,
		arg.SourceID,
		arg.Note,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertBankProceeds = `-- name: InsertBankProceeds :exec
INSERT INTO bank_contributions (guild_id, user_id, username, amount, note, kind, reference_type, reference_id)
VALUES ($1, $2, $4::text, $3, NULLIF($5::text, ''),
        $6::text, $7::text, $8::uuid)
`

type InsertBankProceedsParams struct {
	GuildID       uuid.UUID
	UserID        uuid.UUID
	Amount        int64
	Username      string
	Note          string
	Kind          string
	ReferenceType string
	ReferenceID   uuid.UUID
}

func (q *Queries) InsertBankProceeds(ctx context.Context, arg InsertBankProceedsParams) error {
	_, err := q.db.Exec(ctx, insertBankProceeds,
		arg.GuildID,
		arg.UserID,
		arg.Amount,
		arg.Username,
		arg.Note,
		arg.Kind,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	return err
}

const insertBid = `-- name: InsertBid :one
INSERT INTO bids (auction_id, bidder_id, amount, is_winning)
VALUES ($1, $2, $3, true)
RETURNING id, placed_at
`

type InsertBidParams struct {
	AuctionID uuid.UUID
	BidderID  uuid.UUID
	Amount    int64
}

type InsertBidRow struct {
	ID       uuid.UUID
	PlacedAt time.Time
}

func (q *Queries) InsertBid(ctx context.Context, arg InsertBidParams) (InsertBidRow, error) {
	row := q.db.QueryRow(ctx, insertBid, arg.AuctionID, arg.BidderID, arg.Amount)
	var i InsertBidRow
	err := row.Scan(&i.ID, &i.PlacedAt)
	return i, err
}

const listAuctions = `-- name: ListAuctions :many
SELECT auctions.id, auctions.guild_id, auctions.seller_id, auctions.item, auctions.starting_bid, auctions.current_bid, auctions.current_bidder_id, auctions.min_bid_increment, auctions.start_time, auctions.end_time, auctions.status, auctions.is_blind, auctions.created_at, auctions.updated_at, auctions.source_type, auctions.settled_at, auctions.source_item_id,
       COALESCE(notification_user_name(auctions.seller_id), '')::text          AS seller_name,
       COALESCE(seller.avatar_url, '')::text                                   AS seller_avatar_url,
       COALESCE(notification_user_name(auctions.current_bidder_id), '')::text AS current_bidder_name,
       COALESCE(bidder.avatar_url, '')::text                                   AS current_bidder_avatar_url
FROM auctions
LEFT JOIN users seller ON seller.id = auctions.seller_id
LEFT JOIN users bidder ON bidder.id = auctions.current_bidder_id
WHERE auctions.guild_id = $1
  AND ($2::text   = '' OR auctions.status            = $2::text)
  AND ($3::text = '' OR auctions.item->>'category' = $3::text)
  AND ($4::text   = '' OR auctions.item->>'rarity'   = $4::text)
  AND ($5::text          = '%%' OR auctions.item->>'name'  ILIKE $5::text)
ORDER BY auctions.created_at DESC
LIMIT $7::int OFFSET $6::int
`

type ListAuctionsParams struct {
	GuildID        uuid.UUID
	StatusFilter   string
	CategoryFilter string
	RarityFilter   string
	Search         string
	PageOffset     int32
	PageSize       int32
}

type ListAuctionsRow struct {
	Auction                Auction
	SellerName             string
	SellerAvatarUrl        string
	CurrentBidderName      string
	CurrentBidderAvatarUrl string
}

func (q *Queries) ListAuctions(ctx context.Context, arg ListAuctionsParams) ([]ListAuctionsRow, error) {
	rows, err := q.db.Query(ctx, listAuctions,
		arg.GuildID,
		arg.StatusFilter,
		arg.CategoryFilter,
		arg.RarityFilter,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuctionsRow{}
	for rows.Next() {
		var i ListAuctionsRow
		if err := rows.Scan(
			&i.Auction.ID,
			&i.Auction.GuildID,
			&i.Auction.SellerID,
			&i.Auction.Item,
			&i.Auction.StartingBid,
			&i.Auction.CurrentBid,
			&i.Auction.CurrentBidderID,
			&i.Auction.MinBidIncrement,
			&i.Auction.StartTime,
			&i.Auction.EndTime,
			&i.Auction.Status,
			&i.Auction.IsBlind,
			&i.Auction.CreatedAt,
			&i.Auction.UpdatedAt,
			&i.Auction.SourceType,
			&i.Auction.SettledAt,
			&i.Auction.SourceItemID,
			&i.SellerName,
			&i.SellerAvatarUrl,
			&i.CurrentBidderName,
			&i.CurrentBidderAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBids = `-- name: ListBids :many
SELECT b.id, b.auction_id, b.bidder_id, b.amount, b.is_winning, b.placed_at,
       COALESCE(notification_user_name(b.bidder_id), '')::text AS bidder_name,
       COALESCE(u.avatar_url, '')::text                       AS bidder_avatar_url
FROM bids b
LEFT JOIN users u ON u.id = b.bidder_id
WHERE b.auction_id = $1
ORDER BY b.placed_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListBidsParams struct {
	AuctionID  uuid.UUID
	PageOffset int32
	PageSize   int32
}

type ListBidsRow struct {
	ID              uuid.UUID
	AuctionID       uuid.UUID
	BidderID        uuid.UUID
	Amount          int64
	IsWinning       bool
	PlacedAt        time.Time
	BidderName      string
	BidderAvatarUrl string
}

func (q *Queries) ListBids(ctx context.Context, arg ListBidsParams) ([]ListBidsRow, error) {
	rows, err := q.db.Query(ctx, listBids, arg.AuctionID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBidsRow{}
	for rows.Next() {
		var i ListBidsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.BidderID,
			&i.Amount,
			&i.IsWinning,
			&i.PlacedAt,
			&i.BidderName,
			&i.BidderAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueAuctions = `-- name: ListDueAuctions :many
SELECT id FROM auctions
WHERE status = 'ACTIVE' AND end_time <= NOW()
ORDER BY end_time ASC
LIMIT $1::int
`

func (q *Queries) ListDueAuctions(ctx context.Context, maxRows int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueAuctions, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuctionForCancel = `-- name: LockAuctionForCancel :one
SELECT current_bid, current_bidder_id, status, source_type, source_item_id
FROM auctions WHERE id = $1 AND guild_id = $2
FOR UPDATE
`

type LockAuctionForCancelParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type LockAuctionForCancelRow struct {
	CurrentBid      int64
	CurrentBidderID *uuid.UUID
	Status          string
	SourceType      pgtype.Text
	SourceItemID    *uuid.UUID
}

func (q *Queries) LockAuctionForCancel(ctx context.Context, arg LockAuctionForCancelParams) (LockAuctionForCancelRow, error) {
	row := q.db.QueryRow(ctx, lockAuctionForCancel, arg.ID, arg.GuildID)
	var i LockAuctionForCancelRow
	err := row.Scan(
		&i.CurrentBid,
		&i.CurrentBidderID,
		&i.Status,
		&i.SourceType,
		&i.SourceItemID,
	)
	return i, err
}

const lockAuctionForSettlement = `-- name: LockAuctionForSettlement :one
SELECT id, guild_id, seller_id, item, current_bid, current_bidder_id,
       status, end_time, source_type, source_item_id
FROM auctions WHERE id = $1
FOR UPDATE
`

type LockAuctionForSettlementRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	SellerID        uuid.UUID
	Item            []byte
	CurrentBid      int64
	CurrentBidderID *uuid.UUID
	Status          string
	EndTime         time.Time
	SourceType      pgtype.Text
	SourceItemID    *uuid.UUID
}

func (q *Queries) LockAuctionForSettlement(ctx context.Context, id uuid.UUID) (LockAuctionForSettlementRow, error) {
	row := q.db.QueryRow(ctx, lockAuctionForSettlement, id)
	var i LockAuctionForSettlementRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.SellerID,
		&i.Item,
		&i.CurrentBid,
		&i.CurrentBidderID,
		&i.Status,
		&i.EndTime,
		&i.SourceType,
		&i.SourceItemID,
	)
	return i, err
}

const markAllBidsNotWinning = `-- name: MarkAllBidsNotWinning :exec
UPDATE bids SET is_winning = false WHERE auction_id = $1
`

func (q *Queries) MarkAllBidsNotWinning(ctx context.Context, auctionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllBidsNotWinning, auctionID)
	return err
}

const markAuctionEnded = `-- name: MarkAuctionEnded :exec
UPDATE auctions SET status = 'ENDED', settled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkAuctionEnded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAuctionEnded, id)
	return err
}

const updateAuctionBid = `-- name: UpdateAuctionBid :exec
UPDATE auctions SET current_bid = $1, current_bidder_id = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateAuctionBidParams struct {
	CurrentBid      int64
	CurrentBidderID *uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateAuctionBid(ctx context.Context, arg UpdateAuctionBidParams) error {
	_, err := q.db.Exec(ctx, updateAuctionBid, arg.CurrentBid, arg.CurrentBidderID, arg.ID)
	return err
}

const updateAuctionStatus = `-- name: UpdateAuctionStatus :exec
UPDATE auctions SET status = $1::text, updated_at = NOW() WHERE id = $2
`

type UpdateAuctionStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateAuctionStatus(ctx context.Context, arg UpdateAuctionStatusParams) error {
	_, err := q.db.Exec(ctx, updateAuctionStatus, arg.Status, arg.ID)
	return err
}
