// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auction.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const auctionExists = `-- name: AuctionExists :one
SELECT EXISTS(SELECT 1 FROM auctions WHERE id = $1 AND guild_id = $2)
`

type AuctionExistsParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) AuctionExists(ctx context.Context, arg AuctionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, auctionExists, arg.ID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAuctions = `-- name: CountAuctions :one
SELECT COUNT(*) FROM auctions
WHERE guild_id = $1
  AND ($2::text   = '' OR status             = $2::text)
  AND ($3::text = '' OR item->>'category'  = $3::text)
  AND ($4::text   = '' OR item->>'rarity'    = $4::text)
  AND ($5::text          = '%%' OR item->>'name'   ILIKE $5::text)
`

type CountAuctionsParams struct {
	GuildID        uuid.UUID
	StatusFilter   string
	CategoryFilter string
	RarityFilter   string
	Search         string
}

func (q *Queries) CountAuctions(ctx context.Context, arg CountAuctionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuctions,
		arg.GuildID,
		arg.StatusFilter,
		arg.CategoryFilter,
		arg.RarityFilter,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBids = `-- name: CountBids :one
SELECT COUNT(*) FROM bids WHERE auction_id = $1
`

func (q *Queries) CountBids(ctx context.Context, auctionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBids, auctionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuction = `-- name: CreateAuction :one
INSERT INTO auctions (
    guild_id, seller_id, item, starting_bid, current_bid,
    min_bid_increment, start_time, end_time, status, is_blind
) VALUES ($1, $2, $8::jsonb, $3, 0, $4, $5, $6, $9::text, $7)
RETURNING id, guild_id, seller_id, item, starting_bid, current_bid,
          current_bidder_id, min_bid_increment, start_time, end_time,
          status, is_blind, created_at, updated_at
`

type CreateAuctionParams struct {
	GuildID         uuid.UUID
	SellerID        uuid.UUID
	StartingBid     int64
	MinBidIncrement int64
	StartTime       time.Time
	EndTime         time.Time
	IsBlind         bool
	Item            []byte
	Status          string
}

func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, createAuction,
		arg.GuildID,
		arg.SellerID,
		arg.StartingBid,
		arg.MinBidIncrement,
		arg.StartTime,
		arg.EndTime,
		arg.IsBlind,
		arg.Item,
		arg.Status,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.SellerID,
		&i.Item,
		&i.StartingBid,
		&i.CurrentBid,
		&i.CurrentBidderID,
		&i.MinBidIncrement,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.IsBlind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuction = `-- name: GetAuction :one
SELECT id, guild_id, seller_id, item, starting_bid, current_bid,
       current_bidder_id, min_bid_increment, start_time, end_time,
       status, is_blind, created_at, updated_at
FROM auctions WHERE id = $1 AND guild_id = $2
`

type GetAuctionParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) GetAuction(ctx context.Context, arg GetAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuction, arg.ID, arg.GuildID)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.SellerID,
		&i.Item,
		&i.StartingBid,
		&i.CurrentBid,
		&i.CurrentBidderID,
		&i.MinBidIncrement,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.IsBlind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuctionCancelInfo = `-- name: GetAuctionCancelInfo :one
SELECT current_bid, current_bidder_id, status FROM auctions WHERE id = $1 AND guild_id = $2
`

type GetAuctionCancelInfoParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetAuctionCancelInfoRow struct {
	CurrentBid      int64
	CurrentBidderID *uuid.UUID
	Status          string
}

func (q *Queries) GetAuctionCancelInfo(ctx context.Context, arg GetAuctionCancelInfoParams) (GetAuctionCancelInfoRow, error) {
	row := q.db.QueryRow(ctx, getAuctionCancelInfo, arg.ID, arg.GuildID)
	var i GetAuctionCancelInfoRow
	err := row.Scan(&i.CurrentBid, &i.CurrentBidderID, &i.Status)
	return i, err
}

const getAuctionForUpdate = `-- name: GetAuctionForUpdate :one
SELECT current_bid, current_bidder_id, min_bid_increment, status, end_time
FROM auctions WHERE id = $1 AND guild_id = $2 FOR UPDATE
`

type GetAuctionForUpdateParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetAuctionForUpdateRow struct {
	CurrentBid      int64
	CurrentBidderID *uuid.UUID
	MinBidIncrement int64
	Status          string
	EndTime         time.Time
}

func (q *Queries) GetAuctionForUpdate(ctx context.Context, arg GetAuctionForUpdateParams) (GetAuctionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuctionForUpdate, arg.ID, arg.GuildID)
	var i GetAuctionForUpdateRow
	err := row.Scan(
		&i.CurrentBid,
		&i.CurrentBidderID,
		&i.MinBidIncrement,
		&i.Status,
		&i.EndTime,
	)
	return i, err
}

const insertBid = `-- name: InsertBid :one
INSERT INTO bids (auction_id, bidder_id, amount, is_winning)
VALUES ($1, $2, $3, true)
RETURNING id, placed_at
`

type InsertBidParams struct {
	AuctionID uuid.UUID
	BidderID  uuid.UUID
	Amount    int64
}

type InsertBidRow struct {
	ID       uuid.UUID
	PlacedAt time.Time
}

func (q *Queries) InsertBid(ctx context.Context, arg InsertBidParams) (InsertBidRow, error) {
	row := q.db.QueryRow(ctx, insertBid, arg.AuctionID, arg.BidderID, arg.Amount)
	var i InsertBidRow
	err := row.Scan(&i.ID, &i.PlacedAt)
	return i, err
}

const listAuctions = `-- name: ListAuctions :many
SELECT id, guild_id, seller_id, item, starting_bid, current_bid,
       current_bidder_id, min_bid_increment, start_time, end_time,
       status, is_blind, created_at, updated_at
FROM auctions
WHERE guild_id = $1
  AND ($2::text   = '' OR status             = $2::text)
  AND ($3::text = '' OR item->>'category'  = $3::text)
  AND ($4::text   = '' OR item->>'rarity'    = $4::text)
  AND ($5::text          = '%%' OR item->>'name'   ILIKE $5::text)
ORDER BY created_at DESC
LIMIT $7::int OFFSET $6::int
`

type ListAuctionsParams struct {
	GuildID        uuid.UUID
	StatusFilter   string
	CategoryFilter string
	RarityFilter   string
	Search         string
	PageOffset     int32
	PageSize       int32
}

func (q *Queries) ListAuctions(ctx context.Context, arg ListAuctionsParams) ([]Auction, error) {
	rows, err := q.db.Query(ctx, listAuctions,
		arg.GuildID,
		arg.StatusFilter,
		arg.CategoryFilter,
		arg.RarityFilter,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Auction{}
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.SellerID,
			&i.Item,
			&i.StartingBid,
			&i.CurrentBid,
			&i.CurrentBidderID,
			&i.MinBidIncrement,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.IsBlind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBids = `-- name: ListBids :many
SELECT id, auction_id, bidder_id, amount, is_winning, placed_at
FROM bids WHERE auction_id = $1
ORDER BY placed_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListBidsParams struct {
	AuctionID  uuid.UUID
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ListBids(ctx context.Context, arg ListBidsParams) ([]Bid, error) {
	rows, err := q.db.Query(ctx, listBids, arg.AuctionID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bid{}
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.AuctionID,
			&i.BidderID,
			&i.Amount,
			&i.IsWinning,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllBidsNotWinning = `-- name: MarkAllBidsNotWinning :exec
UPDATE bids SET is_winning = false WHERE auction_id = $1
`

func (q *Queries) MarkAllBidsNotWinning(ctx context.Context, auctionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllBidsNotWinning, auctionID)
	return err
}

const updateAuctionBid = `-- name: UpdateAuctionBid :exec
UPDATE auctions SET current_bid = $1, current_bidder_id = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateAuctionBidParams struct {
	CurrentBid      int64
	CurrentBidderID *uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateAuctionBid(ctx context.Context, arg UpdateAuctionBidParams) error {
	_, err := q.db.Exec(ctx, updateAuctionBid, arg.CurrentBid, arg.CurrentBidderID, arg.ID)
	return err
}

const updateAuctionStatus = `-- name: UpdateAuctionStatus :exec
UPDATE auctions SET status = $1::text, updated_at = NOW() WHERE id = $2
`

type UpdateAuctionStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateAuctionStatus(ctx context.Context, arg UpdateAuctionStatusParams) error {
	_, err := q.db.Exec(ctx, updateAuctionStatus, arg.Status, arg.ID)
	return err
}
