// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authz.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const acquireAuthzMemberLock = `-- name: AcquireAuthzMemberLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::uuid::text || ':' || $2::uuid::text, 0))
`

type AcquireAuthzMemberLockParams struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) AcquireAuthzMemberLock(ctx context.Context, arg AcquireAuthzMemberLockParams) error {
	_, err := q.db.Exec(ctx, acquireAuthzMemberLock, arg.GuildID, arg.UserID)
	return err
}

const claimNextAuthzOutboxMember = `-- name: ClaimNextAuthzOutboxMember :one
SELECT guild_id, user_id FROM authz_member_outbox
WHERE available_at <= NOW()
ORDER BY id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type ClaimNextAuthzOutboxMemberRow struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) ClaimNextAuthzOutboxMember(ctx context.Context) (ClaimNextAuthzOutboxMemberRow, error) {
	row := q.db.QueryRow(ctx, claimNextAuthzOutboxMember)
	var i ClaimNextAuthzOutboxMemberRow
	err := row.Scan(&i.GuildID, &i.UserID)
	return i, err
}

const deferAuthzOutboxMember = `-- name: DeferAuthzOutboxMember :exec
UPDATE authz_member_outbox
SET attempts = attempts + 1,
    available_at = NOW() + make_interval(secs => power(2, LEAST(attempts, 8)))
WHERE guild_id = $1 AND user_id = $2
`

type DeferAuthzOutboxMemberParams struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeferAuthzOutboxMember(ctx context.Context, arg DeferAuthzOutboxMemberParams) error {
	_, err := q.db.Exec(ctx, deferAuthzOutboxMember, arg.GuildID, arg.UserID)
	return err
}

const deleteAuthzOutboxEntries = `-- name: DeleteAuthzOutboxEntries :exec
DELETE FROM authz_member_outbox WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteAuthzOutboxEntries(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, deleteAuthzOutboxEntries, ids)
	return err
}

const listMemberRolesAfter = `-- name: ListMemberRolesAfter :many
SELECT guild_id, user_id, role FROM members
WHERE (guild_id, user_id) > ($1::uuid, $2::uuid)
ORDER BY guild_id, user_id
LIMIT $3
`

type ListMemberRolesAfterParams struct {
	AfterGuildID uuid.UUID
	AfterUserID  uuid.UUID
	PageSize     int32
}

type ListMemberRolesAfterRow struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
	Role    string
}

func (q *Queries) ListMemberRolesAfter(ctx context.Context, arg ListMemberRolesAfterParams) ([]ListMemberRolesAfterRow, error) {
	rows, err := q.db.Query(ctx, listMemberRolesAfter, arg.AfterGuildID, arg.AfterUserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberRolesAfterRow{}
	for rows.Next() {
		var i ListMemberRolesAfterRow
		if err := rows.Scan(&i.GuildID, &i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuthzOutboxEntries = `-- name: LockAuthzOutboxEntries :many
SELECT id FROM authz_member_outbox
WHERE guild_id = $1 AND user_id = $2
FOR UPDATE SKIP LOCKED
`

type LockAuthzOutboxEntriesParams struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) LockAuthzOutboxEntries(ctx context.Context, arg LockAuthzOutboxEntriesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockAuthzOutboxEntries, arg.GuildID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
