// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBankContributions = `-- name: CountBankContributions :one
SELECT ((SELECT COUNT(*) FROM bank_contributions c WHERE c.guild_id = $1)
      + (SELECT COUNT(*) FROM roll_call_gold_pots p
         JOIN roll_calls rc ON rc.id = p.roll_call_id
         WHERE p.guild_id = $1 AND rc.completed_at IS NOT NULL AND p.total - p.distributed - p.retracted > 0))::bigint AS count
`

func (q *Queries) CountBankContributions(ctx context.Context, guildID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBankContributions, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBankItems = `-- name: CountBankItems :one
SELECT COUNT(*) FROM bank_items
WHERE guild_id = $1
  AND ($2::text = '' OR item->>'category' = $2::text)
  AND ($3::text   = '' OR item->>'rarity'   = $3::text)
  AND ($4::text  = '' OR roll_call_id::text  = $4::text)
`

type CountBankItemsParams struct {
	GuildID        uuid.UUID
	CategoryFilter string
	RarityFilter   string
	RollCallFilter string
}

func (q *Queries) CountBankItems(ctx context.Context, arg CountBankItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBankItems,
		arg.GuildID,
		arg.CategoryFilter,
		arg.RarityFilter,
		arg.RollCallFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFundRequests = `-- name: CountFundRequests :one
SELECT COUNT(*) FROM fund_requests WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
`

type CountFundRequestsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountFundRequests(ctx context.Context, arg CountFundRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFundRequests, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemRequests = `-- name: CountItemRequests :one
SELECT COUNT(*) FROM item_requests WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
`

type CountItemRequestsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountItemRequests(ctx context.Context, arg CountItemRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItemRequests, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const creditGuildBank = `-- name: CreditGuildBank :exec
UPDATE guild_bank SET balance = balance + $2::bigint, updated_at = NOW() WHERE guild_id = $1
`

type CreditGuildBankParams struct {
	GuildID uuid.UUID
	Amount  int64
}

func (q *Queries) CreditGuildBank(ctx context.Context, arg CreditGuildBankParams) error {
	_, err := q.db.Exec(ctx, creditGuildBank, arg.GuildID, arg.Amount)
	return err
}

const creditWallet = `-- name: CreditWallet :one
UPDATE wallets SET balance = balance + $3::bigint, updated_at = NOW()
WHERE user_id = $1 AND guild_id = $2
RETURNING balance
`

type CreditWalletParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
	Amount  int64
}

func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) (int64, error) {
	row := q.db.QueryRow(ctx, creditWallet, arg.UserID, arg.GuildID, arg.Amount)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const deductGuildBankIfSufficient = `-- name: DeductGuildBankIfSufficient :one
UPDATE guild_bank SET balance = balance - $2::bigint, updated_at = NOW()
WHERE guild_id = $1 AND balance >= $2::bigint
RETURNING balance
`

type DeductGuildBankIfSufficientParams struct {
	GuildID uuid.UUID
	Amount  int64
}

func (q *Queries) DeductGuildBankIfSufficient(ctx context.Context, arg DeductGuildBankIfSufficientParams) (int64, error) {
	row := q.db.QueryRow(ctx, deductGuildBankIfSufficient, arg.GuildID, arg.Amount)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const deductWalletIfSufficient = `-- name: DeductWalletIfSufficient :one
UPDATE wallets SET balance = balance - $3::bigint, updated_at = NOW()
WHERE user_id = $1 AND guild_id = $2 AND balance >= $3::bigint
RETURNING balance
`

type DeductWalletIfSufficientParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
	Amount  int64
}

func (q *Queries) DeductWalletIfSufficient(ctx context.Context, arg DeductWalletIfSufficientParams) (int64, error) {
	row := q.db.QueryRow(ctx, deductWalletIfSufficient, arg.UserID, arg.GuildID, arg.Amount)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const deleteBackpackItemReturningItem = `-- name: DeleteBackpackItemReturningItem :one
DELETE FROM backpack_items
WHERE id = $1 AND owner_id = $2 AND guild_id = $3 AND locked_by_type IS NULL AND delivery_requested_at IS NULL
RETURNING item
`

type DeleteBackpackItemReturningItemParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteBackpackItemReturningItem(ctx context.Context, arg DeleteBackpackItemReturningItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteBackpackItemReturningItem, arg.ID, arg.OwnerID, arg.GuildID)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const deleteBankItemReturningItem = `-- name: DeleteBankItemReturningItem :one
DELETE FROM bank_items WHERE id = $1 AND guild_id = $2 AND locked_by_type IS NULL
RETURNING item
`

type DeleteBankItemReturningItemParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteBankItemReturningItem(ctx context.Context, arg DeleteBankItemReturningItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteBankItemReturningItem, arg.ID, arg.GuildID)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const ensureGuildBank = `-- name: EnsureGuildBank :exec
INSERT INTO guild_bank (guild_id) VALUES ($1)
ON CONFLICT (guild_id) DO NOTHING
`

func (q *Queries) EnsureGuildBank(ctx context.Context, guildID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureGuildBank, guildID)
	return err
}

const getBankItemForUpdate = `-- name: GetBankItemForUpdate :one
SELECT item, COALESCE(locked_by_type, '') AS locked_by_type FROM bank_items
WHERE id = $1 AND guild_id = $2
FOR UPDATE
`

type GetBankItemForUpdateParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetBankItemForUpdateRow struct {
	Item         []byte
	LockedByType string
}

func (q *Queries) GetBankItemForUpdate(ctx context.Context, arg GetBankItemForUpdateParams) (GetBankItemForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBankItemForUpdate, arg.ID, arg.GuildID)
	var i GetBankItemForUpdateRow
	err := row.Scan(&i.Item, &i.LockedByType)
	return i, err
}

const getGuildBank = `-- name: GetGuildBank :one
SELECT id, guild_id, balance, currency, created_at, updated_at
FROM guild_bank WHERE guild_id = $1
`

func (q *Queries) GetGuildBank(ctx context.Context, guildID uuid.UUID) (GuildBank, error) {
	row := q.db.QueryRow(ctx, getGuildBank, guildID)
	var i GuildBank
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDisplayName = `-- name: GetUserDisplayName :one
SELECT COALESCE(member_display_name($1::uuid, $2::uuid), '')::text AS display_name
`

type GetUserDisplayNameParams struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetUserDisplayName(ctx context.Context, arg GetUserDisplayNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserDisplayName, arg.GuildID, arg.UserID)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const insertBackpackItemFromRequest = `-- name: InsertBackpackItemFromRequest :exec
INSERT INTO backpack_items (id, owner_id, guild_id, item, source, source_id)
VALUES ($1, $2, $3, $4::jsonb, 'bank_item_request', $5)
`

type InsertBackpackItemFromRequestParams struct {
	ID       uuid.UUID
	OwnerID  uuid.UUID
	GuildID  uuid.UUID
	Item     []byte
	SourceID *uuid.UUID
}

func (q *Queries) InsertBackpackItemFromRequest(ctx context.Context, arg InsertBackpackItemFromRequestParams) error {
	_, err := q.db.Exec(ctx, insertBackpackItemFromRequest,
		arg.ID,
		arg.OwnerID,
		arg.GuildID,
		arg.Item,
		arg.SourceID,
	)
	return err
}

const insertBankContribution = `-- name: InsertBankContribution :one
INSERT INTO bank_contributions (guild_id, user_id, username, amount, note)
VALUES ($1, $2, $4::text, $3, NULLIF($5::text, ''))
RETURNING id, created_at
`

type InsertBankContributionParams struct {
	GuildID  uuid.UUID
	UserID   uuid.UUID
	Amount   int64
	Username string
	Note     string
}

type InsertBankContributionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertBankContribution(ctx context.Context, arg InsertBankContributionParams) (InsertBankContributionRow, error) {
	row := q.db.QueryRow(ctx, insertBankContribution,
		arg.GuildID,
		arg.UserID,
		arg.Amount,
		arg.Username,
		arg.Note,
	)
	var i InsertBankContributionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertBankItem = `-- name: InsertBankItem :one
INSERT INTO bank_items (id, guild_id, donor_id, donor_name, item, note)
VALUES ($1, $2, $3, $4::text, $5::jsonb,
        NULLIF($6::text, ''))
RETURNING id, guild_id, donor_id, donor_name, item, quantity,
          COALESCE(note, '') AS note,
          donated_at
`

type InsertBankItemParams struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	DonorID   uuid.UUID
	DonorName string
	Item      []byte
	Note      string
}

type InsertBankItemRow struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	DonorID   uuid.UUID
	DonorName string
	Item      []byte
	Quantity  int32
	Note      string
	DonatedAt time.Time
}

func (q *Queries) InsertBankItem(ctx context.Context, arg InsertBankItemParams) (InsertBankItemRow, error) {
	row := q.db.QueryRow(ctx, insertBankItem,
		arg.ID,
		arg.GuildID,
		arg.DonorID,
		arg.DonorName,
		arg.Item,
		arg.Note,
	)
	var i InsertBankItemRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.DonorID,
		&i.DonorName,
		&i.Item,
		&i.Quantity,
		&i.Note,
		&i.DonatedAt,
	)
	return i, err
}

const insertFundRequest = `-- name: InsertFundRequest :one
INSERT INTO fund_requests (guild_id, requester_id, requester_name, amount, reason)
VALUES ($1, $2, $4::text, $3, NULLIF($5::text, ''))
RETURNING fund_requests.id, fund_requests.guild_id, fund_requests.requester_id, fund_requests.requester_name,
          (SELECT COALESCE(u.avatar_url, '') FROM users u WHERE u.id = fund_requests.requester_id)::text AS requester_avatar_url,
          fund_requests.amount,
          COALESCE(fund_requests.reason, '')      AS reason,
          fund_requests.status,
          fund_requests.reviewer_id,
          COALESCE(fund_requests.review_note, '') AS review_note,
          fund_requests.created_at, fund_requests.reviewed_at
`

type InsertFundRequestParams struct {
	GuildID       uuid.UUID
	RequesterID   uuid.UUID
	Amount        int64
	RequesterName string
	Reason        string
}

type InsertFundRequestRow struct {
	ID                 uuid.UUID
	GuildID            uuid.UUID
	RequesterID        uuid.UUID
	RequesterName      string
	RequesterAvatarUrl string
	Amount             int64
	Reason             string
	Status             string
	ReviewerID         *uuid.UUID
	ReviewNote         string
	CreatedAt          time.Time
	ReviewedAt         pgtype.Timestamptz
}

func (q *Queries) InsertFundRequest(ctx context.Context, arg InsertFundRequestParams) (InsertFundRequestRow, error) {
	row := q.db.QueryRow(ctx, insertFundRequest,
		arg.GuildID,
		arg.RequesterID,
		arg.Amount,
		arg.RequesterName,
		arg.Reason,
	)
	var i InsertFundRequestRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.RequesterID,
		&i.RequesterName,
		&i.RequesterAvatarUrl,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const insertItemRequest = `-- name: InsertItemRequest :one
INSERT INTO item_requests (guild_id, bank_item_id, requester_id, requester_name, reason, item)
SELECT bi.guild_id, bi.id, $1, $2::text,
       NULLIF($3::text, ''), bi.item
FROM bank_items bi
WHERE bi.id = $4 AND bi.guild_id = $5 AND bi.locked_by_type IS NULL
RETURNING item_requests.id, item_requests.guild_id, item_requests.bank_item_id, item_requests.requester_id, item_requests.requester_name,
          (SELECT COALESCE(u.avatar_url, '') FROM users u WHERE u.id = item_requests.requester_id)::text AS requester_avatar_url,
          COALESCE(item_requests.reason, '')      AS reason,
          item_requests.status,
          item_requests.reviewer_id,
          COALESCE(item_requests.review_note, '') AS review_note,
          item_requests.created_at, item_requests.reviewed_at, item_requests.item
`

type InsertItemRequestParams struct {
	RequesterID   uuid.UUID
	RequesterName string
	Reason        string
	BankItemID    uuid.UUID
	GuildID       uuid.UUID
}

type InsertItemRequestRow struct {
	ID                 uuid.UUID
	GuildID            uuid.UUID
	BankItemID         *uuid.UUID
	RequesterID        uuid.UUID
	RequesterName      string
	RequesterAvatarUrl string
	Reason             string
	Status             string
	ReviewerID         *uuid.UUID
	ReviewNote         string
	CreatedAt          time.Time
	ReviewedAt         pgtype.Timestamptz
	Item               []byte
}

func (q *Queries) InsertItemRequest(ctx context.Context, arg InsertItemRequestParams) (InsertItemRequestRow, error) {
	row := q.db.QueryRow(ctx, insertItemRequest,
		arg.RequesterID,
		arg.RequesterName,
		arg.Reason,
		arg.BankItemID,
		arg.GuildID,
	)
	var i InsertItemRequestRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.BankItemID,
		&i.RequesterID,
		&i.RequesterName,
		&i.RequesterAvatarUrl,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.Item,
	)
	return i, err
}

const listBankContributions = `-- name: ListBankContributions :many
SELECT bc.id, bc.guild_id, bc.user_id,
       COALESCE(NULLIF(member_display_name(bc.guild_id, bc.user_id), ''), bc.username)::text AS username,
       COALESCE(u.avatar_url, '') AS avatar_url,
       bc.amount,
       COALESCE(bc.note, '')      AS note,
       bc.created_at, bc.kind, bc.items, bc.roll_call_id,
       COALESCE(bc.reference_type, '') AS reference_type,
       bc.reference_id
FROM (
    SELECT c.id, c.guild_id, c.user_id, c.username, c.amount, c.note, c.created_at, c.kind, c.items,
           c.roll_call_id, c.reference_type, c.reference_id
    FROM bank_contributions c
    WHERE c.guild_id = $1
    UNION ALL
    SELECT p.roll_call_id, p.guild_id, COALESCE(rc.completed_by, rc.created_by), '',
           p.total - p.distributed - p.retracted, rc.title, rc.completed_at, 'roll_call_gold_kept', '[]'::jsonb,
           p.roll_call_id, NULL, NULL::uuid
    FROM roll_call_gold_pots p
    JOIN roll_calls rc ON rc.id = p.roll_call_id
    WHERE p.guild_id = $1 AND rc.completed_at IS NOT NULL AND p.total - p.distributed - p.retracted > 0
) bc
LEFT JOIN users u ON u.id = bc.user_id
ORDER BY bc.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListBankContributionsParams struct {
	GuildID    uuid.UUID
	PageOffset int32
	PageSize   int32
}

type ListBankContributionsRow struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	UserID        uuid.UUID
	Username      string
	AvatarUrl     string
	Amount        int64
	Note          string
	CreatedAt     time.Time
	Kind          string
	Items         []byte
	RollCallID    *uuid.UUID
	ReferenceType string
	ReferenceID   *uuid.UUID
}

func (q *Queries) ListBankContributions(ctx context.Context, arg ListBankContributionsParams) ([]ListBankContributionsRow, error) {
	rows, err := q.db.Query(ctx, listBankContributions, arg.GuildID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankContributionsRow{}
	for rows.Next() {
		var i ListBankContributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.UserID,
			&i.Username,
			&i.AvatarUrl,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
			&i.Kind,
			&i.Items,
			&i.RollCallID,
			&i.ReferenceType,
			&i.ReferenceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankItems = `-- name: ListBankItems :many
SELECT bi.id, bi.guild_id, bi.donor_id,
       COALESCE(NULLIF(member_display_name(bi.guild_id, bi.donor_id), ''), bi.donor_name)::text AS donor_name,
       bi.item, bi.quantity,
       COALESCE(bi.note, '') AS note,
       bi.donated_at,
       bi.roll_call_id,
       COALESCE(c.title, '') AS roll_call_title,
       (c.completed_at IS NOT NULL)::bool AS roll_call_completed,
       (SELECT COUNT(*) FROM item_requests ir WHERE ir.bank_item_id = bi.id AND ir.status = 'pending')::int AS pending_request_count,
       EXISTS (
           SELECT 1 FROM item_requests ir
           WHERE ir.bank_item_id = bi.id AND ir.status = 'pending' AND ir.requester_id = $2
       ) AS requested_by_me,
       COALESCE(bi.locked_by_type, '') AS locked_by_type,
       bi.locked_by_id
FROM bank_items bi
LEFT JOIN roll_calls c ON c.id = bi.roll_call_id
WHERE bi.guild_id = $1
  AND ($3::text = '' OR bi.item->>'category' = $3::text)
  AND ($4::text   = '' OR bi.item->>'rarity'   = $4::text)
  AND ($5::text  = '' OR bi.roll_call_id::text  = $5::text)
ORDER BY bi.donated_at DESC
LIMIT $7::int OFFSET $6::int
`

type ListBankItemsParams struct {
	GuildID        uuid.UUID
	ViewerID       uuid.UUID
	CategoryFilter string
	RarityFilter   string
	RollCallFilter string
	PageOffset     int32
	PageSize       int32
}

type ListBankItemsRow struct {
	ID                  uuid.UUID
	GuildID             uuid.UUID
	DonorID             uuid.UUID
	DonorName           string
	Item                []byte
	Quantity            int32
	Note                string
	DonatedAt           time.Time
	RollCallID          *uuid.UUID
	RollCallTitle       string
	RollCallCompleted   bool
	PendingRequestCount int32
	RequestedByMe       bool
	LockedByType        string
	LockedByID          *uuid.UUID
}

func (q *Queries) ListBankItems(ctx context.Context, arg ListBankItemsParams) ([]ListBankItemsRow, error) {
	rows, err := q.db.Query(ctx, listBankItems,
		arg.GuildID,
		arg.ViewerID,
		arg.CategoryFilter,
		arg.RarityFilter,
		arg.RollCallFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankItemsRow{}
	for rows.Next() {
		var i ListBankItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.DonorID,
			&i.DonorName,
			&i.Item,
			&i.Quantity,
			&i.Note,
			&i.DonatedAt,
			&i.RollCallID,
			&i.RollCallTitle,
			&i.RollCallCompleted,
			&i.PendingRequestCount,
			&i.RequestedByMe,
			&i.LockedByType,
			&i.LockedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFundRequests = `-- name: ListFundRequests :many
SELECT fr.id, fr.guild_id, fr.requester_id,
       COALESCE(NULLIF(member_display_name(fr.guild_id, fr.requester_id), ''), fr.requester_name)::text AS requester_name,
       COALESCE(u.avatar_url, '')   AS requester_avatar_url,
       fr.amount,
       COALESCE(fr.reason, '')      AS reason,
       fr.status,
       fr.reviewer_id,
       COALESCE(fr.review_note, '') AS review_note,
       fr.created_at, fr.reviewed_at
FROM fund_requests fr
LEFT JOIN users u ON u.id = fr.requester_id
WHERE fr.guild_id = $1
  AND ($2::text = '' OR fr.status = $2::text)
ORDER BY fr.created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListFundRequestsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListFundRequestsRow struct {
	ID                 uuid.UUID
	GuildID            uuid.UUID
	RequesterID        uuid.UUID
	RequesterName      string
	RequesterAvatarUrl string
	Amount             int64
	Reason             string
	Status             string
	ReviewerID         *uuid.UUID
	ReviewNote         string
	CreatedAt          time.Time
	ReviewedAt         pgtype.Timestamptz
}

func (q *Queries) ListFundRequests(ctx context.Context, arg ListFundRequestsParams) ([]ListFundRequestsRow, error) {
	rows, err := q.db.Query(ctx, listFundRequests,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFundRequestsRow{}
	for rows.Next() {
		var i ListFundRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.RequesterID,
			&i.RequesterName,
			&i.RequesterAvatarUrl,
			&i.Amount,
			&i.Reason,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewNote,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemRequests = `-- name: ListItemRequests :many
SELECT ir.id, ir.guild_id, ir.bank_item_id, ir.requester_id,
       COALESCE(NULLIF(member_display_name(ir.guild_id, ir.requester_id), ''), ir.requester_name)::text AS requester_name,
       COALESCE(u.avatar_url, '')   AS requester_avatar_url,
       COALESCE(ir.reason, '')      AS reason,
       ir.status,
       ir.reviewer_id,
       COALESCE(ir.review_note, '') AS review_note,
       ir.created_at, ir.reviewed_at, ir.item
FROM item_requests ir
LEFT JOIN users u ON u.id = ir.requester_id
WHERE ir.guild_id = $1
  AND ($2::text = '' OR ir.status = $2::text)
ORDER BY ir.created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListItemRequestsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListItemRequestsRow struct {
	ID                 uuid.UUID
	GuildID            uuid.UUID
	BankItemID         *uuid.UUID
	RequesterID        uuid.UUID
	RequesterName      string
	RequesterAvatarUrl string
	Reason             string
	Status             string
	ReviewerID         *uuid.UUID
	ReviewNote         string
	CreatedAt          time.Time
	ReviewedAt         pgtype.Timestamptz
	Item               []byte
}

func (q *Queries) ListItemRequests(ctx context.Context, arg ListItemRequestsParams) ([]ListItemRequestsRow, error) {
	rows, err := q.db.Query(ctx, listItemRequests,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemRequestsRow{}
	for rows.Next() {
		var i ListItemRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.BankItemID,
			&i.RequesterID,
			&i.RequesterName,
			&i.RequesterAvatarUrl,
			&i.Reason,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewNote,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.Item,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopBankContributors = `-- name: ListTopBankContributors :many
SELECT bc.user_id,
       COALESCE(NULLIF(member_display_name(bc.guild_id, bc.user_id), ''), MAX(bc.username))::text AS username,
       COALESCE(u.avatar_url, '') AS avatar_url,
       SUM(bc.amount)::bigint     AS total
FROM bank_contributions bc
LEFT JOIN users u ON u.id = bc.user_id
WHERE bc.guild_id = $1 AND bc.kind = 'gold'
GROUP BY bc.guild_id, bc.user_id, u.avatar_url
ORDER BY total DESC
LIMIT 5
`

type ListTopBankContributorsRow struct {
	UserID    uuid.UUID
	Username  string
	AvatarUrl string
	Total     int64
}

func (q *Queries) ListTopBankContributors(ctx context.Context, guildID uuid.UUID) ([]ListTopBankContributorsRow, error) {
	rows, err := q.db.Query(ctx, listTopBankContributors, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopBankContributorsRow{}
	for rows.Next() {
		var i ListTopBankContributorsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.AvatarUrl,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFundRequest = `-- name: LockFundRequest :one
SELECT amount, requester_id, status FROM fund_requests
WHERE id = $1 AND guild_id = $2
FOR UPDATE
`

type LockFundRequestParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type LockFundRequestRow struct {
	Amount      int64
	RequesterID uuid.UUID
	Status      string
}

func (q *Queries) LockFundRequest(ctx context.Context, arg LockFundRequestParams) (LockFundRequestRow, error) {
	row := q.db.QueryRow(ctx, lockFundRequest, arg.ID, arg.GuildID)
	var i LockFundRequestRow
	err := row.Scan(&i.Amount, &i.RequesterID, &i.Status)
	return i, err
}

const lockItemRequest = `-- name: LockItemRequest :one
SELECT bank_item_id, requester_id, status FROM item_requests
WHERE id = $1 AND guild_id = $2
FOR UPDATE
`

type LockItemRequestParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type LockItemRequestRow struct {
	BankItemID  *uuid.UUID
	RequesterID uuid.UUID
	Status      string
}

func (q *Queries) LockItemRequest(ctx context.Context, arg LockItemRequestParams) (LockItemRequestRow, error) {
	row := q.db.QueryRow(ctx, lockItemRequest, arg.ID, arg.GuildID)
	var i LockItemRequestRow
	err := row.Scan(&i.BankItemID, &i.RequesterID, &i.Status)
	return i, err
}

const rejectCompetingItemRequests = `-- name: RejectCompetingItemRequests :exec
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    reviewed_at = NOW()
WHERE bank_item_id = $2 AND guild_id = $3
  AND id <> $4 AND status = 'pending'
`

type RejectCompetingItemRequestsParams struct {
	ReviewerID *uuid.UUID
	BankItemID *uuid.UUID
	GuildID    uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) RejectCompetingItemRequests(ctx context.Context, arg RejectCompetingItemRequestsParams) error {
	_, err := q.db.Exec(ctx, rejectCompetingItemRequests,
		arg.ReviewerID,
		arg.BankItemID,
		arg.GuildID,
		arg.ID,
	)
	return err
}

const updateFundRequestStatus = `-- name: UpdateFundRequestStatus :one
UPDATE fund_requests SET
    status = $1::text,
    reviewer_id = $2,
    review_note = NULLIF($3::text, ''),
    reviewed_at = NOW()
WHERE fund_requests.id = $4 AND fund_requests.guild_id = $5 AND fund_requests.status = 'pending'
RETURNING fund_requests.id, fund_requests.guild_id, fund_requests.requester_id, fund_requests.requester_name,
          (SELECT COALESCE(u.avatar_url, '') FROM users u WHERE u.id = fund_requests.requester_id)::text AS requester_avatar_url,
          fund_requests.amount,
          COALESCE(fund_requests.reason, '')      AS reason,
          fund_requests.status,
          fund_requests.reviewer_id,
          COALESCE(fund_requests.review_note, '') AS review_note,
          fund_requests.created_at, fund_requests.reviewed_at
`

type UpdateFundRequestStatusParams struct {
	Status     string
	ReviewerID *uuid.UUID
	ReviewNote string
	ID         uuid.UUID
	GuildID    uuid.UUID
}

type UpdateFundRequestStatusRow struct {
	ID                 uuid.UUID
	GuildID            uuid.UUID
	RequesterID        uuid.UUID
	RequesterName      string
	RequesterAvatarUrl string
	Amount             int64
	Reason             string
	Status             string
	ReviewerID         *uuid.UUID
	ReviewNote         string
	CreatedAt          time.Time
	ReviewedAt         pgtype.Timestamptz
}

func (q *Queries) UpdateFundRequestStatus(ctx context.Context, arg UpdateFundRequestStatusParams) (UpdateFundRequestStatusRow, error) {
	row := q.db.QueryRow(ctx, updateFundRequestStatus,
		arg.Status,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateFundRequestStatusRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.RequesterID,
		&i.RequesterName,
		&i.RequesterAvatarUrl,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const updateItemRequestStatus = `-- name: UpdateItemRequestStatus :one
UPDATE item_requests SET
    status = $1::text,
    reviewer_id = $2,
    review_note = NULLIF($3::text, ''),
    reviewed_at = NOW()
WHERE item_requests.id = $4 AND item_requests.guild_id = $5 AND item_requests.status = 'pending'
RETURNING item_requests.id, item_requests.guild_id, item_requests.bank_item_id, item_requests.requester_id, item_requests.requester_name,
          (SELECT COALESCE(u.avatar_url, '') FROM users u WHERE u.id = item_requests.requester_id)::text AS requester_avatar_url,
          COALESCE(item_requests.reason, '')      AS reason,
          item_requests.status,
          item_requests.reviewer_id,
          COALESCE(item_requests.review_note, '') AS review_note,
          item_requests.created_at, item_requests.reviewed_at, item_requests.item
`

type UpdateItemRequestStatusParams struct {
	Status     string
	ReviewerID *uuid.UUID
	ReviewNote string
	ID         uuid.UUID
	GuildID    uuid.UUID
}

type UpdateItemRequestStatusRow struct {
	ID                 uuid.UUID
	GuildID            uuid.UUID
	BankItemID         *uuid.UUID
	RequesterID        uuid.UUID
	RequesterName      string
	RequesterAvatarUrl string
	Reason             string
	Status             string
	ReviewerID         *uuid.UUID
	ReviewNote         string
	CreatedAt          time.Time
	ReviewedAt         pgtype.Timestamptz
	Item               []byte
}

func (q *Queries) UpdateItemRequestStatus(ctx context.Context, arg UpdateItemRequestStatusParams) (UpdateItemRequestStatusRow, error) {
	row := q.db.QueryRow(ctx, updateItemRequestStatus,
		arg.Status,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateItemRequestStatusRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.BankItemID,
		&i.RequesterID,
		&i.RequesterName,
		&i.RequesterAvatarUrl,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.Item,
	)
	return i, err
}
