// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBankContributions = `-- name: CountBankContributions :one
SELECT COUNT(*) FROM bank_contributions WHERE guild_id = $1
`

func (q *Queries) CountBankContributions(ctx context.Context, guildID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBankContributions, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBankItems = `-- name: CountBankItems :one
SELECT COUNT(*) FROM bank_items
WHERE guild_id = $1
  AND ($2::text = '' OR item->>'category' = $2::text)
  AND ($3::text   = '' OR item->>'rarity'   = $3::text)
`

type CountBankItemsParams struct {
	GuildID        uuid.UUID
	CategoryFilter string
	RarityFilter   string
}

func (q *Queries) CountBankItems(ctx context.Context, arg CountBankItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBankItems, arg.GuildID, arg.CategoryFilter, arg.RarityFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFundRequests = `-- name: CountFundRequests :one
SELECT COUNT(*) FROM fund_requests WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
`

type CountFundRequestsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountFundRequests(ctx context.Context, arg CountFundRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFundRequests, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemRequests = `-- name: CountItemRequests :one
SELECT COUNT(*) FROM item_requests WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
`

type CountItemRequestsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountItemRequests(ctx context.Context, arg CountItemRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItemRequests, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const creditGuildBank = `-- name: CreditGuildBank :exec
UPDATE guild_bank SET balance = balance + $2::bigint, updated_at = NOW() WHERE guild_id = $1
`

type CreditGuildBankParams struct {
	GuildID uuid.UUID
	Amount  int64
}

func (q *Queries) CreditGuildBank(ctx context.Context, arg CreditGuildBankParams) error {
	_, err := q.db.Exec(ctx, creditGuildBank, arg.GuildID, arg.Amount)
	return err
}

const creditWallet = `-- name: CreditWallet :one
UPDATE wallets SET balance = balance + $3::bigint, updated_at = NOW()
WHERE user_id = $1 AND guild_id = $2
RETURNING balance
`

type CreditWalletParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
	Amount  int64
}

func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) (int64, error) {
	row := q.db.QueryRow(ctx, creditWallet, arg.UserID, arg.GuildID, arg.Amount)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const deductGuildBankIfSufficient = `-- name: DeductGuildBankIfSufficient :one
UPDATE guild_bank SET balance = balance - $2::bigint, updated_at = NOW()
WHERE guild_id = $1 AND balance >= $2::bigint
RETURNING balance
`

type DeductGuildBankIfSufficientParams struct {
	GuildID uuid.UUID
	Amount  int64
}

func (q *Queries) DeductGuildBankIfSufficient(ctx context.Context, arg DeductGuildBankIfSufficientParams) (int64, error) {
	row := q.db.QueryRow(ctx, deductGuildBankIfSufficient, arg.GuildID, arg.Amount)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const deductWalletIfSufficient = `-- name: DeductWalletIfSufficient :one
UPDATE wallets SET balance = balance - $3::bigint, updated_at = NOW()
WHERE user_id = $1 AND guild_id = $2 AND balance >= $3::bigint
RETURNING balance
`

type DeductWalletIfSufficientParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
	Amount  int64
}

func (q *Queries) DeductWalletIfSufficient(ctx context.Context, arg DeductWalletIfSufficientParams) (int64, error) {
	row := q.db.QueryRow(ctx, deductWalletIfSufficient, arg.UserID, arg.GuildID, arg.Amount)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const deleteBackpackItemReturningItem = `-- name: DeleteBackpackItemReturningItem :one
DELETE FROM backpack_items WHERE id = $1 AND owner_id = $2 AND guild_id = $3
RETURNING item
`

type DeleteBackpackItemReturningItemParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteBackpackItemReturningItem(ctx context.Context, arg DeleteBackpackItemReturningItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteBackpackItemReturningItem, arg.ID, arg.OwnerID, arg.GuildID)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const deleteBankItemReturningItem = `-- name: DeleteBankItemReturningItem :one
DELETE FROM bank_items WHERE id = $1 AND guild_id = $2
RETURNING item
`

type DeleteBankItemReturningItemParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteBankItemReturningItem(ctx context.Context, arg DeleteBankItemReturningItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteBankItemReturningItem, arg.ID, arg.GuildID)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const ensureGuildBank = `-- name: EnsureGuildBank :exec
INSERT INTO guild_bank (guild_id) VALUES ($1)
ON CONFLICT (guild_id) DO NOTHING
`

func (q *Queries) EnsureGuildBank(ctx context.Context, guildID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureGuildBank, guildID)
	return err
}

const getGuildBank = `-- name: GetGuildBank :one
SELECT id, guild_id, balance, currency, goal, created_at, updated_at
FROM guild_bank WHERE guild_id = $1
`

func (q *Queries) GetGuildBank(ctx context.Context, guildID uuid.UUID) (GuildBank, error) {
	row := q.db.QueryRow(ctx, getGuildBank, guildID)
	var i GuildBank
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Balance,
		&i.Currency,
		&i.Goal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDisplayName = `-- name: GetUserDisplayName :one
SELECT COALESCE(display_name, username, '')::text AS display_name
FROM users WHERE id = $1
`

func (q *Queries) GetUserDisplayName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserDisplayName, id)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const insertBackpackItemFromRequest = `-- name: InsertBackpackItemFromRequest :exec
INSERT INTO backpack_items (owner_id, guild_id, item, source, source_id)
VALUES ($1, $2, $3::jsonb, 'bank_item_request', $4)
`

type InsertBackpackItemFromRequestParams struct {
	OwnerID  uuid.UUID
	GuildID  uuid.UUID
	Item     []byte
	SourceID *uuid.UUID
}

func (q *Queries) InsertBackpackItemFromRequest(ctx context.Context, arg InsertBackpackItemFromRequestParams) error {
	_, err := q.db.Exec(ctx, insertBackpackItemFromRequest,
		arg.OwnerID,
		arg.GuildID,
		arg.Item,
		arg.SourceID,
	)
	return err
}

const insertBankContribution = `-- name: InsertBankContribution :one
INSERT INTO bank_contributions (guild_id, user_id, username, amount, note)
VALUES ($1, $2, $4::text, $3, NULLIF($5::text, ''))
RETURNING id, created_at
`

type InsertBankContributionParams struct {
	GuildID  uuid.UUID
	UserID   uuid.UUID
	Amount   int64
	Username string
	Note     string
}

type InsertBankContributionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertBankContribution(ctx context.Context, arg InsertBankContributionParams) (InsertBankContributionRow, error) {
	row := q.db.QueryRow(ctx, insertBankContribution,
		arg.GuildID,
		arg.UserID,
		arg.Amount,
		arg.Username,
		arg.Note,
	)
	var i InsertBankContributionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertBankItem = `-- name: InsertBankItem :one
INSERT INTO bank_items (guild_id, donor_id, donor_name, item, note)
VALUES ($1, $2, $3::text, $4::jsonb, NULLIF($5::text, ''))
RETURNING id, guild_id, donor_id, donor_name, item, quantity,
          COALESCE(note, '') AS note,
          donated_at
`

type InsertBankItemParams struct {
	GuildID   uuid.UUID
	DonorID   uuid.UUID
	DonorName string
	Item      []byte
	Note      string
}

type InsertBankItemRow struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	DonorID   uuid.UUID
	DonorName string
	Item      []byte
	Quantity  int32
	Note      string
	DonatedAt time.Time
}

func (q *Queries) InsertBankItem(ctx context.Context, arg InsertBankItemParams) (InsertBankItemRow, error) {
	row := q.db.QueryRow(ctx, insertBankItem,
		arg.GuildID,
		arg.DonorID,
		arg.DonorName,
		arg.Item,
		arg.Note,
	)
	var i InsertBankItemRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.DonorID,
		&i.DonorName,
		&i.Item,
		&i.Quantity,
		&i.Note,
		&i.DonatedAt,
	)
	return i, err
}

const insertFundRequest = `-- name: InsertFundRequest :one
INSERT INTO fund_requests (guild_id, requester_id, requester_name, amount, reason)
VALUES ($1, $2, $4::text, $3, NULLIF($5::text, ''))
RETURNING id, guild_id, requester_id, requester_name, amount,
          COALESCE(reason, '')      AS reason,
          status,
          reviewer_id,
          COALESCE(review_note, '') AS review_note,
          created_at, reviewed_at
`

type InsertFundRequestParams struct {
	GuildID       uuid.UUID
	RequesterID   uuid.UUID
	Amount        int64
	RequesterName string
	Reason        string
}

type InsertFundRequestRow struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	RequesterID   uuid.UUID
	RequesterName string
	Amount        int64
	Reason        string
	Status        string
	ReviewerID    *uuid.UUID
	ReviewNote    string
	CreatedAt     time.Time
	ReviewedAt    pgtype.Timestamptz
}

func (q *Queries) InsertFundRequest(ctx context.Context, arg InsertFundRequestParams) (InsertFundRequestRow, error) {
	row := q.db.QueryRow(ctx, insertFundRequest,
		arg.GuildID,
		arg.RequesterID,
		arg.Amount,
		arg.RequesterName,
		arg.Reason,
	)
	var i InsertFundRequestRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.RequesterID,
		&i.RequesterName,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const insertItemRequest = `-- name: InsertItemRequest :one
INSERT INTO item_requests (guild_id, bank_item_id, requester_id, requester_name, reason, item)
SELECT bi.guild_id, bi.id, $1, $2::text,
       NULLIF($3::text, ''), bi.item
FROM bank_items bi
WHERE bi.id = $4 AND bi.guild_id = $5
RETURNING id, guild_id, bank_item_id, requester_id, requester_name,
          COALESCE(reason, '')      AS reason,
          status,
          reviewer_id,
          COALESCE(review_note, '') AS review_note,
          created_at, reviewed_at, item
`

type InsertItemRequestParams struct {
	RequesterID   uuid.UUID
	RequesterName string
	Reason        string
	BankItemID    uuid.UUID
	GuildID       uuid.UUID
}

type InsertItemRequestRow struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	BankItemID    *uuid.UUID
	RequesterID   uuid.UUID
	RequesterName string
	Reason        string
	Status        string
	ReviewerID    *uuid.UUID
	ReviewNote    string
	CreatedAt     time.Time
	ReviewedAt    pgtype.Timestamptz
	Item          []byte
}

func (q *Queries) InsertItemRequest(ctx context.Context, arg InsertItemRequestParams) (InsertItemRequestRow, error) {
	row := q.db.QueryRow(ctx, insertItemRequest,
		arg.RequesterID,
		arg.RequesterName,
		arg.Reason,
		arg.BankItemID,
		arg.GuildID,
	)
	var i InsertItemRequestRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.BankItemID,
		&i.RequesterID,
		&i.RequesterName,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.Item,
	)
	return i, err
}

const listBankContributions = `-- name: ListBankContributions :many
SELECT id, guild_id, user_id, username, amount,
       COALESCE(note, '') AS note,
       created_at
FROM bank_contributions WHERE guild_id = $1
ORDER BY created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListBankContributionsParams struct {
	GuildID    uuid.UUID
	PageOffset int32
	PageSize   int32
}

type ListBankContributionsRow struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	UserID    uuid.UUID
	Username  string
	Amount    int64
	Note      string
	CreatedAt time.Time
}

func (q *Queries) ListBankContributions(ctx context.Context, arg ListBankContributionsParams) ([]ListBankContributionsRow, error) {
	rows, err := q.db.Query(ctx, listBankContributions, arg.GuildID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankContributionsRow{}
	for rows.Next() {
		var i ListBankContributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.UserID,
			&i.Username,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankItems = `-- name: ListBankItems :many
SELECT id, guild_id, donor_id, donor_name, item, quantity,
       COALESCE(note, '') AS note,
       donated_at
FROM bank_items
WHERE guild_id = $1
  AND ($2::text = '' OR item->>'category' = $2::text)
  AND ($3::text   = '' OR item->>'rarity'   = $3::text)
ORDER BY donated_at DESC
LIMIT $5::int OFFSET $4::int
`

type ListBankItemsParams struct {
	GuildID        uuid.UUID
	CategoryFilter string
	RarityFilter   string
	PageOffset     int32
	PageSize       int32
}

type ListBankItemsRow struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	DonorID   uuid.UUID
	DonorName string
	Item      []byte
	Quantity  int32
	Note      string
	DonatedAt time.Time
}

func (q *Queries) ListBankItems(ctx context.Context, arg ListBankItemsParams) ([]ListBankItemsRow, error) {
	rows, err := q.db.Query(ctx, listBankItems,
		arg.GuildID,
		arg.CategoryFilter,
		arg.RarityFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankItemsRow{}
	for rows.Next() {
		var i ListBankItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.DonorID,
			&i.DonorName,
			&i.Item,
			&i.Quantity,
			&i.Note,
			&i.DonatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFundRequests = `-- name: ListFundRequests :many
SELECT id, guild_id, requester_id, requester_name, amount,
       COALESCE(reason, '')      AS reason,
       status,
       reviewer_id,
       COALESCE(review_note, '') AS review_note,
       created_at, reviewed_at
FROM fund_requests
WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
ORDER BY created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListFundRequestsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListFundRequestsRow struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	RequesterID   uuid.UUID
	RequesterName string
	Amount        int64
	Reason        string
	Status        string
	ReviewerID    *uuid.UUID
	ReviewNote    string
	CreatedAt     time.Time
	ReviewedAt    pgtype.Timestamptz
}

func (q *Queries) ListFundRequests(ctx context.Context, arg ListFundRequestsParams) ([]ListFundRequestsRow, error) {
	rows, err := q.db.Query(ctx, listFundRequests,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFundRequestsRow{}
	for rows.Next() {
		var i ListFundRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.RequesterID,
			&i.RequesterName,
			&i.Amount,
			&i.Reason,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewNote,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemRequests = `-- name: ListItemRequests :many
SELECT id, guild_id, bank_item_id, requester_id, requester_name,
       COALESCE(reason, '')      AS reason,
       status,
       reviewer_id,
       COALESCE(review_note, '') AS review_note,
       created_at, reviewed_at, item
FROM item_requests
WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
ORDER BY created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListItemRequestsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListItemRequestsRow struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	BankItemID    *uuid.UUID
	RequesterID   uuid.UUID
	RequesterName string
	Reason        string
	Status        string
	ReviewerID    *uuid.UUID
	ReviewNote    string
	CreatedAt     time.Time
	ReviewedAt    pgtype.Timestamptz
	Item          []byte
}

func (q *Queries) ListItemRequests(ctx context.Context, arg ListItemRequestsParams) ([]ListItemRequestsRow, error) {
	rows, err := q.db.Query(ctx, listItemRequests,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemRequestsRow{}
	for rows.Next() {
		var i ListItemRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.BankItemID,
			&i.RequesterID,
			&i.RequesterName,
			&i.Reason,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewNote,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.Item,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopBankContributors = `-- name: ListTopBankContributors :many
SELECT bc.user_id,
       bc.username,
       COALESCE(u.avatar_url, '') AS avatar_url,
       SUM(bc.amount)::bigint     AS total
FROM bank_contributions bc
LEFT JOIN users u ON u.id = bc.user_id
WHERE bc.guild_id = $1
GROUP BY bc.user_id, bc.username, u.avatar_url
ORDER BY total DESC
LIMIT 5
`

type ListTopBankContributorsRow struct {
	UserID    uuid.UUID
	Username  string
	AvatarUrl string
	Total     int64
}

func (q *Queries) ListTopBankContributors(ctx context.Context, guildID uuid.UUID) ([]ListTopBankContributorsRow, error) {
	rows, err := q.db.Query(ctx, listTopBankContributors, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopBankContributorsRow{}
	for rows.Next() {
		var i ListTopBankContributorsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.AvatarUrl,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFundRequest = `-- name: LockFundRequest :one
SELECT amount, requester_id, status FROM fund_requests
WHERE id = $1 AND guild_id = $2
FOR UPDATE
`

type LockFundRequestParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type LockFundRequestRow struct {
	Amount      int64
	RequesterID uuid.UUID
	Status      string
}

func (q *Queries) LockFundRequest(ctx context.Context, arg LockFundRequestParams) (LockFundRequestRow, error) {
	row := q.db.QueryRow(ctx, lockFundRequest, arg.ID, arg.GuildID)
	var i LockFundRequestRow
	err := row.Scan(&i.Amount, &i.RequesterID, &i.Status)
	return i, err
}

const lockItemRequest = `-- name: LockItemRequest :one
SELECT bank_item_id, requester_id, status FROM item_requests
WHERE id = $1 AND guild_id = $2
FOR UPDATE
`

type LockItemRequestParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type LockItemRequestRow struct {
	BankItemID  *uuid.UUID
	RequesterID uuid.UUID
	Status      string
}

func (q *Queries) LockItemRequest(ctx context.Context, arg LockItemRequestParams) (LockItemRequestRow, error) {
	row := q.db.QueryRow(ctx, lockItemRequest, arg.ID, arg.GuildID)
	var i LockItemRequestRow
	err := row.Scan(&i.BankItemID, &i.RequesterID, &i.Status)
	return i, err
}

const rejectCompetingItemRequests = `-- name: RejectCompetingItemRequests :exec
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    reviewed_at = NOW()
WHERE bank_item_id = $2 AND guild_id = $3
  AND id <> $4 AND status = 'pending'
`

type RejectCompetingItemRequestsParams struct {
	ReviewerID *uuid.UUID
	BankItemID *uuid.UUID
	GuildID    uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) RejectCompetingItemRequests(ctx context.Context, arg RejectCompetingItemRequestsParams) error {
	_, err := q.db.Exec(ctx, rejectCompetingItemRequests,
		arg.ReviewerID,
		arg.BankItemID,
		arg.GuildID,
		arg.ID,
	)
	return err
}

const updateFundRequestStatus = `-- name: UpdateFundRequestStatus :one
UPDATE fund_requests SET
    status = $1::text,
    reviewer_id = $2,
    review_note = NULLIF($3::text, ''),
    reviewed_at = NOW()
WHERE id = $4 AND guild_id = $5 AND status = 'pending'
RETURNING id, guild_id, requester_id, requester_name, amount,
          COALESCE(reason, '')      AS reason,
          status,
          reviewer_id,
          COALESCE(review_note, '') AS review_note,
          created_at, reviewed_at
`

type UpdateFundRequestStatusParams struct {
	Status     string
	ReviewerID *uuid.UUID
	ReviewNote string
	ID         uuid.UUID
	GuildID    uuid.UUID
}

type UpdateFundRequestStatusRow struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	RequesterID   uuid.UUID
	RequesterName string
	Amount        int64
	Reason        string
	Status        string
	ReviewerID    *uuid.UUID
	ReviewNote    string
	CreatedAt     time.Time
	ReviewedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateFundRequestStatus(ctx context.Context, arg UpdateFundRequestStatusParams) (UpdateFundRequestStatusRow, error) {
	row := q.db.QueryRow(ctx, updateFundRequestStatus,
		arg.Status,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateFundRequestStatusRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.RequesterID,
		&i.RequesterName,
		&i.Amount,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const updateItemRequestStatus = `-- name: UpdateItemRequestStatus :one
UPDATE item_requests SET
    status = $1::text,
    reviewer_id = $2,
    review_note = NULLIF($3::text, ''),
    reviewed_at = NOW()
WHERE id = $4 AND guild_id = $5 AND status = 'pending'
RETURNING id, guild_id, bank_item_id, requester_id, requester_name,
          COALESCE(reason, '')      AS reason,
          status,
          reviewer_id,
          COALESCE(review_note, '') AS review_note,
          created_at, reviewed_at, item
`

type UpdateItemRequestStatusParams struct {
	Status     string
	ReviewerID *uuid.UUID
	ReviewNote string
	ID         uuid.UUID
	GuildID    uuid.UUID
}

type UpdateItemRequestStatusRow struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	BankItemID    *uuid.UUID
	RequesterID   uuid.UUID
	RequesterName string
	Reason        string
	Status        string
	ReviewerID    *uuid.UUID
	ReviewNote    string
	CreatedAt     time.Time
	ReviewedAt    pgtype.Timestamptz
	Item          []byte
}

func (q *Queries) UpdateItemRequestStatus(ctx context.Context, arg UpdateItemRequestStatusParams) (UpdateItemRequestStatusRow, error) {
	row := q.db.QueryRow(ctx, updateItemRequestStatus,
		arg.Status,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateItemRequestStatusRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.BankItemID,
		&i.RequesterID,
		&i.RequesterName,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewNote,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.Item,
	)
	return i, err
}
