// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkin_template.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCheckinTemplate = `-- name: CreateCheckinTemplate :one
INSERT INTO checkin_templates (guild_id, name, title, loot_list, created_by)
VALUES ($1, $3::text, $4::text, $5::jsonb, $2)
RETURNING id, guild_id, name, title, loot_list, created_by, created_at, updated_at
`

type CreateCheckinTemplateParams struct {
	GuildID   uuid.UUID
	CreatedBy uuid.UUID
	Name      string
	Title     string
	LootList  []byte
}

func (q *Queries) CreateCheckinTemplate(ctx context.Context, arg CreateCheckinTemplateParams) (CheckinTemplate, error) {
	row := q.db.QueryRow(ctx, createCheckinTemplate,
		arg.GuildID,
		arg.CreatedBy,
		arg.Name,
		arg.Title,
		arg.LootList,
	)
	var i CheckinTemplate
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Title,
		&i.LootList,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCheckinTemplate = `-- name: DeleteCheckinTemplate :execrows
DELETE FROM checkin_templates WHERE id = $1 AND guild_id = $2
`

type DeleteCheckinTemplateParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteCheckinTemplate(ctx context.Context, arg DeleteCheckinTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCheckinTemplate, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCheckinTemplates = `-- name: ListCheckinTemplates :many
SELECT id, guild_id, name, title, loot_list, created_by, created_at, updated_at
FROM checkin_templates
WHERE guild_id = $1
ORDER BY name ASC
`

func (q *Queries) ListCheckinTemplates(ctx context.Context, guildID uuid.UUID) ([]CheckinTemplate, error) {
	rows, err := q.db.Query(ctx, listCheckinTemplates, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckinTemplate{}
	for rows.Next() {
		var i CheckinTemplate
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Title,
			&i.LootList,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckinTemplate = `-- name: UpdateCheckinTemplate :one
UPDATE checkin_templates SET
    name       = $1::text,
    title      = $2::text,
    loot_list  = $3::jsonb,
    updated_at = NOW()
WHERE id = $4 AND guild_id = $5
RETURNING id, guild_id, name, title, loot_list, created_by, created_at, updated_at
`

type UpdateCheckinTemplateParams struct {
	Name     string
	Title    string
	LootList []byte
	ID       uuid.UUID
	GuildID  uuid.UUID
}

func (q *Queries) UpdateCheckinTemplate(ctx context.Context, arg UpdateCheckinTemplateParams) (CheckinTemplate, error) {
	row := q.db.QueryRow(ctx, updateCheckinTemplate,
		arg.Name,
		arg.Title,
		arg.LootList,
		arg.ID,
		arg.GuildID,
	)
	var i CheckinTemplate
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Title,
		&i.LootList,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
