// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkin.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelCheckin = `-- name: CancelCheckin :one
UPDATE checkins SET cancelled_at = NOW(), updated_at = NOW()
WHERE id = $1 AND guild_id = $2 AND cancelled_at IS NULL AND expire_time >= NOW()
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          created_at, updated_at
`

type CancelCheckinParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type CancelCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CancelCheckin(ctx context.Context, arg CancelCheckinParams) (CancelCheckinRow, error) {
	row := q.db.QueryRow(ctx, cancelCheckin, arg.ID, arg.GuildID)
	var i CancelCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkinExists = `-- name: CheckinExists :one
SELECT EXISTS(SELECT 1 FROM checkins WHERE id = $1 AND guild_id = $2)
`

type CheckinExistsParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) CheckinExists(ctx context.Context, arg CheckinExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkinExists, arg.ID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCheckinAttendees = `-- name: CountCheckinAttendees :one
SELECT COUNT(*) FROM checkin_attendees WHERE checkin_id = $1
`

func (q *Queries) CountCheckinAttendees(ctx context.Context, checkinID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckinAttendees, checkinID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCheckins = `-- name: CountCheckins :one
SELECT COUNT(*) FROM checkins WHERE guild_id = $1
  AND CASE
    WHEN $2::text = 'active'    THEN cancelled_at IS NULL AND expire_time >= NOW()
    WHEN $2::text = 'expired'   THEN cancelled_at IS NULL AND expire_time < NOW()
    WHEN $2::text = 'cancelled' THEN cancelled_at IS NOT NULL
    ELSE true
  END
`

type CountCheckinsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountCheckins(ctx context.Context, arg CountCheckinsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckins, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckin = `-- name: CreateCheckin :one
INSERT INTO checkins (guild_id, created_by, title, description, datetime, expire_time, image_url, loot_list)
VALUES (
    $1, $2, $3::text,
    NULLIF($4::text, ''),
    $5::text::timestamptz,
    $6::text::timestamptz,
    NULLIF($7::text, ''),
    $8::jsonb
)
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          created_at, updated_at
`

type CreateCheckinParams struct {
	GuildID     uuid.UUID
	CreatedBy   uuid.UUID
	Title       string
	Description string
	Datetime    string
	ExpireTime  string
	ImageUrl    string
	LootList    []byte
}

type CreateCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateCheckin(ctx context.Context, arg CreateCheckinParams) (CreateCheckinRow, error) {
	row := q.db.QueryRow(ctx, createCheckin,
		arg.GuildID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Datetime,
		arg.ExpireTime,
		arg.ImageUrl,
		arg.LootList,
	)
	var i CreateCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCheckin = `-- name: DeleteCheckin :execrows
DELETE FROM checkins WHERE id = $1 AND guild_id = $2
`

type DeleteCheckinParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteCheckin(ctx context.Context, arg DeleteCheckinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCheckin, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCheckin = `-- name: GetCheckin :one
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
       TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
       COALESCE(image_url, '') AS image_url,
       loot_list, attendance_count,
       (expire_time < NOW())::bool AS is_expired,
       (cancelled_at IS NOT NULL)::bool AS is_cancelled,
       created_at, updated_at
FROM checkins WHERE id = $1 AND guild_id = $2
`

type GetCheckinParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetCheckin(ctx context.Context, arg GetCheckinParams) (GetCheckinRow, error) {
	row := q.db.QueryRow(ctx, getCheckin, arg.ID, arg.GuildID)
	var i GetCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckinAttendanceWindow = `-- name: GetCheckinAttendanceWindow :one
SELECT expire_time, (cancelled_at IS NOT NULL)::bool AS is_cancelled
FROM checkins WHERE id = $1 AND guild_id = $2
`

type GetCheckinAttendanceWindowParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetCheckinAttendanceWindowRow struct {
	ExpireTime  time.Time
	IsCancelled bool
}

func (q *Queries) GetCheckinAttendanceWindow(ctx context.Context, arg GetCheckinAttendanceWindowParams) (GetCheckinAttendanceWindowRow, error) {
	row := q.db.QueryRow(ctx, getCheckinAttendanceWindow, arg.ID, arg.GuildID)
	var i GetCheckinAttendanceWindowRow
	err := row.Scan(&i.ExpireTime, &i.IsCancelled)
	return i, err
}

const getUserDisplayAndAvatar = `-- name: GetUserDisplayAndAvatar :one
SELECT COALESCE(member_display_name($1::uuid, id), '')::text AS display_name,
       COALESCE(avatar_url, '')                                                   AS avatar_url
FROM users WHERE id = $2
`

type GetUserDisplayAndAvatarParams struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
}

type GetUserDisplayAndAvatarRow struct {
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) GetUserDisplayAndAvatar(ctx context.Context, arg GetUserDisplayAndAvatarParams) (GetUserDisplayAndAvatarRow, error) {
	row := q.db.QueryRow(ctx, getUserDisplayAndAvatar, arg.GuildID, arg.UserID)
	var i GetUserDisplayAndAvatarRow
	err := row.Scan(&i.DisplayName, &i.AvatarUrl)
	return i, err
}

const incrementCheckinAttendance = `-- name: IncrementCheckinAttendance :exec
UPDATE checkins SET attendance_count = attendance_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementCheckinAttendance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCheckinAttendance, id)
	return err
}

const insertCheckinAttendee = `-- name: InsertCheckinAttendee :one
INSERT INTO checkin_attendees (checkin_id, user_id, display_name, avatar_url, notes)
VALUES ($1, $2, $3::text, $4::text, $5::text)
ON CONFLICT (checkin_id, user_id) DO NOTHING
RETURNING id
`

type InsertCheckinAttendeeParams struct {
	CheckinID   uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	AvatarUrl   string
	Notes       string
}

func (q *Queries) InsertCheckinAttendee(ctx context.Context, arg InsertCheckinAttendeeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCheckinAttendee,
		arg.CheckinID,
		arg.UserID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Notes,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertCheckinBankItem = `-- name: InsertCheckinBankItem :exec
INSERT INTO bank_items (id, guild_id, donor_id, donor_name, item, checkin_id)
VALUES ($1, $2, $3, $4::text, $5::jsonb, $6::uuid)
`

type InsertCheckinBankItemParams struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	DonorID   uuid.UUID
	DonorName string
	Item      []byte
	CheckinID uuid.UUID
}

func (q *Queries) InsertCheckinBankItem(ctx context.Context, arg InsertCheckinBankItemParams) error {
	_, err := q.db.Exec(ctx, insertCheckinBankItem,
		arg.ID,
		arg.GuildID,
		arg.DonorID,
		arg.DonorName,
		arg.Item,
		arg.CheckinID,
	)
	return err
}

const insertCheckinLootContribution = `-- name: InsertCheckinLootContribution :exec
INSERT INTO bank_contributions (guild_id, user_id, username, amount, note, kind, items, checkin_id)
VALUES ($1, $2, $3::text, 0, NULLIF($4::text, ''), 'checkin_loot',
        $5::jsonb, $6::uuid)
`

type InsertCheckinLootContributionParams struct {
	GuildID   uuid.UUID
	UserID    uuid.UUID
	Username  string
	Note      string
	Items     []byte
	CheckinID uuid.UUID
}

func (q *Queries) InsertCheckinLootContribution(ctx context.Context, arg InsertCheckinLootContributionParams) error {
	_, err := q.db.Exec(ctx, insertCheckinLootContribution,
		arg.GuildID,
		arg.UserID,
		arg.Username,
		arg.Note,
		arg.Items,
		arg.CheckinID,
	)
	return err
}

const isCheckinAttendee = `-- name: IsCheckinAttendee :one
SELECT EXISTS(SELECT 1 FROM checkin_attendees WHERE checkin_id = $1 AND user_id = $2)
`

type IsCheckinAttendeeParams struct {
	CheckinID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) IsCheckinAttendee(ctx context.Context, arg IsCheckinAttendeeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCheckinAttendee, arg.CheckinID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCheckinAttendees = `-- name: ListCheckinAttendees :many
SELECT ca.id, ca.checkin_id, ca.user_id,
       COALESCE(NULLIF(member_display_name(c.guild_id, ca.user_id), ''), ca.display_name, '')::text AS display_name,
       COALESCE(NULLIF(u.avatar_url, ''), ca.avatar_url, '')::text                        AS avatar_url,
       ca.notes,
       ca.attended_at
FROM checkin_attendees ca
JOIN checkins c ON c.id = ca.checkin_id
LEFT JOIN users u ON u.id = ca.user_id
WHERE ca.checkin_id = $1
ORDER BY ca.attended_at ASC
LIMIT $3::int OFFSET $2::int
`

type ListCheckinAttendeesParams struct {
	CheckinID  uuid.UUID
	PageOffset int32
	PageSize   int32
}

type ListCheckinAttendeesRow struct {
	ID          uuid.UUID
	CheckinID   uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	AvatarUrl   string
	Notes       string
	AttendedAt  time.Time
}

func (q *Queries) ListCheckinAttendees(ctx context.Context, arg ListCheckinAttendeesParams) ([]ListCheckinAttendeesRow, error) {
	rows, err := q.db.Query(ctx, listCheckinAttendees, arg.CheckinID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinAttendeesRow{}
	for rows.Next() {
		var i ListCheckinAttendeesRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckinID,
			&i.UserID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Notes,
			&i.AttendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckins = `-- name: ListCheckins :many
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
       TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
       COALESCE(image_url, '') AS image_url,
       loot_list, attendance_count,
       (expire_time < NOW())::bool AS is_expired,
       (cancelled_at IS NOT NULL)::bool AS is_cancelled,
       created_at, updated_at
FROM checkins
WHERE guild_id = $1
  AND CASE
    WHEN $2::text = 'active'    THEN cancelled_at IS NULL AND expire_time >= NOW()
    WHEN $2::text = 'expired'   THEN cancelled_at IS NULL AND expire_time < NOW()
    WHEN $2::text = 'cancelled' THEN cancelled_at IS NOT NULL
    ELSE true
  END
ORDER BY datetime DESC
LIMIT $4::int OFFSET $3::int
`

type ListCheckinsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListCheckinsRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListCheckins(ctx context.Context, arg ListCheckinsParams) ([]ListCheckinsRow, error) {
	rows, err := q.db.Query(ctx, listCheckins,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinsRow{}
	for rows.Next() {
		var i ListCheckinsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Datetime,
			&i.ExpireTime,
			&i.ImageUrl,
			&i.LootList,
			&i.AttendanceCount,
			&i.IsExpired,
			&i.IsCancelled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logRetractedCheckinLoot = `-- name: LogRetractedCheckinLoot :exec
INSERT INTO item_events (guild_id, item_id, kind, actor_id, source, reference_id)
SELECT bi.guild_id, bi.id, 'retracted', $1::uuid, 'checkin', bi.checkin_id
FROM bank_items bi
WHERE bi.checkin_id = $2 AND bi.guild_id = $3 AND bi.locked_by_type IS NULL
`

type LogRetractedCheckinLootParams struct {
	ActorID   uuid.UUID
	CheckinID *uuid.UUID
	GuildID   uuid.UUID
}

func (q *Queries) LogRetractedCheckinLoot(ctx context.Context, arg LogRetractedCheckinLootParams) error {
	_, err := q.db.Exec(ctx, logRetractedCheckinLoot, arg.ActorID, arg.CheckinID, arg.GuildID)
	return err
}

const rejectPendingRequestsForCheckinLoot = `-- name: RejectPendingRequestsForCheckinLoot :execrows
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    review_note = NULLIF($2::text, ''),
    reviewed_at = NOW()
WHERE item_requests.guild_id = $3
  AND item_requests.status = 'pending'
  AND item_requests.bank_item_id IN (
      SELECT bi.id FROM bank_items bi
      WHERE bi.checkin_id = $4 AND bi.guild_id = $3
  )
`

type RejectPendingRequestsForCheckinLootParams struct {
	ReviewerID *uuid.UUID
	ReviewNote string
	GuildID    uuid.UUID
	CheckinID  *uuid.UUID
}

func (q *Queries) RejectPendingRequestsForCheckinLoot(ctx context.Context, arg RejectPendingRequestsForCheckinLootParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPendingRequestsForCheckinLoot,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.GuildID,
		arg.CheckinID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectPendingRequestsForLootItem = `-- name: RejectPendingRequestsForLootItem :execrows
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    review_note = NULLIF($2::text, ''),
    reviewed_at = NOW()
WHERE item_requests.guild_id = $3
  AND item_requests.bank_item_id = $4
  AND item_requests.status = 'pending'
`

type RejectPendingRequestsForLootItemParams struct {
	ReviewerID *uuid.UUID
	ReviewNote string
	GuildID    uuid.UUID
	BankItemID *uuid.UUID
}

func (q *Queries) RejectPendingRequestsForLootItem(ctx context.Context, arg RejectPendingRequestsForLootItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPendingRequestsForLootItem,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.GuildID,
		arg.BankItemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retractCheckinLoot = `-- name: RetractCheckinLoot :execrows
DELETE FROM bank_items
WHERE checkin_id = $1 AND guild_id = $2 AND locked_by_type IS NULL
`

type RetractCheckinLootParams struct {
	CheckinID *uuid.UUID
	GuildID   uuid.UUID
}

func (q *Queries) RetractCheckinLoot(ctx context.Context, arg RetractCheckinLootParams) (int64, error) {
	result, err := q.db.Exec(ctx, retractCheckinLoot, arg.CheckinID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeCheckinLootItem = `-- name: TakeCheckinLootItem :one
DELETE FROM bank_items
WHERE bank_items.id = $1 AND bank_items.guild_id = $2 AND bank_items.checkin_id = $3
  AND bank_items.locked_by_type IS NULL
RETURNING bank_items.item
`

type TakeCheckinLootItemParams struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	CheckinID *uuid.UUID
}

func (q *Queries) TakeCheckinLootItem(ctx context.Context, arg TakeCheckinLootItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, takeCheckinLootItem, arg.ID, arg.GuildID, arg.CheckinID)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const updateCheckin = `-- name: UpdateCheckin :one
UPDATE checkins SET
    title       = $1::text,
    description = CASE WHEN $2::bool THEN NULLIF($3::text, '') ELSE description END,
    datetime    = $4::text::timestamptz,
    expire_time = $5::text::timestamptz,
    image_url   = CASE WHEN $6::bool THEN NULLIF($7::text, '') ELSE image_url END,
    updated_at  = NOW()
WHERE id = $8 AND guild_id = $9
  AND cancelled_at IS NULL AND expire_time >= NOW()
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          created_at, updated_at
`

type UpdateCheckinParams struct {
	Title          string
	SetDescription bool
	Description    string
	Datetime       string
	ExpireTime     string
	SetImageUrl    bool
	ImageUrl       string
	ID             uuid.UUID
	GuildID        uuid.UUID
}

type UpdateCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateCheckin(ctx context.Context, arg UpdateCheckinParams) (UpdateCheckinRow, error) {
	row := q.db.QueryRow(ctx, updateCheckin,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.Datetime,
		arg.ExpireTime,
		arg.SetImageUrl,
		arg.ImageUrl,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
