// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkin.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkinExists = `-- name: CheckinExists :one
SELECT EXISTS(SELECT 1 FROM checkins WHERE id = $1 AND guild_id = $2)
`

type CheckinExistsParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) CheckinExists(ctx context.Context, arg CheckinExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkinExists, arg.ID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCheckinAttendees = `-- name: CountCheckinAttendees :one
SELECT COUNT(*) FROM checkin_attendees WHERE checkin_id = $1
`

func (q *Queries) CountCheckinAttendees(ctx context.Context, checkinID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckinAttendees, checkinID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCheckins = `-- name: CountCheckins :one
SELECT COUNT(*) FROM checkins WHERE guild_id = $1
  AND CASE
    WHEN $2::text = 'active'  THEN expire_time >= NOW()
    WHEN $2::text = 'expired' THEN expire_time < NOW()
    ELSE true
  END
`

type CountCheckinsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountCheckins(ctx context.Context, arg CountCheckinsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckins, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckin = `-- name: CreateCheckin :one
INSERT INTO checkins (guild_id, created_by, title, description, datetime, expire_time, image_url, loot_list)
VALUES (
    $1, $2, $3::text,
    NULLIF($4::text, ''),
    $5::text::timestamptz,
    $6::text::timestamptz,
    NULLIF($7::text, ''),
    $8::jsonb
)
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          created_at, updated_at
`

type CreateCheckinParams struct {
	GuildID     uuid.UUID
	CreatedBy   uuid.UUID
	Title       string
	Description string
	Datetime    string
	ExpireTime  string
	ImageUrl    string
	LootList    []byte
}

type CreateCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateCheckin(ctx context.Context, arg CreateCheckinParams) (CreateCheckinRow, error) {
	row := q.db.QueryRow(ctx, createCheckin,
		arg.GuildID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Datetime,
		arg.ExpireTime,
		arg.ImageUrl,
		arg.LootList,
	)
	var i CreateCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCheckin = `-- name: DeleteCheckin :execrows
DELETE FROM checkins WHERE id = $1 AND guild_id = $2
`

type DeleteCheckinParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteCheckin(ctx context.Context, arg DeleteCheckinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCheckin, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCheckin = `-- name: GetCheckin :one
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
       TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
       COALESCE(image_url, '') AS image_url,
       loot_list, attendance_count,
       (expire_time < NOW())::bool AS is_expired,
       created_at, updated_at
FROM checkins WHERE id = $1 AND guild_id = $2
`

type GetCheckinParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetCheckin(ctx context.Context, arg GetCheckinParams) (GetCheckinRow, error) {
	row := q.db.QueryRow(ctx, getCheckin, arg.ID, arg.GuildID)
	var i GetCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckinExpireTime = `-- name: GetCheckinExpireTime :one
SELECT expire_time FROM checkins WHERE id = $1 AND guild_id = $2
`

type GetCheckinExpireTimeParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) GetCheckinExpireTime(ctx context.Context, arg GetCheckinExpireTimeParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getCheckinExpireTime, arg.ID, arg.GuildID)
	var expire_time time.Time
	err := row.Scan(&expire_time)
	return expire_time, err
}

const getUserDisplayAndAvatar = `-- name: GetUserDisplayAndAvatar :one
SELECT COALESCE(display_name, '') AS display_name,
       COALESCE(avatar_url, '')   AS avatar_url
FROM users WHERE id = $1
`

type GetUserDisplayAndAvatarRow struct {
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) GetUserDisplayAndAvatar(ctx context.Context, id uuid.UUID) (GetUserDisplayAndAvatarRow, error) {
	row := q.db.QueryRow(ctx, getUserDisplayAndAvatar, id)
	var i GetUserDisplayAndAvatarRow
	err := row.Scan(&i.DisplayName, &i.AvatarUrl)
	return i, err
}

const incrementCheckinAttendance = `-- name: IncrementCheckinAttendance :exec
UPDATE checkins SET attendance_count = attendance_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementCheckinAttendance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCheckinAttendance, id)
	return err
}

const insertCheckinAttendee = `-- name: InsertCheckinAttendee :one
INSERT INTO checkin_attendees (checkin_id, user_id, display_name, avatar_url)
VALUES ($1, $2, $3::text, $4::text)
ON CONFLICT (checkin_id, user_id) DO NOTHING
RETURNING id
`

type InsertCheckinAttendeeParams struct {
	CheckinID   uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) InsertCheckinAttendee(ctx context.Context, arg InsertCheckinAttendeeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCheckinAttendee,
		arg.CheckinID,
		arg.UserID,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCheckinAttendees = `-- name: ListCheckinAttendees :many
SELECT id, checkin_id, user_id,
       COALESCE(display_name, '') AS display_name,
       COALESCE(avatar_url, '')   AS avatar_url,
       attended_at
FROM checkin_attendees WHERE checkin_id = $1
ORDER BY attended_at ASC
LIMIT $3::int OFFSET $2::int
`

type ListCheckinAttendeesParams struct {
	CheckinID  uuid.UUID
	PageOffset int32
	PageSize   int32
}

type ListCheckinAttendeesRow struct {
	ID          uuid.UUID
	CheckinID   uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	AvatarUrl   string
	AttendedAt  time.Time
}

func (q *Queries) ListCheckinAttendees(ctx context.Context, arg ListCheckinAttendeesParams) ([]ListCheckinAttendeesRow, error) {
	rows, err := q.db.Query(ctx, listCheckinAttendees, arg.CheckinID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinAttendeesRow{}
	for rows.Next() {
		var i ListCheckinAttendeesRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckinID,
			&i.UserID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.AttendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckins = `-- name: ListCheckins :many
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
       TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
       COALESCE(image_url, '') AS image_url,
       loot_list, attendance_count,
       (expire_time < NOW())::bool AS is_expired,
       created_at, updated_at
FROM checkins
WHERE guild_id = $1
  AND CASE
    WHEN $2::text = 'active'  THEN expire_time >= NOW()
    WHEN $2::text = 'expired' THEN expire_time < NOW()
    ELSE true
  END
ORDER BY datetime DESC
LIMIT $4::int OFFSET $3::int
`

type ListCheckinsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListCheckinsRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListCheckins(ctx context.Context, arg ListCheckinsParams) ([]ListCheckinsRow, error) {
	rows, err := q.db.Query(ctx, listCheckins,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinsRow{}
	for rows.Next() {
		var i ListCheckinsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Datetime,
			&i.ExpireTime,
			&i.ImageUrl,
			&i.LootList,
			&i.AttendanceCount,
			&i.IsExpired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckin = `-- name: UpdateCheckin :one
UPDATE checkins SET
    title       = CASE WHEN $1::text       != '' THEN $1::text       ELSE title END,
    description = CASE WHEN $2::text != '' THEN $2::text ELSE description END,
    datetime    = CASE WHEN $3::text    != '' THEN $3::text::timestamptz    ELSE datetime END,
    expire_time = CASE WHEN $4::text != '' THEN $4::text::timestamptz ELSE expire_time END,
    image_url   = CASE WHEN $5::text   != '' THEN $5::text   ELSE image_url END,
    loot_list   = $6::jsonb,
    updated_at  = NOW()
WHERE id = $7 AND guild_id = $8
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          created_at, updated_at
`

type UpdateCheckinParams struct {
	Title       string
	Description string
	Datetime    string
	ExpireTime  string
	ImageUrl    string
	LootList    []byte
	ID          uuid.UUID
	GuildID     uuid.UUID
}

type UpdateCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateCheckin(ctx context.Context, arg UpdateCheckinParams) (UpdateCheckinRow, error) {
	row := q.db.QueryRow(ctx, updateCheckin,
		arg.Title,
		arg.Description,
		arg.Datetime,
		arg.ExpireTime,
		arg.ImageUrl,
		arg.LootList,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
