// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkin.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCheckinGoldPotDistributed = `-- name: AddCheckinGoldPotDistributed :one
UPDATE checkin_gold_pots SET
    distributed = distributed + $1::bigint,
    updated_at  = NOW()
WHERE checkin_id = $2 AND guild_id = $3
  AND retracted = 0
  AND distributed + $1::bigint <= total
RETURNING checkin_id, guild_id, total, distributed, retracted
`

type AddCheckinGoldPotDistributedParams struct {
	Amount    int64
	CheckinID uuid.UUID
	GuildID   uuid.UUID
}

type AddCheckinGoldPotDistributedRow struct {
	CheckinID   uuid.UUID
	GuildID     uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) AddCheckinGoldPotDistributed(ctx context.Context, arg AddCheckinGoldPotDistributedParams) (AddCheckinGoldPotDistributedRow, error) {
	row := q.db.QueryRow(ctx, addCheckinGoldPotDistributed, arg.Amount, arg.CheckinID, arg.GuildID)
	var i AddCheckinGoldPotDistributedRow
	err := row.Scan(
		&i.CheckinID,
		&i.GuildID,
		&i.Total,
		&i.Distributed,
		&i.Retracted,
	)
	return i, err
}

const cancelCheckin = `-- name: CancelCheckin :one
UPDATE checkins SET cancelled_at = NOW(), updated_at = NOW()
WHERE id = $1 AND guild_id = $2 AND cancelled_at IS NULL AND expire_time >= NOW()
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          created_at, updated_at
`

type CancelCheckinParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type CancelCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CancelCheckin(ctx context.Context, arg CancelCheckinParams) (CancelCheckinRow, error) {
	row := q.db.QueryRow(ctx, cancelCheckin, arg.ID, arg.GuildID)
	var i CancelCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkinExists = `-- name: CheckinExists :one
SELECT EXISTS(SELECT 1 FROM checkins WHERE id = $1 AND guild_id = $2)
`

type CheckinExistsParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) CheckinExists(ctx context.Context, arg CheckinExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkinExists, arg.ID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCheckinAttendees = `-- name: CountCheckinAttendees :one
SELECT COUNT(*) FROM checkin_attendees WHERE checkin_id = $1
`

func (q *Queries) CountCheckinAttendees(ctx context.Context, checkinID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckinAttendees, checkinID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCheckinAttendeesAmong = `-- name: CountCheckinAttendeesAmong :one
SELECT COUNT(*) FROM checkin_attendees
WHERE checkin_id = $1 AND user_id = ANY($2::uuid[])
`

type CountCheckinAttendeesAmongParams struct {
	CheckinID uuid.UUID
	UserIds   []uuid.UUID
}

func (q *Queries) CountCheckinAttendeesAmong(ctx context.Context, arg CountCheckinAttendeesAmongParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckinAttendeesAmong, arg.CheckinID, arg.UserIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCheckins = `-- name: CountCheckins :one
SELECT COUNT(*) FROM checkins WHERE guild_id = $1
  AND CASE
    WHEN $2::text = 'active'    THEN cancelled_at IS NULL AND expire_time >= NOW()
    WHEN $2::text = 'expired'   THEN cancelled_at IS NULL AND expire_time < NOW()
    WHEN $2::text = 'cancelled' THEN cancelled_at IS NOT NULL
    ELSE true
  END
`

type CountCheckinsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountCheckins(ctx context.Context, arg CountCheckinsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckins, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckin = `-- name: CreateCheckin :one
INSERT INTO checkins (guild_id, created_by, title, description, datetime, expire_time, image_url, loot_list)
VALUES (
    $1, $2, $3::text,
    NULLIF($4::text, ''),
    $5::text::timestamptz,
    $6::text::timestamptz,
    NULLIF($7::text, ''),
    $8::jsonb
)
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          created_at, updated_at
`

type CreateCheckinParams struct {
	GuildID     uuid.UUID
	CreatedBy   uuid.UUID
	Title       string
	Description string
	Datetime    string
	ExpireTime  string
	ImageUrl    string
	LootList    []byte
}

type CreateCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateCheckin(ctx context.Context, arg CreateCheckinParams) (CreateCheckinRow, error) {
	row := q.db.QueryRow(ctx, createCheckin,
		arg.GuildID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Datetime,
		arg.ExpireTime,
		arg.ImageUrl,
		arg.LootList,
	)
	var i CreateCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCheckin = `-- name: DeleteCheckin :execrows
DELETE FROM checkins WHERE id = $1 AND guild_id = $2
`

type DeleteCheckinParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteCheckin(ctx context.Context, arg DeleteCheckinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCheckin, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCheckin = `-- name: GetCheckin :one
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
       TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
       COALESCE(image_url, '') AS image_url,
       loot_list, attendance_count,
       (expire_time < NOW())::bool AS is_expired,
       (cancelled_at IS NOT NULL)::bool AS is_cancelled,
       created_at, updated_at
FROM checkins WHERE id = $1 AND guild_id = $2
`

type GetCheckinParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetCheckin(ctx context.Context, arg GetCheckinParams) (GetCheckinRow, error) {
	row := q.db.QueryRow(ctx, getCheckin, arg.ID, arg.GuildID)
	var i GetCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckinAttendanceWindow = `-- name: GetCheckinAttendanceWindow :one
SELECT expire_time, (cancelled_at IS NOT NULL)::bool AS is_cancelled
FROM checkins WHERE id = $1 AND guild_id = $2
`

type GetCheckinAttendanceWindowParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetCheckinAttendanceWindowRow struct {
	ExpireTime  time.Time
	IsCancelled bool
}

func (q *Queries) GetCheckinAttendanceWindow(ctx context.Context, arg GetCheckinAttendanceWindowParams) (GetCheckinAttendanceWindowRow, error) {
	row := q.db.QueryRow(ctx, getCheckinAttendanceWindow, arg.ID, arg.GuildID)
	var i GetCheckinAttendanceWindowRow
	err := row.Scan(&i.ExpireTime, &i.IsCancelled)
	return i, err
}

const getCheckinGoldDistributionByRequest = `-- name: GetCheckinGoldDistributionByRequest :one
SELECT id, total, created_at
FROM checkin_gold_distributions
WHERE checkin_id = $1 AND request_id = $2
`

type GetCheckinGoldDistributionByRequestParams struct {
	CheckinID uuid.UUID
	RequestID uuid.UUID
}

type GetCheckinGoldDistributionByRequestRow struct {
	ID        uuid.UUID
	Total     int64
	CreatedAt time.Time
}

func (q *Queries) GetCheckinGoldDistributionByRequest(ctx context.Context, arg GetCheckinGoldDistributionByRequestParams) (GetCheckinGoldDistributionByRequestRow, error) {
	row := q.db.QueryRow(ctx, getCheckinGoldDistributionByRequest, arg.CheckinID, arg.RequestID)
	var i GetCheckinGoldDistributionByRequestRow
	err := row.Scan(&i.ID, &i.Total, &i.CreatedAt)
	return i, err
}

const getCheckinGoldPot = `-- name: GetCheckinGoldPot :one
SELECT checkin_id, guild_id, total, distributed, retracted
FROM checkin_gold_pots
WHERE checkin_id = $1 AND guild_id = $2
`

type GetCheckinGoldPotParams struct {
	CheckinID uuid.UUID
	GuildID   uuid.UUID
}

type GetCheckinGoldPotRow struct {
	CheckinID   uuid.UUID
	GuildID     uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) GetCheckinGoldPot(ctx context.Context, arg GetCheckinGoldPotParams) (GetCheckinGoldPotRow, error) {
	row := q.db.QueryRow(ctx, getCheckinGoldPot, arg.CheckinID, arg.GuildID)
	var i GetCheckinGoldPotRow
	err := row.Scan(
		&i.CheckinID,
		&i.GuildID,
		&i.Total,
		&i.Distributed,
		&i.Retracted,
	)
	return i, err
}

const getUserDisplayAndAvatar = `-- name: GetUserDisplayAndAvatar :one
SELECT COALESCE(display_name, '') AS display_name,
       COALESCE(avatar_url, '')   AS avatar_url
FROM users WHERE id = $1
`

type GetUserDisplayAndAvatarRow struct {
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) GetUserDisplayAndAvatar(ctx context.Context, id uuid.UUID) (GetUserDisplayAndAvatarRow, error) {
	row := q.db.QueryRow(ctx, getUserDisplayAndAvatar, id)
	var i GetUserDisplayAndAvatarRow
	err := row.Scan(&i.DisplayName, &i.AvatarUrl)
	return i, err
}

const incrementCheckinAttendance = `-- name: IncrementCheckinAttendance :exec
UPDATE checkins SET attendance_count = attendance_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementCheckinAttendance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCheckinAttendance, id)
	return err
}

const insertCheckinAttendee = `-- name: InsertCheckinAttendee :one
INSERT INTO checkin_attendees (checkin_id, user_id, display_name, avatar_url, notes)
VALUES ($1, $2, $3::text, $4::text, $5::text)
ON CONFLICT (checkin_id, user_id) DO NOTHING
RETURNING id
`

type InsertCheckinAttendeeParams struct {
	CheckinID   uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	AvatarUrl   string
	Notes       string
}

func (q *Queries) InsertCheckinAttendee(ctx context.Context, arg InsertCheckinAttendeeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCheckinAttendee,
		arg.CheckinID,
		arg.UserID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Notes,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertCheckinBankItem = `-- name: InsertCheckinBankItem :exec
INSERT INTO bank_items (id, guild_id, donor_id, donor_name, item, checkin_id)
VALUES ($1, $2, $3, $4::text, $5::jsonb, $6::uuid)
`

type InsertCheckinBankItemParams struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	DonorID   uuid.UUID
	DonorName string
	Item      []byte
	CheckinID uuid.UUID
}

func (q *Queries) InsertCheckinBankItem(ctx context.Context, arg InsertCheckinBankItemParams) error {
	_, err := q.db.Exec(ctx, insertCheckinBankItem,
		arg.ID,
		arg.GuildID,
		arg.DonorID,
		arg.DonorName,
		arg.Item,
		arg.CheckinID,
	)
	return err
}

const insertCheckinGoldBankActivity = `-- name: InsertCheckinGoldBankActivity :exec
INSERT INTO bank_contributions (guild_id, user_id, username, amount, note, kind, checkin_id, reference_type, reference_id)
VALUES ($1, $2, $3::text, $4::bigint,
        NULLIF($5::text, ''), $6::text, $7::uuid,
        NULLIF($8::text, ''), $9::uuid)
`

type InsertCheckinGoldBankActivityParams struct {
	GuildID       uuid.UUID
	UserID        uuid.UUID
	Username      string
	Amount        int64
	Note          string
	Kind          string
	CheckinID     uuid.UUID
	ReferenceType string
	ReferenceID   *uuid.UUID
}

func (q *Queries) InsertCheckinGoldBankActivity(ctx context.Context, arg InsertCheckinGoldBankActivityParams) error {
	_, err := q.db.Exec(ctx, insertCheckinGoldBankActivity,
		arg.GuildID,
		arg.UserID,
		arg.Username,
		arg.Amount,
		arg.Note,
		arg.Kind,
		arg.CheckinID,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	return err
}

const insertCheckinGoldDistribution = `-- name: InsertCheckinGoldDistribution :one
INSERT INTO checkin_gold_distributions (checkin_id, guild_id, actor_id, request_id, total)
VALUES ($1, $2, $3, $4, $5::bigint)
RETURNING id, created_at
`

type InsertCheckinGoldDistributionParams struct {
	CheckinID uuid.UUID
	GuildID   uuid.UUID
	ActorID   *uuid.UUID
	RequestID uuid.UUID
	Total     int64
}

type InsertCheckinGoldDistributionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertCheckinGoldDistribution(ctx context.Context, arg InsertCheckinGoldDistributionParams) (InsertCheckinGoldDistributionRow, error) {
	row := q.db.QueryRow(ctx, insertCheckinGoldDistribution,
		arg.CheckinID,
		arg.GuildID,
		arg.ActorID,
		arg.RequestID,
		arg.Total,
	)
	var i InsertCheckinGoldDistributionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertCheckinGoldPayout = `-- name: InsertCheckinGoldPayout :exec
INSERT INTO checkin_gold_payouts (distribution_id, user_id, amount, transaction_id)
VALUES ($1, $2, $3::bigint, $4)
`

type InsertCheckinGoldPayoutParams struct {
	DistributionID uuid.UUID
	UserID         uuid.UUID
	Amount         int64
	TransactionID  *uuid.UUID
}

func (q *Queries) InsertCheckinGoldPayout(ctx context.Context, arg InsertCheckinGoldPayoutParams) error {
	_, err := q.db.Exec(ctx, insertCheckinGoldPayout,
		arg.DistributionID,
		arg.UserID,
		arg.Amount,
		arg.TransactionID,
	)
	return err
}

const insertCheckinGoldPot = `-- name: InsertCheckinGoldPot :exec
INSERT INTO checkin_gold_pots (checkin_id, guild_id, total)
VALUES ($1, $2, $3::bigint)
`

type InsertCheckinGoldPotParams struct {
	CheckinID uuid.UUID
	GuildID   uuid.UUID
	Total     int64
}

func (q *Queries) InsertCheckinGoldPot(ctx context.Context, arg InsertCheckinGoldPotParams) error {
	_, err := q.db.Exec(ctx, insertCheckinGoldPot, arg.CheckinID, arg.GuildID, arg.Total)
	return err
}

const insertCheckinLootContribution = `-- name: InsertCheckinLootContribution :exec
INSERT INTO bank_contributions (guild_id, user_id, username, amount, note, kind, items, checkin_id)
VALUES ($1, $2, $3::text, $4::bigint, NULLIF($5::text, ''), 'checkin_loot',
        $6::jsonb, $7::uuid)
`

type InsertCheckinLootContributionParams struct {
	GuildID   uuid.UUID
	UserID    uuid.UUID
	Username  string
	Amount    int64
	Note      string
	Items     []byte
	CheckinID uuid.UUID
}

func (q *Queries) InsertCheckinLootContribution(ctx context.Context, arg InsertCheckinLootContributionParams) error {
	_, err := q.db.Exec(ctx, insertCheckinLootContribution,
		arg.GuildID,
		arg.UserID,
		arg.Username,
		arg.Amount,
		arg.Note,
		arg.Items,
		arg.CheckinID,
	)
	return err
}

const isCheckinAttendee = `-- name: IsCheckinAttendee :one
SELECT EXISTS(SELECT 1 FROM checkin_attendees WHERE checkin_id = $1 AND user_id = $2)
`

type IsCheckinAttendeeParams struct {
	CheckinID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) IsCheckinAttendee(ctx context.Context, arg IsCheckinAttendeeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCheckinAttendee, arg.CheckinID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCheckinAttendees = `-- name: ListCheckinAttendees :many
SELECT id, checkin_id, user_id,
       COALESCE(display_name, '') AS display_name,
       COALESCE(avatar_url, '')   AS avatar_url,
       notes,
       attended_at
FROM checkin_attendees WHERE checkin_id = $1
ORDER BY attended_at ASC
LIMIT $3::int OFFSET $2::int
`

type ListCheckinAttendeesParams struct {
	CheckinID  uuid.UUID
	PageOffset int32
	PageSize   int32
}

type ListCheckinAttendeesRow struct {
	ID          uuid.UUID
	CheckinID   uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	AvatarUrl   string
	Notes       string
	AttendedAt  time.Time
}

func (q *Queries) ListCheckinAttendees(ctx context.Context, arg ListCheckinAttendeesParams) ([]ListCheckinAttendeesRow, error) {
	rows, err := q.db.Query(ctx, listCheckinAttendees, arg.CheckinID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinAttendeesRow{}
	for rows.Next() {
		var i ListCheckinAttendeesRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckinID,
			&i.UserID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Notes,
			&i.AttendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckinGoldDistributionPayouts = `-- name: ListCheckinGoldDistributionPayouts :many
SELECT user_id, amount
FROM checkin_gold_payouts
WHERE distribution_id = $1
ORDER BY user_id
`

type ListCheckinGoldDistributionPayoutsRow struct {
	UserID uuid.UUID
	Amount int64
}

func (q *Queries) ListCheckinGoldDistributionPayouts(ctx context.Context, distributionID uuid.UUID) ([]ListCheckinGoldDistributionPayoutsRow, error) {
	rows, err := q.db.Query(ctx, listCheckinGoldDistributionPayouts, distributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinGoldDistributionPayoutsRow{}
	for rows.Next() {
		var i ListCheckinGoldDistributionPayoutsRow
		if err := rows.Scan(&i.UserID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckinGoldPots = `-- name: ListCheckinGoldPots :many
SELECT checkin_id, total, distributed, retracted
FROM checkin_gold_pots
WHERE guild_id = $1 AND checkin_id = ANY($2::uuid[])
`

type ListCheckinGoldPotsParams struct {
	GuildID    uuid.UUID
	CheckinIds []uuid.UUID
}

type ListCheckinGoldPotsRow struct {
	CheckinID   uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) ListCheckinGoldPots(ctx context.Context, arg ListCheckinGoldPotsParams) ([]ListCheckinGoldPotsRow, error) {
	rows, err := q.db.Query(ctx, listCheckinGoldPots, arg.GuildID, arg.CheckinIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinGoldPotsRow{}
	for rows.Next() {
		var i ListCheckinGoldPotsRow
		if err := rows.Scan(
			&i.CheckinID,
			&i.Total,
			&i.Distributed,
			&i.Retracted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckinGoldRecipients = `-- name: ListCheckinGoldRecipients :many
SELECT p.user_id, SUM(p.amount)::bigint AS amount
FROM checkin_gold_payouts p
JOIN checkin_gold_distributions d ON d.id = p.distribution_id
WHERE d.checkin_id = $1 AND d.guild_id = $2
GROUP BY p.user_id
ORDER BY p.user_id
`

type ListCheckinGoldRecipientsParams struct {
	CheckinID uuid.UUID
	GuildID   uuid.UUID
}

type ListCheckinGoldRecipientsRow struct {
	UserID uuid.UUID
	Amount int64
}

func (q *Queries) ListCheckinGoldRecipients(ctx context.Context, arg ListCheckinGoldRecipientsParams) ([]ListCheckinGoldRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listCheckinGoldRecipients, arg.CheckinID, arg.GuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinGoldRecipientsRow{}
	for rows.Next() {
		var i ListCheckinGoldRecipientsRow
		if err := rows.Scan(&i.UserID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckins = `-- name: ListCheckins :many
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
       TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
       COALESCE(image_url, '') AS image_url,
       loot_list, attendance_count,
       (expire_time < NOW())::bool AS is_expired,
       (cancelled_at IS NOT NULL)::bool AS is_cancelled,
       created_at, updated_at
FROM checkins
WHERE guild_id = $1
  AND CASE
    WHEN $2::text = 'active'    THEN cancelled_at IS NULL AND expire_time >= NOW()
    WHEN $2::text = 'expired'   THEN cancelled_at IS NULL AND expire_time < NOW()
    WHEN $2::text = 'cancelled' THEN cancelled_at IS NOT NULL
    ELSE true
  END
ORDER BY datetime DESC
LIMIT $4::int OFFSET $3::int
`

type ListCheckinsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListCheckinsRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListCheckins(ctx context.Context, arg ListCheckinsParams) ([]ListCheckinsRow, error) {
	rows, err := q.db.Query(ctx, listCheckins,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckinsRow{}
	for rows.Next() {
		var i ListCheckinsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Datetime,
			&i.ExpireTime,
			&i.ImageUrl,
			&i.LootList,
			&i.AttendanceCount,
			&i.IsExpired,
			&i.IsCancelled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCheckinGoldPot = `-- name: LockCheckinGoldPot :one
SELECT checkin_id, guild_id, total, distributed, retracted
FROM checkin_gold_pots
WHERE checkin_id = $1 AND guild_id = $2
FOR UPDATE
`

type LockCheckinGoldPotParams struct {
	CheckinID uuid.UUID
	GuildID   uuid.UUID
}

type LockCheckinGoldPotRow struct {
	CheckinID   uuid.UUID
	GuildID     uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) LockCheckinGoldPot(ctx context.Context, arg LockCheckinGoldPotParams) (LockCheckinGoldPotRow, error) {
	row := q.db.QueryRow(ctx, lockCheckinGoldPot, arg.CheckinID, arg.GuildID)
	var i LockCheckinGoldPotRow
	err := row.Scan(
		&i.CheckinID,
		&i.GuildID,
		&i.Total,
		&i.Distributed,
		&i.Retracted,
	)
	return i, err
}

const logRetractedCheckinLoot = `-- name: LogRetractedCheckinLoot :exec
INSERT INTO item_events (guild_id, item_id, kind, actor_id, source, reference_id)
SELECT bi.guild_id, bi.id, 'retracted', $1::uuid, 'checkin', bi.checkin_id
FROM bank_items bi
WHERE bi.checkin_id = $2 AND bi.guild_id = $3 AND bi.locked_by_type IS NULL
`

type LogRetractedCheckinLootParams struct {
	ActorID   uuid.UUID
	CheckinID *uuid.UUID
	GuildID   uuid.UUID
}

func (q *Queries) LogRetractedCheckinLoot(ctx context.Context, arg LogRetractedCheckinLootParams) error {
	_, err := q.db.Exec(ctx, logRetractedCheckinLoot, arg.ActorID, arg.CheckinID, arg.GuildID)
	return err
}

const rejectPendingRequestsForCheckinLoot = `-- name: RejectPendingRequestsForCheckinLoot :execrows
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    review_note = NULLIF($2::text, ''),
    reviewed_at = NOW()
WHERE item_requests.guild_id = $3
  AND item_requests.status = 'pending'
  AND item_requests.bank_item_id IN (
      SELECT bi.id FROM bank_items bi
      WHERE bi.checkin_id = $4 AND bi.guild_id = $3
  )
`

type RejectPendingRequestsForCheckinLootParams struct {
	ReviewerID *uuid.UUID
	ReviewNote string
	GuildID    uuid.UUID
	CheckinID  *uuid.UUID
}

func (q *Queries) RejectPendingRequestsForCheckinLoot(ctx context.Context, arg RejectPendingRequestsForCheckinLootParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPendingRequestsForCheckinLoot,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.GuildID,
		arg.CheckinID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectPendingRequestsForLootItem = `-- name: RejectPendingRequestsForLootItem :execrows
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    review_note = NULLIF($2::text, ''),
    reviewed_at = NOW()
WHERE item_requests.guild_id = $3
  AND item_requests.bank_item_id = $4
  AND item_requests.status = 'pending'
`

type RejectPendingRequestsForLootItemParams struct {
	ReviewerID *uuid.UUID
	ReviewNote string
	GuildID    uuid.UUID
	BankItemID *uuid.UUID
}

func (q *Queries) RejectPendingRequestsForLootItem(ctx context.Context, arg RejectPendingRequestsForLootItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPendingRequestsForLootItem,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.GuildID,
		arg.BankItemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retractCheckinGoldPot = `-- name: RetractCheckinGoldPot :one
UPDATE checkin_gold_pots SET
    retracted  = total - distributed,
    updated_at = NOW()
WHERE checkin_id = $1 AND guild_id = $2 AND retracted = 0 AND distributed < total
RETURNING checkin_id, guild_id, total, distributed, retracted
`

type RetractCheckinGoldPotParams struct {
	CheckinID uuid.UUID
	GuildID   uuid.UUID
}

type RetractCheckinGoldPotRow struct {
	CheckinID   uuid.UUID
	GuildID     uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) RetractCheckinGoldPot(ctx context.Context, arg RetractCheckinGoldPotParams) (RetractCheckinGoldPotRow, error) {
	row := q.db.QueryRow(ctx, retractCheckinGoldPot, arg.CheckinID, arg.GuildID)
	var i RetractCheckinGoldPotRow
	err := row.Scan(
		&i.CheckinID,
		&i.GuildID,
		&i.Total,
		&i.Distributed,
		&i.Retracted,
	)
	return i, err
}

const retractCheckinLoot = `-- name: RetractCheckinLoot :execrows
DELETE FROM bank_items
WHERE checkin_id = $1 AND guild_id = $2 AND locked_by_type IS NULL
`

type RetractCheckinLootParams struct {
	CheckinID *uuid.UUID
	GuildID   uuid.UUID
}

func (q *Queries) RetractCheckinLoot(ctx context.Context, arg RetractCheckinLootParams) (int64, error) {
	result, err := q.db.Exec(ctx, retractCheckinLoot, arg.CheckinID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeCheckinLootItem = `-- name: TakeCheckinLootItem :one
DELETE FROM bank_items
WHERE bank_items.id = $1 AND bank_items.guild_id = $2 AND bank_items.checkin_id = $3
  AND bank_items.locked_by_type IS NULL
RETURNING bank_items.item
`

type TakeCheckinLootItemParams struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	CheckinID *uuid.UUID
}

func (q *Queries) TakeCheckinLootItem(ctx context.Context, arg TakeCheckinLootItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, takeCheckinLootItem, arg.ID, arg.GuildID, arg.CheckinID)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const updateCheckin = `-- name: UpdateCheckin :one
UPDATE checkins SET
    title       = $1::text,
    description = CASE WHEN $2::bool THEN NULLIF($3::text, '') ELSE description END,
    datetime    = $4::text::timestamptz,
    expire_time = $5::text::timestamptz,
    image_url   = CASE WHEN $6::bool THEN NULLIF($7::text, '') ELSE image_url END,
    updated_at  = NOW()
WHERE id = $8 AND guild_id = $9
  AND cancelled_at IS NULL AND expire_time >= NOW()
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          created_at, updated_at
`

type UpdateCheckinParams struct {
	Title          string
	SetDescription bool
	Description    string
	Datetime       string
	ExpireTime     string
	SetImageUrl    bool
	ImageUrl       string
	ID             uuid.UUID
	GuildID        uuid.UUID
}

type UpdateCheckinRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateCheckin(ctx context.Context, arg UpdateCheckinParams) (UpdateCheckinRow, error) {
	row := q.db.QueryRow(ctx, updateCheckin,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.Datetime,
		arg.ExpireTime,
		arg.SetImageUrl,
		arg.ImageUrl,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateCheckinRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
