// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM guild_events WHERE guild_id = $1
`

func (q *Queries) CountEvents(ctx context.Context, guildID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO guild_events (
    guild_id, created_by, title, description, type,
    start_date, end_date, is_all_day, location, priority,
    is_recurring, recurring_pattern
) VALUES (
    $1, $2, $3::text,
    NULLIF($4::text, ''),
    $5::text,
    $6::text::timestamptz,
    $7::text::timestamptz,
    $8::bool,
    NULLIF($9::text, ''),
    $10::text,
    $11::bool,
    $12::jsonb
)
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          type,
          TO_CHAR(start_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS start_date,
          TO_CHAR(end_date   AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS end_date,
          is_all_day,
          COALESCE(location, '') AS location,
          priority,
          is_recurring, recurring_pattern,
          participant_ids,
          created_at, updated_at
`

type CreateEventParams struct {
	GuildID          uuid.UUID
	CreatedBy        uuid.UUID
	Title            string
	Description      string
	Type             string
	StartDate        string
	EndDate          string
	IsAllDay         bool
	Location         string
	Priority         string
	IsRecurring      bool
	RecurringPattern []byte
}

type CreateEventRow struct {
	ID               uuid.UUID
	GuildID          uuid.UUID
	CreatedBy        uuid.UUID
	Title            string
	Description      string
	Type             string
	StartDate        string
	EndDate          string
	IsAllDay         bool
	Location         string
	Priority         string
	IsRecurring      bool
	RecurringPattern []byte
	ParticipantIds   []uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.GuildID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.StartDate,
		arg.EndDate,
		arg.IsAllDay,
		arg.Location,
		arg.Priority,
		arg.IsRecurring,
		arg.RecurringPattern,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.IsAllDay,
		&i.Location,
		&i.Priority,
		&i.IsRecurring,
		&i.RecurringPattern,
		&i.ParticipantIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM guild_events WHERE id = $1 AND guild_id = $2
`

type DeleteEventParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       type,
       TO_CHAR(start_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS start_date,
       TO_CHAR(end_date   AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS end_date,
       is_all_day,
       COALESCE(location, '') AS location,
       priority,
       is_recurring, recurring_pattern,
       participant_ids,
       created_at, updated_at
FROM guild_events WHERE id = $1 AND guild_id = $2
`

type GetEventParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetEventRow struct {
	ID               uuid.UUID
	GuildID          uuid.UUID
	CreatedBy        uuid.UUID
	Title            string
	Description      string
	Type             string
	StartDate        string
	EndDate          string
	IsAllDay         bool
	Location         string
	Priority         string
	IsRecurring      bool
	RecurringPattern []byte
	ParticipantIds   []uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (GetEventRow, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.ID, arg.GuildID)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.IsAllDay,
		&i.Location,
		&i.Priority,
		&i.IsRecurring,
		&i.RecurringPattern,
		&i.ParticipantIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       type,
       TO_CHAR(start_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS start_date,
       TO_CHAR(end_date   AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS end_date,
       is_all_day,
       COALESCE(location, '') AS location,
       priority,
       is_recurring, recurring_pattern,
       participant_ids,
       created_at, updated_at
FROM guild_events
WHERE guild_id = $1
ORDER BY start_date ASC
LIMIT $3::int OFFSET $2::int
`

type ListEventsParams struct {
	GuildID    uuid.UUID
	PageOffset int32
	PageSize   int32
}

type ListEventsRow struct {
	ID               uuid.UUID
	GuildID          uuid.UUID
	CreatedBy        uuid.UUID
	Title            string
	Description      string
	Type             string
	StartDate        string
	EndDate          string
	IsAllDay         bool
	Location         string
	Priority         string
	IsRecurring      bool
	RecurringPattern []byte
	ParticipantIds   []uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.GuildID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.StartDate,
			&i.EndDate,
			&i.IsAllDay,
			&i.Location,
			&i.Priority,
			&i.IsRecurring,
			&i.RecurringPattern,
			&i.ParticipantIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByRange = `-- name: ListEventsByRange :many
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       type,
       TO_CHAR(start_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS start_date,
       TO_CHAR(end_date   AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS end_date,
       is_all_day,
       COALESCE(location, '') AS location,
       priority,
       is_recurring, recurring_pattern,
       participant_ids,
       created_at, updated_at
FROM guild_events
WHERE guild_id = $1
  AND start_date >= $2::text::timestamptz
  AND end_date   <= $3::text::timestamptz
ORDER BY start_date ASC
`

type ListEventsByRangeParams struct {
	GuildID   uuid.UUID
	StartDate string
	EndDate   string
}

type ListEventsByRangeRow struct {
	ID               uuid.UUID
	GuildID          uuid.UUID
	CreatedBy        uuid.UUID
	Title            string
	Description      string
	Type             string
	StartDate        string
	EndDate          string
	IsAllDay         bool
	Location         string
	Priority         string
	IsRecurring      bool
	RecurringPattern []byte
	ParticipantIds   []uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListEventsByRange(ctx context.Context, arg ListEventsByRangeParams) ([]ListEventsByRangeRow, error) {
	rows, err := q.db.Query(ctx, listEventsByRange, arg.GuildID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByRangeRow{}
	for rows.Next() {
		var i ListEventsByRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.StartDate,
			&i.EndDate,
			&i.IsAllDay,
			&i.Location,
			&i.Priority,
			&i.IsRecurring,
			&i.RecurringPattern,
			&i.ParticipantIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       type,
       TO_CHAR(start_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS start_date,
       TO_CHAR(end_date   AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS end_date,
       is_all_day,
       COALESCE(location, '') AS location,
       priority,
       is_recurring, recurring_pattern,
       participant_ids,
       created_at, updated_at
FROM guild_events
WHERE guild_id = $1 AND start_date > NOW()
ORDER BY start_date ASC
LIMIT $2::int
`

type ListUpcomingEventsParams struct {
	GuildID uuid.UUID
	Lim     int32
}

type ListUpcomingEventsRow struct {
	ID               uuid.UUID
	GuildID          uuid.UUID
	CreatedBy        uuid.UUID
	Title            string
	Description      string
	Type             string
	StartDate        string
	EndDate          string
	IsAllDay         bool
	Location         string
	Priority         string
	IsRecurring      bool
	RecurringPattern []byte
	ParticipantIds   []uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]ListUpcomingEventsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingEvents, arg.GuildID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingEventsRow{}
	for rows.Next() {
		var i ListUpcomingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.StartDate,
			&i.EndDate,
			&i.IsAllDay,
			&i.Location,
			&i.Priority,
			&i.IsRecurring,
			&i.RecurringPattern,
			&i.ParticipantIds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE guild_events SET
    title             = CASE WHEN $1::text       != '' THEN $1::text       ELSE title END,
    description       = CASE WHEN $2::text != '' THEN $2::text ELSE description END,
    type              = CASE WHEN $3::text        != '' THEN $3::text        ELSE type END,
    start_date        = CASE WHEN $4::text  != '' THEN $4::text::timestamptz ELSE start_date END,
    end_date          = CASE WHEN $5::text    != '' THEN $5::text::timestamptz   ELSE end_date END,
    is_all_day        = $6::bool,
    location          = CASE WHEN $7::text    != '' THEN $7::text    ELSE location END,
    priority          = CASE WHEN $8::text    != '' THEN $8::text    ELSE priority END,
    is_recurring      = $9::bool,
    recurring_pattern = CASE WHEN $10::jsonb IS NOT NULL THEN $10::jsonb ELSE recurring_pattern END,
    updated_at        = NOW()
WHERE id = $11 AND guild_id = $12
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          type,
          TO_CHAR(start_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS start_date,
          TO_CHAR(end_date   AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS end_date,
          is_all_day,
          COALESCE(location, '') AS location,
          priority,
          is_recurring, recurring_pattern,
          participant_ids,
          created_at, updated_at
`

type UpdateEventParams struct {
	Title            string
	Description      string
	Type             string
	StartDate        string
	EndDate          string
	IsAllDay         bool
	Location         string
	Priority         string
	IsRecurring      bool
	RecurringPattern []byte
	ID               uuid.UUID
	GuildID          uuid.UUID
}

type UpdateEventRow struct {
	ID               uuid.UUID
	GuildID          uuid.UUID
	CreatedBy        uuid.UUID
	Title            string
	Description      string
	Type             string
	StartDate        string
	EndDate          string
	IsAllDay         bool
	Location         string
	Priority         string
	IsRecurring      bool
	RecurringPattern []byte
	ParticipantIds   []uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.StartDate,
		arg.EndDate,
		arg.IsAllDay,
		arg.Location,
		arg.Priority,
		arg.IsRecurring,
		arg.RecurringPattern,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateEventRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.IsAllDay,
		&i.Location,
		&i.Priority,
		&i.IsRecurring,
		&i.RecurringPattern,
		&i.ParticipantIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
