// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countGuildMembers = `-- name: CountGuildMembers :one
SELECT COUNT(*) FROM members WHERE guild_id = $1
`

func (q *Queries) CountGuildMembers(ctx context.Context, guildID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGuildMembers, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuildMembersByRole = `-- name: CountGuildMembersByRole :one
SELECT COUNT(*) FROM members
WHERE guild_id = $1
  AND ($2::text = '' OR role = $2::text)
`

type CountGuildMembersByRoleParams struct {
	GuildID    uuid.UUID
	RoleFilter string
}

func (q *Queries) CountGuildMembersByRole(ctx context.Context, arg CountGuildMembersByRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGuildMembersByRole, arg.GuildID, arg.RoleFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuilds = `-- name: CountGuilds :one
SELECT COUNT(*) FROM guilds
WHERE ($1::text = '%%' OR name ILIKE $1::text OR description ILIKE $1::text)
`

func (q *Queries) CountGuilds(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countGuilds, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuild = `-- name: CreateGuild :one
INSERT INTO guilds (
    name, description, owner_id,
    timezone, language, public, allow_invites, custom_settings,
    icon_url, banner_url
) VALUES (
    $1::text,
    NULLIF($2::text, ''),
    $3,
    'UTC', 'en', false, true,
    $4::jsonb,
    NULLIF($5::text, ''),
    NULLIF($6::text, '')
)
RETURNING id, name,
          COALESCE(description, '') AS description,
          owner_id,
          timezone, language, public, allow_invites,
          custom_settings,
          COALESCE(icon_url, '')   AS icon_url,
          COALESCE(banner_url, '') AS banner_url,
          created_at, updated_at
`

type CreateGuildParams struct {
	Name           string
	Description    string
	OwnerID        uuid.UUID
	CustomSettings []byte
	IconUrl        string
	BannerUrl      string
}

type CreateGuildRow struct {
	ID             uuid.UUID
	Name           string
	Description    string
	OwnerID        uuid.UUID
	Timezone       string
	Language       string
	Public         bool
	AllowInvites   bool
	CustomSettings []byte
	IconUrl        string
	BannerUrl      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateGuild(ctx context.Context, arg CreateGuildParams) (CreateGuildRow, error) {
	row := q.db.QueryRow(ctx, createGuild,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.CustomSettings,
		arg.IconUrl,
		arg.BannerUrl,
	)
	var i CreateGuildRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Timezone,
		&i.Language,
		&i.Public,
		&i.AllowInvites,
		&i.CustomSettings,
		&i.IconUrl,
		&i.BannerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGuild = `-- name: DeleteGuild :exec
DELETE FROM guilds WHERE id = $1
`

func (q *Queries) DeleteGuild(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGuild, id)
	return err
}

const deleteGuildMember = `-- name: DeleteGuildMember :exec
DELETE FROM members WHERE user_id = $1 AND guild_id = $2
`

type DeleteGuildMemberParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteGuildMember(ctx context.Context, arg DeleteGuildMemberParams) error {
	_, err := q.db.Exec(ctx, deleteGuildMember, arg.UserID, arg.GuildID)
	return err
}

const getGuild = `-- name: GetGuild :one
SELECT id, name,
       COALESCE(description, '') AS description,
       owner_id,
       timezone, language, public, allow_invites,
       custom_settings,
       COALESCE(icon_url, '')   AS icon_url,
       COALESCE(banner_url, '') AS banner_url,
       created_at, updated_at
FROM guilds
WHERE id = $1
`

type GetGuildRow struct {
	ID             uuid.UUID
	Name           string
	Description    string
	OwnerID        uuid.UUID
	Timezone       string
	Language       string
	Public         bool
	AllowInvites   bool
	CustomSettings []byte
	IconUrl        string
	BannerUrl      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetGuild(ctx context.Context, id uuid.UUID) (GetGuildRow, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i GetGuildRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Timezone,
		&i.Language,
		&i.Public,
		&i.AllowInvites,
		&i.CustomSettings,
		&i.IconUrl,
		&i.BannerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuildMemberRole = `-- name: GetGuildMemberRole :one
SELECT role FROM members WHERE guild_id = $1 AND user_id = $2
`

type GetGuildMemberRoleParams struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetGuildMemberRole(ctx context.Context, arg GetGuildMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getGuildMemberRole, arg.GuildID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getGuildOwner = `-- name: GetGuildOwner :one
SELECT owner_id FROM guilds WHERE id = $1
`

func (q *Queries) GetGuildOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getGuildOwner, id)
	var owner_id uuid.UUID
	err := row.Scan(&owner_id)
	return owner_id, err
}

const getGuildPublic = `-- name: GetGuildPublic :one
SELECT public FROM guilds WHERE id = $1
`

func (q *Queries) GetGuildPublic(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getGuildPublic, id)
	var public bool
	err := row.Scan(&public)
	return public, err
}

const getGuildSettings = `-- name: GetGuildSettings :one
SELECT timezone, language, public, allow_invites, custom_settings
FROM guilds WHERE id = $1
`

type GetGuildSettingsRow struct {
	Timezone       string
	Language       string
	Public         bool
	AllowInvites   bool
	CustomSettings []byte
}

func (q *Queries) GetGuildSettings(ctx context.Context, id uuid.UUID) (GetGuildSettingsRow, error) {
	row := q.db.QueryRow(ctx, getGuildSettings, id)
	var i GetGuildSettingsRow
	err := row.Scan(
		&i.Timezone,
		&i.Language,
		&i.Public,
		&i.AllowInvites,
		&i.CustomSettings,
	)
	return i, err
}

const getOldestGuild = `-- name: GetOldestGuild :one
SELECT id, name FROM guilds ORDER BY created_at ASC LIMIT 1
`

type GetOldestGuildRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetOldestGuild(ctx context.Context) (GetOldestGuildRow, error) {
	row := q.db.QueryRow(ctx, getOldestGuild)
	var i GetOldestGuildRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSingletonGuildID = `-- name: GetSingletonGuildID :one
SELECT id FROM guilds
WHERE (SELECT COUNT(*) FROM guilds) = 1
`

// Returns the id of the only guild when exactly one exists; pgx.ErrNoRows
// otherwise (used by user bootstrap to auto-join a new user to a
// single-guild deployment).
func (q *Queries) GetSingletonGuildID(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSingletonGuildID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserCurrentGuild = `-- name: GetUserCurrentGuild :one
SELECT g.id, g.name,
       COALESCE(g.description, '') AS description,
       g.owner_id,
       g.timezone, g.language, g.public, g.allow_invites,
       g.custom_settings,
       COALESCE(g.icon_url, '')   AS icon_url,
       COALESCE(g.banner_url, '') AS banner_url,
       g.created_at, g.updated_at
FROM guilds g
JOIN members m ON m.guild_id = g.id
WHERE m.user_id = $1
ORDER BY m.last_active DESC
LIMIT 1
`

type GetUserCurrentGuildRow struct {
	ID             uuid.UUID
	Name           string
	Description    string
	OwnerID        uuid.UUID
	Timezone       string
	Language       string
	Public         bool
	AllowInvites   bool
	CustomSettings []byte
	IconUrl        string
	BannerUrl      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetUserCurrentGuild(ctx context.Context, userID uuid.UUID) (GetUserCurrentGuildRow, error) {
	row := q.db.QueryRow(ctx, getUserCurrentGuild, userID)
	var i GetUserCurrentGuildRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Timezone,
		&i.Language,
		&i.Public,
		&i.AllowInvites,
		&i.CustomSettings,
		&i.IconUrl,
		&i.BannerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGuildMember = `-- name: InsertGuildMember :exec
INSERT INTO members (user_id, guild_id, role)
VALUES ($1, $2, $3::text)
ON CONFLICT (user_id, guild_id) DO NOTHING
`

type InsertGuildMemberParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
	Role    string
}

func (q *Queries) InsertGuildMember(ctx context.Context, arg InsertGuildMemberParams) error {
	_, err := q.db.Exec(ctx, insertGuildMember, arg.UserID, arg.GuildID, arg.Role)
	return err
}

const listGuildMemberUsers = `-- name: ListGuildMemberUsers :many
SELECT u.id, u.email, u.username,
       COALESCE(u.display_name, '') AS display_name,
       COALESCE(u.avatar_url, '')   AS avatar_url,
       u.created_at,
       m.role
FROM members m
JOIN users u ON u.id = m.user_id
WHERE m.guild_id = $1
ORDER BY CASE m.role
             WHEN 'owner' THEN 0
             WHEN 'admin' THEN 1
             WHEN 'moderator' THEN 2
             ELSE 3
         END,
         m.joined_at ASC
LIMIT $2::int
`

type ListGuildMemberUsersParams struct {
	GuildID uuid.UUID
	MaxRows int32
}

type ListGuildMemberUsersRow struct {
	ID          uuid.UUID
	Email       string
	Username    string
	DisplayName string
	AvatarUrl   string
	CreatedAt   time.Time
	Role        string
}

func (q *Queries) ListGuildMemberUsers(ctx context.Context, arg ListGuildMemberUsersParams) ([]ListGuildMemberUsersRow, error) {
	rows, err := q.db.Query(ctx, listGuildMemberUsers, arg.GuildID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildMemberUsersRow{}
	for rows.Next() {
		var i ListGuildMemberUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildMembers = `-- name: ListGuildMembers :many
SELECT m.id, m.user_id, m.guild_id,
       COALESCE(NULLIF(m.display_name, ''), NULLIF(u.display_name, ''), u.username)::text AS display_name,
       m.role, m.profile, m.joined_at, m.last_active,
       u.email,
       COALESCE(u.avatar_url, '') AS avatar_url
FROM members m
JOIN users u ON u.id = m.user_id
WHERE m.guild_id = $1
  AND ($2::text = '' OR m.role = $2::text)
ORDER BY CASE m.role
             WHEN 'owner' THEN 0
             WHEN 'admin' THEN 1
             WHEN 'moderator' THEN 2
             ELSE 3
         END,
         m.joined_at ASC,
         m.id ASC
LIMIT $4::int OFFSET $3::int
`

type ListGuildMembersParams struct {
	GuildID    uuid.UUID
	RoleFilter string
	PageOffset int32
	PageSize   int32
}

type ListGuildMembersRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	GuildID     uuid.UUID
	DisplayName string
	Role        string
	Profile     []byte
	JoinedAt    time.Time
	LastActive  time.Time
	Email       string
	AvatarUrl   string
}

func (q *Queries) ListGuildMembers(ctx context.Context, arg ListGuildMembersParams) ([]ListGuildMembersRow, error) {
	rows, err := q.db.Query(ctx, listGuildMembers,
		arg.GuildID,
		arg.RoleFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildMembersRow{}
	for rows.Next() {
		var i ListGuildMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuildID,
			&i.DisplayName,
			&i.Role,
			&i.Profile,
			&i.JoinedAt,
			&i.LastActive,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuilds = `-- name: ListGuilds :many
SELECT id, name,
       COALESCE(description, '') AS description,
       owner_id,
       timezone, language, public, allow_invites,
       custom_settings,
       COALESCE(icon_url, '')   AS icon_url,
       COALESCE(banner_url, '') AS banner_url,
       created_at, updated_at
FROM guilds
WHERE ($1::text = '%%' OR name ILIKE $1::text OR description ILIKE $1::text)
ORDER BY created_at DESC
LIMIT $3::int
OFFSET $2::int
`

type ListGuildsParams struct {
	Search     string
	PageOffset int32
	PageSize   int32
}

type ListGuildsRow struct {
	ID             uuid.UUID
	Name           string
	Description    string
	OwnerID        uuid.UUID
	Timezone       string
	Language       string
	Public         bool
	AllowInvites   bool
	CustomSettings []byte
	IconUrl        string
	BannerUrl      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListGuilds(ctx context.Context, arg ListGuildsParams) ([]ListGuildsRow, error) {
	rows, err := q.db.Query(ctx, listGuilds, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuildsRow{}
	for rows.Next() {
		var i ListGuildsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.Timezone,
			&i.Language,
			&i.Public,
			&i.AllowInvites,
			&i.CustomSettings,
			&i.IconUrl,
			&i.BannerUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuild = `-- name: UpdateGuild :one
UPDATE guilds SET
    name        = CASE WHEN $1::text        != '' THEN $1::text        ELSE name        END,
    description = CASE WHEN $2::text != '' THEN $2::text ELSE description END,
    icon_url    = CASE WHEN $3::text    != '' THEN $3::text    ELSE icon_url    END,
    banner_url  = CASE WHEN $4::text  != '' THEN $4::text  ELSE banner_url  END,
    updated_at  = NOW()
WHERE id = $5
RETURNING id, name,
          COALESCE(description, '') AS description,
          owner_id,
          timezone, language, public, allow_invites,
          custom_settings,
          COALESCE(icon_url, '')   AS icon_url,
          COALESCE(banner_url, '') AS banner_url,
          created_at, updated_at
`

type UpdateGuildParams struct {
	Name        string
	Description string
	IconUrl     string
	BannerUrl   string
	ID          uuid.UUID
}

type UpdateGuildRow struct {
	ID             uuid.UUID
	Name           string
	Description    string
	OwnerID        uuid.UUID
	Timezone       string
	Language       string
	Public         bool
	AllowInvites   bool
	CustomSettings []byte
	IconUrl        string
	BannerUrl      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateGuild(ctx context.Context, arg UpdateGuildParams) (UpdateGuildRow, error) {
	row := q.db.QueryRow(ctx, updateGuild,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.BannerUrl,
		arg.ID,
	)
	var i UpdateGuildRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Timezone,
		&i.Language,
		&i.Public,
		&i.AllowInvites,
		&i.CustomSettings,
		&i.IconUrl,
		&i.BannerUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGuildSettings = `-- name: UpdateGuildSettings :exec
UPDATE guilds SET
    timezone        = $1::text,
    language        = $2::text,
    public          = $3::bool,
    allow_invites   = $4::bool,
    custom_settings = $5::jsonb,
    updated_at      = NOW()
WHERE id = $6
`

type UpdateGuildSettingsParams struct {
	Timezone       string
	Language       string
	Public         bool
	AllowInvites   bool
	CustomSettings []byte
	ID             uuid.UUID
}

func (q *Queries) UpdateGuildSettings(ctx context.Context, arg UpdateGuildSettingsParams) error {
	_, err := q.db.Exec(ctx, updateGuildSettings,
		arg.Timezone,
		arg.Language,
		arg.Public,
		arg.AllowInvites,
		arg.CustomSettings,
		arg.ID,
	)
	return err
}
