// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const backpackItemOwned = `-- name: BackpackItemOwned :one
SELECT EXISTS (
    SELECT 1 FROM backpack_items
    WHERE backpack_items.id = $1 AND backpack_items.owner_id = $2 AND backpack_items.guild_id = $3
)
`

type BackpackItemOwnedParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) BackpackItemOwned(ctx context.Context, arg BackpackItemOwnedParams) (bool, error) {
	row := q.db.QueryRow(ctx, backpackItemOwned, arg.ID, arg.OwnerID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const bankItemExists = `-- name: BankItemExists :one
SELECT EXISTS (SELECT 1 FROM bank_items WHERE bank_items.id = $1 AND bank_items.guild_id = $2)
`

type BankItemExistsParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) BankItemExists(ctx context.Context, arg BankItemExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, bankItemExists, arg.ID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const consumeBackpackItem = `-- name: ConsumeBackpackItem :one
DELETE FROM backpack_items
WHERE backpack_items.id = $1
  AND backpack_items.locked_by_type = $2::text
  AND backpack_items.locked_by_id = $3::uuid
RETURNING backpack_items.item
`

type ConsumeBackpackItemParams struct {
	ID         uuid.UUID
	HolderType string
	HolderID   uuid.UUID
}

func (q *Queries) ConsumeBackpackItem(ctx context.Context, arg ConsumeBackpackItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, consumeBackpackItem, arg.ID, arg.HolderType, arg.HolderID)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const consumeBankItem = `-- name: ConsumeBankItem :one
DELETE FROM bank_items
WHERE bank_items.id = $1
  AND bank_items.locked_by_type = $2::text
  AND bank_items.locked_by_id = $3::uuid
RETURNING bank_items.item
`

type ConsumeBankItemParams struct {
	ID         uuid.UUID
	HolderType string
	HolderID   uuid.UUID
}

func (q *Queries) ConsumeBankItem(ctx context.Context, arg ConsumeBankItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, consumeBankItem, arg.ID, arg.HolderType, arg.HolderID)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const deleteReleasedCancelledLoot = `-- name: DeleteReleasedCancelledLoot :many
DELETE FROM bank_items
WHERE bank_items.id = $1
  AND bank_items.locked_by_type = $2::text
  AND bank_items.locked_by_id = $3::uuid
  AND bank_items.checkin_id IN (SELECT c.id FROM checkins c WHERE c.cancelled_at IS NOT NULL)
RETURNING bank_items.guild_id, bank_items.checkin_id
`

type DeleteReleasedCancelledLootParams struct {
	ID         uuid.UUID
	HolderType string
	HolderID   uuid.UUID
}

type DeleteReleasedCancelledLootRow struct {
	GuildID   uuid.UUID
	CheckinID *uuid.UUID
}

func (q *Queries) DeleteReleasedCancelledLoot(ctx context.Context, arg DeleteReleasedCancelledLootParams) ([]DeleteReleasedCancelledLootRow, error) {
	rows, err := q.db.Query(ctx, deleteReleasedCancelledLoot, arg.ID, arg.HolderType, arg.HolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteReleasedCancelledLootRow{}
	for rows.Next() {
		var i DeleteReleasedCancelledLootRow
		if err := rows.Scan(&i.GuildID, &i.CheckinID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBackpackItem = `-- name: LockBackpackItem :one
UPDATE backpack_items SET
    locked_by_type = $1::text,
    locked_by_id   = $2::uuid,
    locked_at      = NOW()
WHERE backpack_items.id = $3 AND backpack_items.owner_id = $4
  AND backpack_items.guild_id = $5 AND backpack_items.locked_by_type IS NULL
  AND backpack_items.delivery_requested_at IS NULL
RETURNING backpack_items.item
`

type LockBackpackItemParams struct {
	HolderType string
	HolderID   uuid.UUID
	ID         uuid.UUID
	OwnerID    uuid.UUID
	GuildID    uuid.UUID
}

func (q *Queries) LockBackpackItem(ctx context.Context, arg LockBackpackItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockBackpackItem,
		arg.HolderType,
		arg.HolderID,
		arg.ID,
		arg.OwnerID,
		arg.GuildID,
	)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const lockBankItem = `-- name: LockBankItem :one
UPDATE bank_items SET
    locked_by_type = $1::text,
    locked_by_id   = $2::uuid,
    locked_at      = NOW()
WHERE bank_items.id = $3 AND bank_items.guild_id = $4
  AND bank_items.locked_by_type IS NULL
RETURNING bank_items.item
`

type LockBankItemParams struct {
	HolderType string
	HolderID   uuid.UUID
	ID         uuid.UUID
	GuildID    uuid.UUID
}

func (q *Queries) LockBankItem(ctx context.Context, arg LockBankItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockBankItem,
		arg.HolderType,
		arg.HolderID,
		arg.ID,
		arg.GuildID,
	)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const rejectPendingRequestsForBankItem = `-- name: RejectPendingRequestsForBankItem :execrows
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    review_note = NULLIF($2::text, ''),
    reviewed_at = NOW()
WHERE bank_item_id = $3 AND guild_id = $4 AND status = 'pending'
`

type RejectPendingRequestsForBankItemParams struct {
	ReviewerID *uuid.UUID
	ReviewNote string
	BankItemID *uuid.UUID
	GuildID    uuid.UUID
}

func (q *Queries) RejectPendingRequestsForBankItem(ctx context.Context, arg RejectPendingRequestsForBankItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPendingRequestsForBankItem,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.BankItemID,
		arg.GuildID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseBackpackItem = `-- name: ReleaseBackpackItem :many
UPDATE backpack_items SET locked_by_type = NULL, locked_by_id = NULL, locked_at = NULL
WHERE backpack_items.id = $1
  AND backpack_items.locked_by_type = $2::text
  AND backpack_items.locked_by_id = $3::uuid
RETURNING backpack_items.guild_id
`

type ReleaseBackpackItemParams struct {
	ID         uuid.UUID
	HolderType string
	HolderID   uuid.UUID
}

func (q *Queries) ReleaseBackpackItem(ctx context.Context, arg ReleaseBackpackItemParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, releaseBackpackItem, arg.ID, arg.HolderType, arg.HolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var guild_id uuid.UUID
		if err := rows.Scan(&guild_id); err != nil {
			return nil, err
		}
		items = append(items, guild_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseBankItem = `-- name: ReleaseBankItem :many
UPDATE bank_items SET locked_by_type = NULL, locked_by_id = NULL, locked_at = NULL
WHERE bank_items.id = $1
  AND bank_items.locked_by_type = $2::text
  AND bank_items.locked_by_id = $3::uuid
RETURNING bank_items.guild_id
`

type ReleaseBankItemParams struct {
	ID         uuid.UUID
	HolderType string
	HolderID   uuid.UUID
}

func (q *Queries) ReleaseBankItem(ctx context.Context, arg ReleaseBankItemParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, releaseBankItem, arg.ID, arg.HolderType, arg.HolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var guild_id uuid.UUID
		if err := rows.Scan(&guild_id); err != nil {
			return nil, err
		}
		items = append(items, guild_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
