// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_template.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countGuildItemTemplates = `-- name: CountGuildItemTemplates :one
SELECT COUNT(*) FROM item_templates
WHERE guild_id = $1 AND id = ANY($2::uuid[])
`

type CountGuildItemTemplatesParams struct {
	GuildID uuid.UUID
	Ids     []uuid.UUID
}

func (q *Queries) CountGuildItemTemplates(ctx context.Context, arg CountGuildItemTemplatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGuildItemTemplates, arg.GuildID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemTemplate = `-- name: CreateItemTemplate :one
INSERT INTO item_templates (guild_id, name, description, category, rarity, created_by)
VALUES ($1, $3::text, $4::text, $5::text, $6::text, $2)
RETURNING id, guild_id, name, description, category, rarity, created_by, created_at, updated_at
`

type CreateItemTemplateParams struct {
	GuildID     uuid.UUID
	CreatedBy   uuid.UUID
	Name        string
	Description string
	Category    string
	Rarity      string
}

func (q *Queries) CreateItemTemplate(ctx context.Context, arg CreateItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRow(ctx, createItemTemplate,
		arg.GuildID,
		arg.CreatedBy,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Rarity,
	)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Rarity,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItemTemplate = `-- name: DeleteItemTemplate :execrows
DELETE FROM item_templates WHERE id = $1 AND guild_id = $2
`

type DeleteItemTemplateParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteItemTemplate(ctx context.Context, arg DeleteItemTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItemTemplate, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listItemTemplates = `-- name: ListItemTemplates :many
SELECT id, guild_id, name, description, category, rarity, created_by, created_at, updated_at
FROM item_templates
WHERE guild_id = $1
ORDER BY name ASC
`

func (q *Queries) ListItemTemplates(ctx context.Context, guildID uuid.UUID) ([]ItemTemplate, error) {
	rows, err := q.db.Query(ctx, listItemTemplates, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTemplate{}
	for rows.Next() {
		var i ItemTemplate
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Rarity,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemTemplate = `-- name: UpdateItemTemplate :one
UPDATE item_templates SET
    name        = $1::text,
    description = $2::text,
    category    = $3::text,
    rarity      = $4::text,
    updated_at  = NOW()
WHERE id = $5 AND guild_id = $6
RETURNING id, guild_id, name, description, category, rarity, created_by, created_at, updated_at
`

type UpdateItemTemplateParams struct {
	Name        string
	Description string
	Category    string
	Rarity      string
	ID          uuid.UUID
	GuildID     uuid.UUID
}

func (q *Queries) UpdateItemTemplate(ctx context.Context, arg UpdateItemTemplateParams) (ItemTemplate, error) {
	row := q.db.QueryRow(ctx, updateItemTemplate,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Rarity,
		arg.ID,
		arg.GuildID,
	)
	var i ItemTemplate
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Rarity,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
