// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lottery.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLotteries = `-- name: CountLotteries :one
SELECT COUNT(*) FROM lotteries WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
`

type CountLotteriesParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountLotteries(ctx context.Context, arg CountLotteriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLotteries, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserTickets = `-- name: CountUserTickets :one
SELECT COUNT(*) FROM lottery_tickets lt
JOIN lotteries l ON l.id = lt.lottery_id
WHERE lt.user_id = $1
  AND ($2::text = '' OR l.guild_id::text = $2::text)
`

type CountUserTicketsParams struct {
	UserID      uuid.UUID
	GuildFilter string
}

func (q *Queries) CountUserTickets(ctx context.Context, arg CountUserTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTickets, arg.UserID, arg.GuildFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserTicketsForLottery = `-- name: CountUserTicketsForLottery :one
SELECT COUNT(*) FROM lottery_tickets WHERE lottery_id = $1 AND user_id = $2
`

type CountUserTicketsForLotteryParams struct {
	LotteryID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) CountUserTicketsForLottery(ctx context.Context, arg CountUserTicketsForLotteryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTicketsForLottery, arg.LotteryID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLottery = `-- name: CreateLottery :one
INSERT INTO lotteries (
    id, guild_id, created_by, title, description, ticket_price,
    max_tickets, max_tickets_per_user, status, draw_date, prizes
) VALUES (
    $6::uuid, $1, $2, $7::text,
    NULLIF($8::text, ''),
    $3, $4, $5, 'active',
    $9::text::timestamptz,
    $10::jsonb
)
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          ticket_price, tickets_sold,
          max_tickets, max_tickets_per_user, status,
          TO_CHAR(draw_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS draw_date,
          prizes, created_at, updated_at
`

type CreateLotteryParams struct {
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	TicketPrice       int64
	MaxTickets        int32
	MaxTicketsPerUser int32
	ID                uuid.UUID
	Title             string
	Description       string
	DrawDate          string
	Prizes            []byte
}

type CreateLotteryRow struct {
	ID                uuid.UUID
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	Description       string
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          string
	Prizes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreateLottery(ctx context.Context, arg CreateLotteryParams) (CreateLotteryRow, error) {
	row := q.db.QueryRow(ctx, createLottery,
		arg.GuildID,
		arg.CreatedBy,
		arg.TicketPrice,
		arg.MaxTickets,
		arg.MaxTicketsPerUser,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DrawDate,
		arg.Prizes,
	)
	var i CreateLotteryRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.TicketPrice,
		&i.TicketsSold,
		&i.MaxTickets,
		&i.MaxTicketsPerUser,
		&i.Status,
		&i.DrawDate,
		&i.Prizes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endLottery = `-- name: EndLottery :exec
UPDATE lotteries SET status = 'ended', updated_at = NOW() WHERE id = $1
`

func (q *Queries) EndLottery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, endLottery, id)
	return err
}

const ensureWalletDefault = `-- name: EnsureWalletDefault :exec
INSERT INTO wallets (user_id, guild_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type EnsureWalletDefaultParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) EnsureWalletDefault(ctx context.Context, arg EnsureWalletDefaultParams) error {
	_, err := q.db.Exec(ctx, ensureWalletDefault, arg.UserID, arg.GuildID)
	return err
}

const getLottery = `-- name: GetLottery :one
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       ticket_price, tickets_sold,
       max_tickets, max_tickets_per_user, status,
       TO_CHAR(draw_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS draw_date,
       prizes, created_at, updated_at
FROM lotteries WHERE id = $1 AND guild_id = $2
`

type GetLotteryParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetLotteryRow struct {
	ID                uuid.UUID
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	Description       string
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          string
	Prizes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) GetLottery(ctx context.Context, arg GetLotteryParams) (GetLotteryRow, error) {
	row := q.db.QueryRow(ctx, getLottery, arg.ID, arg.GuildID)
	var i GetLotteryRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.TicketPrice,
		&i.TicketsSold,
		&i.MaxTickets,
		&i.MaxTicketsPerUser,
		&i.Status,
		&i.DrawDate,
		&i.Prizes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLotteryForDraw = `-- name: GetLotteryForDraw :one
SELECT prizes, status, created_by, title, ticket_price
FROM lotteries WHERE id = $1 AND guild_id = $2 FOR UPDATE
`

type GetLotteryForDrawParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetLotteryForDrawRow struct {
	Prizes      []byte
	Status      string
	CreatedBy   uuid.UUID
	Title       string
	TicketPrice int64
}

func (q *Queries) GetLotteryForDraw(ctx context.Context, arg GetLotteryForDrawParams) (GetLotteryForDrawRow, error) {
	row := q.db.QueryRow(ctx, getLotteryForDraw, arg.ID, arg.GuildID)
	var i GetLotteryForDrawRow
	err := row.Scan(
		&i.Prizes,
		&i.Status,
		&i.CreatedBy,
		&i.Title,
		&i.TicketPrice,
	)
	return i, err
}

const getLotteryForPurchase = `-- name: GetLotteryForPurchase :one
SELECT ticket_price, status, max_tickets, max_tickets_per_user, tickets_sold
FROM lotteries WHERE id = $1 AND guild_id = $2
`

type GetLotteryForPurchaseParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetLotteryForPurchaseRow struct {
	TicketPrice       int64
	Status            string
	MaxTickets        int32
	MaxTicketsPerUser int32
	TicketsSold       int32
}

func (q *Queries) GetLotteryForPurchase(ctx context.Context, arg GetLotteryForPurchaseParams) (GetLotteryForPurchaseRow, error) {
	row := q.db.QueryRow(ctx, getLotteryForPurchase, arg.ID, arg.GuildID)
	var i GetLotteryForPurchaseRow
	err := row.Scan(
		&i.TicketPrice,
		&i.Status,
		&i.MaxTickets,
		&i.MaxTicketsPerUser,
		&i.TicketsSold,
	)
	return i, err
}

const getUserUsernameAndAvatar = `-- name: GetUserUsernameAndAvatar :one
SELECT COALESCE(username, '')   AS username,
       COALESCE(avatar_url, '') AS avatar_url
FROM users WHERE id = $1
`

type GetUserUsernameAndAvatarRow struct {
	Username  string
	AvatarUrl string
}

func (q *Queries) GetUserUsernameAndAvatar(ctx context.Context, id uuid.UUID) (GetUserUsernameAndAvatarRow, error) {
	row := q.db.QueryRow(ctx, getUserUsernameAndAvatar, id)
	var i GetUserUsernameAndAvatarRow
	err := row.Scan(&i.Username, &i.AvatarUrl)
	return i, err
}

const incrementTicketsSold = `-- name: IncrementTicketsSold :exec
UPDATE lotteries SET tickets_sold = tickets_sold + $1::int, updated_at = NOW() WHERE id = $2
`

type IncrementTicketsSoldParams struct {
	N  int32
	ID uuid.UUID
}

func (q *Queries) IncrementTicketsSold(ctx context.Context, arg IncrementTicketsSoldParams) error {
	_, err := q.db.Exec(ctx, incrementTicketsSold, arg.N, arg.ID)
	return err
}

const insertLotteryTicket = `-- name: InsertLotteryTicket :one
INSERT INTO lottery_tickets (lottery_id, user_id, ticket_number)
VALUES ($1, $2, $3::text)
RETURNING id, purchased_at
`

type InsertLotteryTicketParams struct {
	LotteryID    uuid.UUID
	UserID       uuid.UUID
	TicketNumber string
}

type InsertLotteryTicketRow struct {
	ID          uuid.UUID
	PurchasedAt time.Time
}

func (q *Queries) InsertLotteryTicket(ctx context.Context, arg InsertLotteryTicketParams) (InsertLotteryTicketRow, error) {
	row := q.db.QueryRow(ctx, insertLotteryTicket, arg.LotteryID, arg.UserID, arg.TicketNumber)
	var i InsertLotteryTicketRow
	err := row.Scan(&i.ID, &i.PurchasedAt)
	return i, err
}

const insertLotteryWinner = `-- name: InsertLotteryWinner :one
INSERT INTO lottery_winners (lottery_id, user_id, rank, prize_amount, prize_description, ticket_number)
VALUES ($1, $2, $4::int, $3, NULLIF($5::text, ''), $6::text)
RETURNING id
`

type InsertLotteryWinnerParams struct {
	LotteryID        uuid.UUID
	UserID           uuid.UUID
	PrizeAmount      int64
	Rank             int32
	PrizeDescription string
	TicketNumber     string
}

func (q *Queries) InsertLotteryWinner(ctx context.Context, arg InsertLotteryWinnerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertLotteryWinner,
		arg.LotteryID,
		arg.UserID,
		arg.PrizeAmount,
		arg.Rank,
		arg.PrizeDescription,
		arg.TicketNumber,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAllLotteryTickets = `-- name: ListAllLotteryTickets :many
SELECT id, user_id, ticket_number FROM lottery_tickets WHERE lottery_id = $1
`

type ListAllLotteryTicketsRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	TicketNumber string
}

func (q *Queries) ListAllLotteryTickets(ctx context.Context, lotteryID uuid.UUID) ([]ListAllLotteryTicketsRow, error) {
	rows, err := q.db.Query(ctx, listAllLotteryTickets, lotteryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllLotteryTicketsRow{}
	for rows.Next() {
		var i ListAllLotteryTicketsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.TicketNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueLotteries = `-- name: ListDueLotteries :many
SELECT id, guild_id FROM lotteries
WHERE status <> 'ended' AND draw_date <= NOW()
ORDER BY draw_date ASC
LIMIT $1::int
`

type ListDueLotteriesRow struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) ListDueLotteries(ctx context.Context, maxRows int32) ([]ListDueLotteriesRow, error) {
	rows, err := q.db.Query(ctx, listDueLotteries, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueLotteriesRow{}
	for rows.Next() {
		var i ListDueLotteriesRow
		if err := rows.Scan(&i.ID, &i.GuildID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotteries = `-- name: ListLotteries :many
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       ticket_price, tickets_sold,
       max_tickets, max_tickets_per_user, status,
       TO_CHAR(draw_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS draw_date,
       prizes, created_at, updated_at
FROM lotteries
WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
ORDER BY created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListLotteriesParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListLotteriesRow struct {
	ID                uuid.UUID
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	Description       string
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          string
	Prizes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) ListLotteries(ctx context.Context, arg ListLotteriesParams) ([]ListLotteriesRow, error) {
	rows, err := q.db.Query(ctx, listLotteries,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotteriesRow{}
	for rows.Next() {
		var i ListLotteriesRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.TicketPrice,
			&i.TicketsSold,
			&i.MaxTickets,
			&i.MaxTicketsPerUser,
			&i.Status,
			&i.DrawDate,
			&i.Prizes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotteryWinners = `-- name: ListLotteryWinners :many
SELECT lw.id, lw.lottery_id, lw.user_id,
       COALESCE(u.username, '')   AS username,
       COALESCE(u.avatar_url, '') AS avatar_url,
       lw.rank, lw.prize_amount,
       COALESCE(lw.prize_description, '') AS prize_description,
       lw.ticket_number
FROM lottery_winners lw
LEFT JOIN users u ON u.id = lw.user_id
WHERE lw.lottery_id = $1
ORDER BY lw.rank ASC
`

type ListLotteryWinnersRow struct {
	ID               uuid.UUID
	LotteryID        uuid.UUID
	UserID           uuid.UUID
	Username         string
	AvatarUrl        string
	Rank             int32
	PrizeAmount      int64
	PrizeDescription string
	TicketNumber     string
}

func (q *Queries) ListLotteryWinners(ctx context.Context, lotteryID uuid.UUID) ([]ListLotteryWinnersRow, error) {
	rows, err := q.db.Query(ctx, listLotteryWinners, lotteryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotteryWinnersRow{}
	for rows.Next() {
		var i ListLotteryWinnersRow
		if err := rows.Scan(
			&i.ID,
			&i.LotteryID,
			&i.UserID,
			&i.Username,
			&i.AvatarUrl,
			&i.Rank,
			&i.PrizeAmount,
			&i.PrizeDescription,
			&i.TicketNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTickets = `-- name: ListUserTickets :many
SELECT lt.id, lt.lottery_id, lt.user_id, lt.ticket_number, lt.purchased_at
FROM lottery_tickets lt
JOIN lotteries l ON l.id = lt.lottery_id
WHERE lt.user_id = $1
  AND ($2::text = '' OR l.guild_id::text = $2::text)
ORDER BY lt.purchased_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListUserTicketsParams struct {
	UserID      uuid.UUID
	GuildFilter string
	PageOffset  int32
	PageSize    int32
}

func (q *Queries) ListUserTickets(ctx context.Context, arg ListUserTicketsParams) ([]LotteryTicket, error) {
	rows, err := q.db.Query(ctx, listUserTickets,
		arg.UserID,
		arg.GuildFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LotteryTicket{}
	for rows.Next() {
		var i LotteryTicket
		if err := rows.Scan(
			&i.ID,
			&i.LotteryID,
			&i.UserID,
			&i.TicketNumber,
			&i.PurchasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lotteryExists = `-- name: LotteryExists :one
SELECT EXISTS(SELECT 1 FROM lotteries WHERE id = $1 AND guild_id = $2)
`

type LotteryExistsParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) LotteryExists(ctx context.Context, arg LotteryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, lotteryExists, arg.ID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLotteryDrawDate = `-- name: UpdateLotteryDrawDate :one
UPDATE lotteries SET
    draw_date  = $1::text::timestamptz,
    updated_at = NOW()
WHERE id = $2 AND guild_id = $3 AND status <> 'ended'
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          ticket_price, tickets_sold,
          max_tickets, max_tickets_per_user, status,
          TO_CHAR(draw_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS draw_date,
          prizes, created_at, updated_at
`

type UpdateLotteryDrawDateParams struct {
	DrawDate string
	ID       uuid.UUID
	GuildID  uuid.UUID
}

type UpdateLotteryDrawDateRow struct {
	ID                uuid.UUID
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	Description       string
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          string
	Prizes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) UpdateLotteryDrawDate(ctx context.Context, arg UpdateLotteryDrawDateParams) (UpdateLotteryDrawDateRow, error) {
	row := q.db.QueryRow(ctx, updateLotteryDrawDate, arg.DrawDate, arg.ID, arg.GuildID)
	var i UpdateLotteryDrawDateRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.TicketPrice,
		&i.TicketsSold,
		&i.MaxTickets,
		&i.MaxTicketsPerUser,
		&i.Status,
		&i.DrawDate,
		&i.Prizes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
