// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID          uuid.UUID
	Type        string
	ActorID     uuid.UUID
	ActorName   string
	GuildID     *uuid.UUID
	Description string
	Metadata    []byte
	CreatedAt   time.Time
}

type Announcement struct {
	ID          uuid.UUID
	GuildID     uuid.UUID
	AuthorID    uuid.UUID
	Title       string
	Content     string
	Pinned      bool
	Status      string
	PublishedAt pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Auction struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	SellerID        uuid.UUID
	Item            []byte
	StartingBid     int64
	CurrentBid      int64
	CurrentBidderID *uuid.UUID
	MinBidIncrement int64
	StartTime       time.Time
	EndTime         time.Time
	Status          string
	IsBlind         bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	SourceType      pgtype.Text
	SettledAt       pgtype.Timestamptz
	SourceItemID    *uuid.UUID
	CancelledAt     pgtype.Timestamptz
}

type BackpackItem struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	GuildID             uuid.UUID
	Item                []byte
	Source              string
	SourceID            *uuid.UUID
	Note                pgtype.Text
	AcquiredAt          time.Time
	LockedByType        pgtype.Text
	LockedByID          *uuid.UUID
	LockedAt            pgtype.Timestamptz
	DeliveryRequestedAt pgtype.Timestamptz
}

type BankContribution struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	UserID        uuid.UUID
	Username      string
	Amount        int64
	Note          pgtype.Text
	CreatedAt     time.Time
	Kind          string
	Items         []byte
	CheckinID     *uuid.UUID
	ReferenceType pgtype.Text
	ReferenceID   *uuid.UUID
}

type BankItem struct {
	ID           uuid.UUID
	GuildID      uuid.UUID
	DonorID      uuid.UUID
	DonorName    string
	Item         []byte
	Quantity     int32
	Note         pgtype.Text
	DonatedAt    time.Time
	CheckinID    *uuid.UUID
	LockedByType pgtype.Text
	LockedByID   *uuid.UUID
	LockedAt     pgtype.Timestamptz
}

type Bid struct {
	ID        uuid.UUID
	AuctionID uuid.UUID
	BidderID  uuid.UUID
	Amount    int64
	IsWinning bool
	PlacedAt  time.Time
}

type Checkin struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     pgtype.Text
	Datetime        time.Time
	ExpireTime      time.Time
	ImageUrl        pgtype.Text
	LootList        []byte
	AttendanceCount int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CancelledAt     pgtype.Timestamptz
}

type CheckinAttendee struct {
	ID          uuid.UUID
	CheckinID   uuid.UUID
	UserID      uuid.UUID
	DisplayName pgtype.Text
	AvatarUrl   pgtype.Text
	AttendedAt  time.Time
	Notes       string
}

type CheckinTemplate struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	Name            string
	Title           string
	ItemTemplateIds []uuid.UUID
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type FundRequest struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	RequesterID   uuid.UUID
	RequesterName string
	Amount        int64
	Reason        pgtype.Text
	Status        string
	ReviewerID    *uuid.UUID
	ReviewNote    pgtype.Text
	CreatedAt     time.Time
	ReviewedAt    pgtype.Timestamptz
}

type Guild struct {
	ID             uuid.UUID
	Name           string
	Description    pgtype.Text
	OwnerID        uuid.UUID
	Timezone       string
	Language       string
	Public         bool
	AllowInvites   bool
	CustomSettings []byte
	IconUrl        pgtype.Text
	BannerUrl      pgtype.Text
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GuildBank struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	Balance   int64
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GuildEvent struct {
	ID               uuid.UUID
	GuildID          uuid.UUID
	CreatedBy        uuid.UUID
	Title            string
	Description      pgtype.Text
	Type             string
	StartDate        time.Time
	EndDate          time.Time
	IsAllDay         bool
	Location         pgtype.Text
	Priority         string
	IsRecurring      bool
	RecurringPattern []byte
	ParticipantIds   []uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type GuildLogo struct {
	GuildID     uuid.UUID
	ContentType string
	Data        []byte
	UpdatedAt   time.Time
}

type Invitation struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	Code      string
	CreatedBy uuid.UUID
	Role      string
	MaxUses   int32
	UseCount  int32
	Revoked   bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt time.Time
}

type Item struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	Category    pgtype.Text
	Rarity      pgtype.Text
}

type ItemEvent struct {
	Seq         int64
	GuildID     uuid.UUID
	ItemID      uuid.UUID
	Kind        string
	ActorID     *uuid.UUID
	SubjectID   *uuid.UUID
	Source      string
	ReferenceID *uuid.UUID
	CreatedAt   time.Time
}

type ItemRequest struct {
	ID            uuid.UUID
	GuildID       uuid.UUID
	BankItemID    *uuid.UUID
	RequesterID   uuid.UUID
	RequesterName string
	Reason        pgtype.Text
	Status        string
	ReviewerID    *uuid.UUID
	ReviewNote    pgtype.Text
	CreatedAt     time.Time
	ReviewedAt    pgtype.Timestamptz
	Item          []byte
}

type ItemTemplate struct {
	ID          uuid.UUID
	GuildID     uuid.UUID
	Name        string
	Description string
	Category    string
	Rarity      string
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Lottery struct {
	ID                uuid.UUID
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	Description       pgtype.Text
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          time.Time
	Prizes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CancelledAt       pgtype.Timestamptz
}

type LotteryTicket struct {
	ID           uuid.UUID
	LotteryID    uuid.UUID
	UserID       uuid.UUID
	TicketNumber string
	PurchasedAt  time.Time
}

type LotteryWinner struct {
	ID               uuid.UUID
	LotteryID        uuid.UUID
	UserID           uuid.UUID
	Rank             int32
	PrizeAmount      int64
	PrizeDescription pgtype.Text
	TicketNumber     string
}

type Member struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	GuildID     uuid.UUID
	DisplayName string
	Role        string
	Profile     []byte
	JoinedAt    time.Time
	LastActive  time.Time
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Message   string
	Type      string
	Read      bool
	ActionUrl pgtype.Text
	CreatedAt time.Time
	Params    []byte
}

type Transaction struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	GuildID       uuid.UUID
	Type          string
	Amount        int64
	BalanceAfter  int64
	Description   pgtype.Text
	ReferenceID   *uuid.UUID
	ReferenceType pgtype.Text
	CreatedAt     time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	Username        pgtype.Text
	DisplayName     pgtype.Text
	Bio             pgtype.Text
	AvatarUrl       pgtype.Text
	Metadata        []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DiscordUsername pgtype.Text
}

type UserPreference struct {
	UserID             uuid.UUID
	Theme              string
	Language           string
	Timezone           string
	DateFormat         string
	TimeFormat         string
	UiSettings         []byte
	UpdatedAt          time.Time
	EmailNotifications bool
	AuctionAlerts      bool
	LotteryAlerts      bool
	EventReminders     bool
	CheckinReminders   bool
}

type Wallet struct {
	UserID    uuid.UUID
	GuildID   uuid.UUID
	Balance   int64
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
