// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND NOT read
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserNotifications = `-- name: CountUserNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
  AND (NOT $2::bool OR NOT read)
`

type CountUserNotificationsParams struct {
	UserID     uuid.UUID
	UnreadOnly bool
}

func (q *Queries) CountUserNotifications(ctx context.Context, arg CountUserNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserNotifications, arg.UserID, arg.UnreadOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, user_id, title, message, type, read,
       COALESCE(action_url, '') AS action_url,
       params, created_at
FROM notifications
WHERE user_id = $1
  AND (NOT $2::bool OR NOT read)
ORDER BY created_at DESC, id DESC
LIMIT $4::int OFFSET $3::int
`

type ListUserNotificationsParams struct {
	UserID     uuid.UUID
	UnreadOnly bool
	PageOffset int32
	PageSize   int32
}

type ListUserNotificationsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Message   string
	Type      string
	Read      bool
	ActionUrl string
	Params    []byte
	CreatedAt time.Time
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]ListUserNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listUserNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserNotificationsRow{}
	for rows.Next() {
		var i ListUserNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Read,
			&i.ActionUrl,
			&i.Params,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read = TRUE WHERE user_id = $1 AND NOT read
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET read = TRUE
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, message, type, read,
          COALESCE(action_url, '') AS action_url,
          params, created_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type MarkNotificationReadRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Message   string
	Type      string
	Read      bool
	ActionUrl string
	Params    []byte
	CreatedAt time.Time
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (MarkNotificationReadRow, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i MarkNotificationReadRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Read,
		&i.ActionUrl,
		&i.Params,
		&i.CreatedAt,
	)
	return i, err
}
