// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preference.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT email_notifications, auction_alerts, raffle_alerts, event_reminders, roll_call_reminders, updated_at
FROM user_preferences
WHERE user_id = $1
`

type GetNotificationPreferencesRow struct {
	EmailNotifications bool
	AuctionAlerts      bool
	RaffleAlerts       bool
	EventReminders     bool
	RollCallReminders  bool
	UpdatedAt          time.Time
}

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (GetNotificationPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, userID)
	var i GetNotificationPreferencesRow
	err := row.Scan(
		&i.EmailNotifications,
		&i.AuctionAlerts,
		&i.RaffleAlerts,
		&i.EventReminders,
		&i.RollCallReminders,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO user_preferences (
    user_id, email_notifications, auction_alerts, raffle_alerts, event_reminders, roll_call_reminders
)
VALUES (
    $1,
    COALESCE($2::bool, TRUE),
    COALESCE($3::bool, TRUE),
    COALESCE($4::bool, TRUE),
    COALESCE($5::bool, FALSE),
    COALESCE($6::bool, TRUE)
)
ON CONFLICT (user_id) DO UPDATE SET
    email_notifications = COALESCE($2::bool, user_preferences.email_notifications),
    auction_alerts      = COALESCE($3::bool, user_preferences.auction_alerts),
    raffle_alerts      = COALESCE($4::bool, user_preferences.raffle_alerts),
    event_reminders     = COALESCE($5::bool, user_preferences.event_reminders),
    roll_call_reminders   = COALESCE($6::bool, user_preferences.roll_call_reminders),
    updated_at          = NOW()
RETURNING email_notifications, auction_alerts, raffle_alerts, event_reminders, roll_call_reminders, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID             uuid.UUID
	EmailNotifications pgtype.Bool
	AuctionAlerts      pgtype.Bool
	RaffleAlerts       pgtype.Bool
	EventReminders     pgtype.Bool
	RollCallReminders  pgtype.Bool
}

type UpsertNotificationPreferencesRow struct {
	EmailNotifications bool
	AuctionAlerts      bool
	RaffleAlerts       bool
	EventReminders     bool
	RollCallReminders  bool
	UpdatedAt          time.Time
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (UpsertNotificationPreferencesRow, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.EmailNotifications,
		arg.AuctionAlerts,
		arg.RaffleAlerts,
		arg.EventReminders,
		arg.RollCallReminders,
	)
	var i UpsertNotificationPreferencesRow
	err := row.Scan(
		&i.EmailNotifications,
		&i.AuctionAlerts,
		&i.RaffleAlerts,
		&i.EventReminders,
		&i.RollCallReminders,
		&i.UpdatedAt,
	)
	return i, err
}
