// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raffle.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRaffles = `-- name: CountRaffles :one
SELECT COUNT(*) FROM raffles WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
`

type CountRafflesParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountRaffles(ctx context.Context, arg CountRafflesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRaffles, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserTickets = `-- name: CountUserTickets :one
SELECT COUNT(*) FROM raffle_tickets lt
JOIN raffles l ON l.id = lt.raffle_id
WHERE lt.user_id = $1
  AND ($2::text = '' OR l.guild_id::text = $2::text)
`

type CountUserTicketsParams struct {
	UserID      uuid.UUID
	GuildFilter string
}

func (q *Queries) CountUserTickets(ctx context.Context, arg CountUserTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTickets, arg.UserID, arg.GuildFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserTicketsForRaffle = `-- name: CountUserTicketsForRaffle :one
SELECT COUNT(*) FROM raffle_tickets WHERE raffle_id = $1 AND user_id = $2
`

type CountUserTicketsForRaffleParams struct {
	RaffleID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) CountUserTicketsForRaffle(ctx context.Context, arg CountUserTicketsForRaffleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserTicketsForRaffle, arg.RaffleID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRaffle = `-- name: CreateRaffle :one
INSERT INTO raffles (
    id, guild_id, created_by, title, description, ticket_price,
    max_tickets, max_tickets_per_user, status, draw_date, prizes
) VALUES (
    $6::uuid, $1, $2, $7::text,
    NULLIF($8::text, ''),
    $3, $4, $5, 'active',
    $9::text::timestamptz,
    $10::jsonb
)
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          ticket_price, tickets_sold,
          max_tickets, max_tickets_per_user, status,
          TO_CHAR(draw_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS draw_date,
          prizes, created_at, updated_at, cancelled_at
`

type CreateRaffleParams struct {
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	TicketPrice       int64
	MaxTickets        int32
	MaxTicketsPerUser int32
	ID                uuid.UUID
	Title             string
	Description       string
	DrawDate          string
	Prizes            []byte
}

type CreateRaffleRow struct {
	ID                uuid.UUID
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	Description       string
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          string
	Prizes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CancelledAt       pgtype.Timestamptz
}

func (q *Queries) CreateRaffle(ctx context.Context, arg CreateRaffleParams) (CreateRaffleRow, error) {
	row := q.db.QueryRow(ctx, createRaffle,
		arg.GuildID,
		arg.CreatedBy,
		arg.TicketPrice,
		arg.MaxTickets,
		arg.MaxTicketsPerUser,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DrawDate,
		arg.Prizes,
	)
	var i CreateRaffleRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.TicketPrice,
		&i.TicketsSold,
		&i.MaxTickets,
		&i.MaxTicketsPerUser,
		&i.Status,
		&i.DrawDate,
		&i.Prizes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const deleteCancelledRaffle = `-- name: DeleteCancelledRaffle :execrows
DELETE FROM raffles WHERE id = $1 AND guild_id = $2 AND status = 'cancelled'
`

type DeleteCancelledRaffleParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteCancelledRaffle(ctx context.Context, arg DeleteCancelledRaffleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCancelledRaffle, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endRaffle = `-- name: EndRaffle :exec
UPDATE raffles SET status = 'ended', updated_at = NOW() WHERE id = $1
`

func (q *Queries) EndRaffle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, endRaffle, id)
	return err
}

const ensureWalletDefault = `-- name: EnsureWalletDefault :exec
INSERT INTO wallets (user_id, guild_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type EnsureWalletDefaultParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) EnsureWalletDefault(ctx context.Context, arg EnsureWalletDefaultParams) error {
	_, err := q.db.Exec(ctx, ensureWalletDefault, arg.UserID, arg.GuildID)
	return err
}

const getRaffle = `-- name: GetRaffle :one
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       ticket_price, tickets_sold,
       max_tickets, max_tickets_per_user, status,
       TO_CHAR(draw_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS draw_date,
       prizes, created_at, updated_at, cancelled_at
FROM raffles WHERE id = $1 AND guild_id = $2
`

type GetRaffleParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetRaffleRow struct {
	ID                uuid.UUID
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	Description       string
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          string
	Prizes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CancelledAt       pgtype.Timestamptz
}

func (q *Queries) GetRaffle(ctx context.Context, arg GetRaffleParams) (GetRaffleRow, error) {
	row := q.db.QueryRow(ctx, getRaffle, arg.ID, arg.GuildID)
	var i GetRaffleRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.TicketPrice,
		&i.TicketsSold,
		&i.MaxTickets,
		&i.MaxTicketsPerUser,
		&i.Status,
		&i.DrawDate,
		&i.Prizes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getRaffleForDraw = `-- name: GetRaffleForDraw :one
SELECT prizes, status, created_by, title, ticket_price
FROM raffles WHERE id = $1 AND guild_id = $2 FOR UPDATE
`

type GetRaffleForDrawParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetRaffleForDrawRow struct {
	Prizes      []byte
	Status      string
	CreatedBy   uuid.UUID
	Title       string
	TicketPrice int64
}

func (q *Queries) GetRaffleForDraw(ctx context.Context, arg GetRaffleForDrawParams) (GetRaffleForDrawRow, error) {
	row := q.db.QueryRow(ctx, getRaffleForDraw, arg.ID, arg.GuildID)
	var i GetRaffleForDrawRow
	err := row.Scan(
		&i.Prizes,
		&i.Status,
		&i.CreatedBy,
		&i.Title,
		&i.TicketPrice,
	)
	return i, err
}

const getUserUsernameAndAvatar = `-- name: GetUserUsernameAndAvatar :one
SELECT COALESCE(member_display_name($1::uuid, id), '')::text AS username,
       COALESCE(avatar_url, '')                                               AS avatar_url
FROM users WHERE id = $2
`

type GetUserUsernameAndAvatarParams struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
}

type GetUserUsernameAndAvatarRow struct {
	Username  string
	AvatarUrl string
}

func (q *Queries) GetUserUsernameAndAvatar(ctx context.Context, arg GetUserUsernameAndAvatarParams) (GetUserUsernameAndAvatarRow, error) {
	row := q.db.QueryRow(ctx, getUserUsernameAndAvatar, arg.GuildID, arg.UserID)
	var i GetUserUsernameAndAvatarRow
	err := row.Scan(&i.Username, &i.AvatarUrl)
	return i, err
}

const incrementTicketsSold = `-- name: IncrementTicketsSold :exec
UPDATE raffles SET tickets_sold = tickets_sold + $1::int, updated_at = NOW() WHERE id = $2
`

type IncrementTicketsSoldParams struct {
	N  int32
	ID uuid.UUID
}

func (q *Queries) IncrementTicketsSold(ctx context.Context, arg IncrementTicketsSoldParams) error {
	_, err := q.db.Exec(ctx, incrementTicketsSold, arg.N, arg.ID)
	return err
}

const insertRaffleTicket = `-- name: InsertRaffleTicket :one
INSERT INTO raffle_tickets (raffle_id, user_id, ticket_number)
VALUES ($1, $2, $3::text)
RETURNING id, purchased_at
`

type InsertRaffleTicketParams struct {
	RaffleID     uuid.UUID
	UserID       uuid.UUID
	TicketNumber string
}

type InsertRaffleTicketRow struct {
	ID          uuid.UUID
	PurchasedAt time.Time
}

func (q *Queries) InsertRaffleTicket(ctx context.Context, arg InsertRaffleTicketParams) (InsertRaffleTicketRow, error) {
	row := q.db.QueryRow(ctx, insertRaffleTicket, arg.RaffleID, arg.UserID, arg.TicketNumber)
	var i InsertRaffleTicketRow
	err := row.Scan(&i.ID, &i.PurchasedAt)
	return i, err
}

const insertRaffleWinner = `-- name: InsertRaffleWinner :one
INSERT INTO raffle_winners (raffle_id, user_id, rank, prize_amount, prize_description, ticket_number)
VALUES ($1, $2, $4::int, $3, NULLIF($5::text, ''), $6::text)
RETURNING id
`

type InsertRaffleWinnerParams struct {
	RaffleID         uuid.UUID
	UserID           uuid.UUID
	PrizeAmount      int64
	Rank             int32
	PrizeDescription string
	TicketNumber     string
}

func (q *Queries) InsertRaffleWinner(ctx context.Context, arg InsertRaffleWinnerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRaffleWinner,
		arg.RaffleID,
		arg.UserID,
		arg.PrizeAmount,
		arg.Rank,
		arg.PrizeDescription,
		arg.TicketNumber,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAllRaffleTickets = `-- name: ListAllRaffleTickets :many
SELECT id, user_id, ticket_number FROM raffle_tickets WHERE raffle_id = $1
`

type ListAllRaffleTicketsRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	TicketNumber string
}

func (q *Queries) ListAllRaffleTickets(ctx context.Context, raffleID uuid.UUID) ([]ListAllRaffleTicketsRow, error) {
	rows, err := q.db.Query(ctx, listAllRaffleTickets, raffleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRaffleTicketsRow{}
	for rows.Next() {
		var i ListAllRaffleTicketsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.TicketNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueRaffles = `-- name: ListDueRaffles :many
SELECT id, guild_id FROM raffles
WHERE status IN ('active', 'upcoming') AND draw_date <= NOW()
ORDER BY draw_date ASC
LIMIT $1::int
`

type ListDueRafflesRow struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) ListDueRaffles(ctx context.Context, maxRows int32) ([]ListDueRafflesRow, error) {
	rows, err := q.db.Query(ctx, listDueRaffles, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueRafflesRow{}
	for rows.Next() {
		var i ListDueRafflesRow
		if err := rows.Scan(&i.ID, &i.GuildID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaffleTicketHolders = `-- name: ListRaffleTicketHolders :many
SELECT user_id, COUNT(*)::int AS tickets
FROM raffle_tickets WHERE raffle_id = $1
GROUP BY user_id
ORDER BY user_id
`

type ListRaffleTicketHoldersRow struct {
	UserID  uuid.UUID
	Tickets int32
}

func (q *Queries) ListRaffleTicketHolders(ctx context.Context, raffleID uuid.UUID) ([]ListRaffleTicketHoldersRow, error) {
	rows, err := q.db.Query(ctx, listRaffleTicketHolders, raffleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRaffleTicketHoldersRow{}
	for rows.Next() {
		var i ListRaffleTicketHoldersRow
		if err := rows.Scan(&i.UserID, &i.Tickets); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaffleWinners = `-- name: ListRaffleWinners :many
SELECT lw.id, lw.raffle_id, lw.user_id,
       COALESCE(member_display_name(l.guild_id, lw.user_id), '')::text AS username,
       COALESCE(u.avatar_url, '') AS avatar_url,
       lw.rank, lw.prize_amount,
       COALESCE(lw.prize_description, '') AS prize_description,
       lw.ticket_number
FROM raffle_winners lw
JOIN raffles l ON l.id = lw.raffle_id
LEFT JOIN users u ON u.id = lw.user_id
WHERE lw.raffle_id = $1
ORDER BY lw.rank ASC
`

type ListRaffleWinnersRow struct {
	ID               uuid.UUID
	RaffleID         uuid.UUID
	UserID           uuid.UUID
	Username         string
	AvatarUrl        string
	Rank             int32
	PrizeAmount      int64
	PrizeDescription string
	TicketNumber     string
}

func (q *Queries) ListRaffleWinners(ctx context.Context, raffleID uuid.UUID) ([]ListRaffleWinnersRow, error) {
	rows, err := q.db.Query(ctx, listRaffleWinners, raffleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRaffleWinnersRow{}
	for rows.Next() {
		var i ListRaffleWinnersRow
		if err := rows.Scan(
			&i.ID,
			&i.RaffleID,
			&i.UserID,
			&i.Username,
			&i.AvatarUrl,
			&i.Rank,
			&i.PrizeAmount,
			&i.PrizeDescription,
			&i.TicketNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaffles = `-- name: ListRaffles :many
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       ticket_price, tickets_sold,
       max_tickets, max_tickets_per_user, status,
       TO_CHAR(draw_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS draw_date,
       prizes, created_at, updated_at, cancelled_at
FROM raffles
WHERE guild_id = $1
  AND ($2::text = '' OR status = $2::text)
ORDER BY created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListRafflesParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListRafflesRow struct {
	ID                uuid.UUID
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	Description       string
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          string
	Prizes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CancelledAt       pgtype.Timestamptz
}

func (q *Queries) ListRaffles(ctx context.Context, arg ListRafflesParams) ([]ListRafflesRow, error) {
	rows, err := q.db.Query(ctx, listRaffles,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRafflesRow{}
	for rows.Next() {
		var i ListRafflesRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.TicketPrice,
			&i.TicketsSold,
			&i.MaxTickets,
			&i.MaxTicketsPerUser,
			&i.Status,
			&i.DrawDate,
			&i.Prizes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTickets = `-- name: ListUserTickets :many
SELECT lt.id, lt.raffle_id, lt.user_id, lt.ticket_number, lt.purchased_at
FROM raffle_tickets lt
JOIN raffles l ON l.id = lt.raffle_id
WHERE lt.user_id = $1
  AND ($2::text = '' OR l.guild_id::text = $2::text)
ORDER BY lt.purchased_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListUserTicketsParams struct {
	UserID      uuid.UUID
	GuildFilter string
	PageOffset  int32
	PageSize    int32
}

func (q *Queries) ListUserTickets(ctx context.Context, arg ListUserTicketsParams) ([]RaffleTicket, error) {
	rows, err := q.db.Query(ctx, listUserTickets,
		arg.UserID,
		arg.GuildFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RaffleTicket{}
	for rows.Next() {
		var i RaffleTicket
		if err := rows.Scan(
			&i.ID,
			&i.RaffleID,
			&i.UserID,
			&i.TicketNumber,
			&i.PurchasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRaffle = `-- name: LockRaffle :one
SELECT id, created_by, title, ticket_price, tickets_sold, max_tickets,
       max_tickets_per_user, status, draw_date, prizes
FROM raffles WHERE id = $1 AND guild_id = $2
FOR UPDATE
`

type LockRaffleParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type LockRaffleRow struct {
	ID                uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          time.Time
	Prizes            []byte
}

func (q *Queries) LockRaffle(ctx context.Context, arg LockRaffleParams) (LockRaffleRow, error) {
	row := q.db.QueryRow(ctx, lockRaffle, arg.ID, arg.GuildID)
	var i LockRaffleRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.TicketPrice,
		&i.TicketsSold,
		&i.MaxTickets,
		&i.MaxTicketsPerUser,
		&i.Status,
		&i.DrawDate,
		&i.Prizes,
	)
	return i, err
}

const lockRaffleForPurchase = `-- name: LockRaffleForPurchase :one
SELECT ticket_price, status, max_tickets, max_tickets_per_user, tickets_sold, draw_date
FROM raffles WHERE id = $1 AND guild_id = $2
FOR UPDATE
`

type LockRaffleForPurchaseParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type LockRaffleForPurchaseRow struct {
	TicketPrice       int64
	Status            string
	MaxTickets        int32
	MaxTicketsPerUser int32
	TicketsSold       int32
	DrawDate          time.Time
}

func (q *Queries) LockRaffleForPurchase(ctx context.Context, arg LockRaffleForPurchaseParams) (LockRaffleForPurchaseRow, error) {
	row := q.db.QueryRow(ctx, lockRaffleForPurchase, arg.ID, arg.GuildID)
	var i LockRaffleForPurchaseRow
	err := row.Scan(
		&i.TicketPrice,
		&i.Status,
		&i.MaxTickets,
		&i.MaxTicketsPerUser,
		&i.TicketsSold,
		&i.DrawDate,
	)
	return i, err
}

const markRaffleCancelled = `-- name: MarkRaffleCancelled :exec
UPDATE raffles SET status = 'cancelled', cancelled_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRaffleCancelled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRaffleCancelled, id)
	return err
}

const raffleExists = `-- name: RaffleExists :one
SELECT EXISTS(SELECT 1 FROM raffles WHERE id = $1 AND guild_id = $2)
`

type RaffleExistsParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) RaffleExists(ctx context.Context, arg RaffleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, raffleExists, arg.ID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRaffle = `-- name: UpdateRaffle :one
UPDATE raffles SET
    title                = $1::text,
    description          = CASE WHEN $2::bool
                                THEN NULLIF($3::text, '')
                                ELSE description END,
    ticket_price         = $4,
    max_tickets          = $5,
    max_tickets_per_user = $6,
    draw_date            = $7,
    updated_at           = NOW()
WHERE id = $8 AND guild_id = $9
  AND status IN ('active', 'upcoming')
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          ticket_price, tickets_sold,
          max_tickets, max_tickets_per_user, status,
          TO_CHAR(draw_date AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS draw_date,
          prizes, created_at, updated_at, cancelled_at
`

type UpdateRaffleParams struct {
	Title             string
	SetDescription    bool
	Description       string
	TicketPrice       int64
	MaxTickets        int32
	MaxTicketsPerUser int32
	DrawDate          time.Time
	ID                uuid.UUID
	GuildID           uuid.UUID
}

type UpdateRaffleRow struct {
	ID                uuid.UUID
	GuildID           uuid.UUID
	CreatedBy         uuid.UUID
	Title             string
	Description       string
	TicketPrice       int64
	TicketsSold       int32
	MaxTickets        int32
	MaxTicketsPerUser int32
	Status            string
	DrawDate          string
	Prizes            []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CancelledAt       pgtype.Timestamptz
}

func (q *Queries) UpdateRaffle(ctx context.Context, arg UpdateRaffleParams) (UpdateRaffleRow, error) {
	row := q.db.QueryRow(ctx, updateRaffle,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.TicketPrice,
		arg.MaxTickets,
		arg.MaxTicketsPerUser,
		arg.DrawDate,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateRaffleRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.TicketPrice,
		&i.TicketsSold,
		&i.MaxTickets,
		&i.MaxTicketsPerUser,
		&i.Status,
		&i.DrawDate,
		&i.Prizes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}
