// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roll_call.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRollCallGoldPotDistributed = `-- name: AddRollCallGoldPotDistributed :one
UPDATE roll_call_gold_pots SET
    distributed = distributed + $1::bigint,
    updated_at  = NOW()
WHERE roll_call_id = $2 AND guild_id = $3
  AND retracted = 0
  AND distributed + $1::bigint <= total
RETURNING roll_call_id, guild_id, total, distributed, retracted
`

type AddRollCallGoldPotDistributedParams struct {
	Amount     int64
	RollCallID uuid.UUID
	GuildID    uuid.UUID
}

type AddRollCallGoldPotDistributedRow struct {
	RollCallID  uuid.UUID
	GuildID     uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) AddRollCallGoldPotDistributed(ctx context.Context, arg AddRollCallGoldPotDistributedParams) (AddRollCallGoldPotDistributedRow, error) {
	row := q.db.QueryRow(ctx, addRollCallGoldPotDistributed, arg.Amount, arg.RollCallID, arg.GuildID)
	var i AddRollCallGoldPotDistributedRow
	err := row.Scan(
		&i.RollCallID,
		&i.GuildID,
		&i.Total,
		&i.Distributed,
		&i.Retracted,
	)
	return i, err
}

const cancelRollCall = `-- name: CancelRollCall :one
UPDATE roll_calls SET cancelled_at = NOW(), updated_at = NOW()
WHERE id = $1 AND guild_id = $2 AND cancelled_at IS NULL AND expire_time >= NOW()
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          (completed_at IS NOT NULL)::bool AS is_completed,
          completed_at,
          created_at, updated_at
`

type CancelRollCallParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type CancelRollCallRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CancelRollCall(ctx context.Context, arg CancelRollCallParams) (CancelRollCallRow, error) {
	row := q.db.QueryRow(ctx, cancelRollCall, arg.ID, arg.GuildID)
	var i CancelRollCallRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeRollCall = `-- name: CompleteRollCall :one
UPDATE roll_calls SET completed_at = NOW(), completed_by = $1, updated_at = NOW()
WHERE id = $2 AND guild_id = $3
  AND cancelled_at IS NULL AND completed_at IS NULL AND expire_time < NOW()
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          (completed_at IS NOT NULL)::bool AS is_completed,
          completed_at,
          created_at, updated_at
`

type CompleteRollCallParams struct {
	CompletedBy *uuid.UUID
	ID          uuid.UUID
	GuildID     uuid.UUID
}

type CompleteRollCallRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CompleteRollCall(ctx context.Context, arg CompleteRollCallParams) (CompleteRollCallRow, error) {
	row := q.db.QueryRow(ctx, completeRollCall, arg.CompletedBy, arg.ID, arg.GuildID)
	var i CompleteRollCallRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countRollCallAttendees = `-- name: CountRollCallAttendees :one
SELECT COUNT(*) FROM roll_call_attendees WHERE roll_call_id = $1
`

func (q *Queries) CountRollCallAttendees(ctx context.Context, rollCallID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRollCallAttendees, rollCallID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRollCallAttendeesAmong = `-- name: CountRollCallAttendeesAmong :one
SELECT COUNT(*) FROM roll_call_attendees
WHERE roll_call_id = $1 AND user_id = ANY($2::uuid[])
`

type CountRollCallAttendeesAmongParams struct {
	RollCallID uuid.UUID
	UserIds    []uuid.UUID
}

func (q *Queries) CountRollCallAttendeesAmong(ctx context.Context, arg CountRollCallAttendeesAmongParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRollCallAttendeesAmong, arg.RollCallID, arg.UserIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRollCallBankItems = `-- name: CountRollCallBankItems :one
SELECT COUNT(*) FROM bank_items
WHERE bank_items.roll_call_id = $1::uuid AND bank_items.guild_id = $2
`

type CountRollCallBankItemsParams struct {
	RollCallID uuid.UUID
	GuildID    uuid.UUID
}

func (q *Queries) CountRollCallBankItems(ctx context.Context, arg CountRollCallBankItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRollCallBankItems, arg.RollCallID, arg.GuildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRollCalls = `-- name: CountRollCalls :one
SELECT COUNT(*) FROM roll_calls WHERE guild_id = $1
  AND CASE
    WHEN $2::text = 'active'    THEN cancelled_at IS NULL AND expire_time >= NOW()
    WHEN $2::text = 'expired'   THEN cancelled_at IS NULL AND completed_at IS NULL AND expire_time < NOW()
    WHEN $2::text = 'cancelled' THEN cancelled_at IS NOT NULL
    WHEN $2::text = 'completed' THEN completed_at IS NOT NULL
    ELSE true
  END
`

type CountRollCallsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
}

func (q *Queries) CountRollCalls(ctx context.Context, arg CountRollCallsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRollCalls, arg.GuildID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRollCall = `-- name: CreateRollCall :one
INSERT INTO roll_calls (guild_id, created_by, title, description, datetime, expire_time, image_url, loot_list)
VALUES (
    $1, $2, $3::text,
    NULLIF($4::text, ''),
    $5::text::timestamptz,
    $6::text::timestamptz,
    NULLIF($7::text, ''),
    $8::jsonb
)
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          (completed_at IS NOT NULL)::bool AS is_completed,
          completed_at,
          created_at, updated_at
`

type CreateRollCallParams struct {
	GuildID     uuid.UUID
	CreatedBy   uuid.UUID
	Title       string
	Description string
	Datetime    string
	ExpireTime  string
	ImageUrl    string
	LootList    []byte
}

type CreateRollCallRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateRollCall(ctx context.Context, arg CreateRollCallParams) (CreateRollCallRow, error) {
	row := q.db.QueryRow(ctx, createRollCall,
		arg.GuildID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Datetime,
		arg.ExpireTime,
		arg.ImageUrl,
		arg.LootList,
	)
	var i CreateRollCallRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRollCall = `-- name: DeleteRollCall :execrows
DELETE FROM roll_calls WHERE id = $1 AND guild_id = $2
`

type DeleteRollCallParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteRollCall(ctx context.Context, arg DeleteRollCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRollCall, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRollCall = `-- name: GetRollCall :one
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
       TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
       COALESCE(image_url, '') AS image_url,
       loot_list, attendance_count,
       (expire_time < NOW())::bool AS is_expired,
       (cancelled_at IS NOT NULL)::bool AS is_cancelled,
       (completed_at IS NOT NULL)::bool AS is_completed,
       completed_at,
       created_at, updated_at
FROM roll_calls WHERE id = $1 AND guild_id = $2
`

type GetRollCallParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetRollCallRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetRollCall(ctx context.Context, arg GetRollCallParams) (GetRollCallRow, error) {
	row := q.db.QueryRow(ctx, getRollCall, arg.ID, arg.GuildID)
	var i GetRollCallRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRollCallCheckInWindow = `-- name: GetRollCallCheckInWindow :one
SELECT expire_time, (cancelled_at IS NOT NULL)::bool AS is_cancelled
FROM roll_calls WHERE id = $1 AND guild_id = $2
`

type GetRollCallCheckInWindowParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetRollCallCheckInWindowRow struct {
	ExpireTime  time.Time
	IsCancelled bool
}

func (q *Queries) GetRollCallCheckInWindow(ctx context.Context, arg GetRollCallCheckInWindowParams) (GetRollCallCheckInWindowRow, error) {
	row := q.db.QueryRow(ctx, getRollCallCheckInWindow, arg.ID, arg.GuildID)
	var i GetRollCallCheckInWindowRow
	err := row.Scan(&i.ExpireTime, &i.IsCancelled)
	return i, err
}

const getRollCallGoldDistributionByRequest = `-- name: GetRollCallGoldDistributionByRequest :one
SELECT id, total, created_at
FROM roll_call_gold_distributions
WHERE roll_call_id = $1 AND request_id = $2
`

type GetRollCallGoldDistributionByRequestParams struct {
	RollCallID uuid.UUID
	RequestID  uuid.UUID
}

type GetRollCallGoldDistributionByRequestRow struct {
	ID        uuid.UUID
	Total     int64
	CreatedAt time.Time
}

func (q *Queries) GetRollCallGoldDistributionByRequest(ctx context.Context, arg GetRollCallGoldDistributionByRequestParams) (GetRollCallGoldDistributionByRequestRow, error) {
	row := q.db.QueryRow(ctx, getRollCallGoldDistributionByRequest, arg.RollCallID, arg.RequestID)
	var i GetRollCallGoldDistributionByRequestRow
	err := row.Scan(&i.ID, &i.Total, &i.CreatedAt)
	return i, err
}

const getRollCallGoldPot = `-- name: GetRollCallGoldPot :one
SELECT roll_call_id, guild_id, total, distributed, retracted
FROM roll_call_gold_pots
WHERE roll_call_id = $1 AND guild_id = $2
`

type GetRollCallGoldPotParams struct {
	RollCallID uuid.UUID
	GuildID    uuid.UUID
}

type GetRollCallGoldPotRow struct {
	RollCallID  uuid.UUID
	GuildID     uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) GetRollCallGoldPot(ctx context.Context, arg GetRollCallGoldPotParams) (GetRollCallGoldPotRow, error) {
	row := q.db.QueryRow(ctx, getRollCallGoldPot, arg.RollCallID, arg.GuildID)
	var i GetRollCallGoldPotRow
	err := row.Scan(
		&i.RollCallID,
		&i.GuildID,
		&i.Total,
		&i.Distributed,
		&i.Retracted,
	)
	return i, err
}

const getUserDisplayAndAvatar = `-- name: GetUserDisplayAndAvatar :one
SELECT COALESCE(member_display_name($1::uuid, id), '')::text AS display_name,
       COALESCE(avatar_url, '')                                                   AS avatar_url
FROM users WHERE id = $2
`

type GetUserDisplayAndAvatarParams struct {
	GuildID uuid.UUID
	UserID  uuid.UUID
}

type GetUserDisplayAndAvatarRow struct {
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) GetUserDisplayAndAvatar(ctx context.Context, arg GetUserDisplayAndAvatarParams) (GetUserDisplayAndAvatarRow, error) {
	row := q.db.QueryRow(ctx, getUserDisplayAndAvatar, arg.GuildID, arg.UserID)
	var i GetUserDisplayAndAvatarRow
	err := row.Scan(&i.DisplayName, &i.AvatarUrl)
	return i, err
}

const incrementRollCallAttendance = `-- name: IncrementRollCallAttendance :exec
UPDATE roll_calls SET attendance_count = attendance_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementRollCallAttendance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementRollCallAttendance, id)
	return err
}

const insertRollCallAttendee = `-- name: InsertRollCallAttendee :one
INSERT INTO roll_call_attendees (roll_call_id, user_id, display_name, avatar_url, notes)
VALUES ($1, $2, $3::text, $4::text, $5::text)
ON CONFLICT (roll_call_id, user_id) DO NOTHING
RETURNING id
`

type InsertRollCallAttendeeParams struct {
	RollCallID  uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	AvatarUrl   string
	Notes       string
}

func (q *Queries) InsertRollCallAttendee(ctx context.Context, arg InsertRollCallAttendeeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRollCallAttendee,
		arg.RollCallID,
		arg.UserID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Notes,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertRollCallBankItem = `-- name: InsertRollCallBankItem :exec
INSERT INTO bank_items (id, guild_id, donor_id, donor_name, item, roll_call_id)
VALUES ($1, $2, $3, $4::text, $5::jsonb, $6::uuid)
`

type InsertRollCallBankItemParams struct {
	ID         uuid.UUID
	GuildID    uuid.UUID
	DonorID    uuid.UUID
	DonorName  string
	Item       []byte
	RollCallID uuid.UUID
}

func (q *Queries) InsertRollCallBankItem(ctx context.Context, arg InsertRollCallBankItemParams) error {
	_, err := q.db.Exec(ctx, insertRollCallBankItem,
		arg.ID,
		arg.GuildID,
		arg.DonorID,
		arg.DonorName,
		arg.Item,
		arg.RollCallID,
	)
	return err
}

const insertRollCallGoldBankActivity = `-- name: InsertRollCallGoldBankActivity :exec
INSERT INTO bank_contributions (guild_id, user_id, username, amount, note, kind, roll_call_id, reference_type, reference_id)
VALUES ($1, $2, $3::text, $4::bigint,
        NULLIF($5::text, ''), $6::text, $7::uuid,
        NULLIF($8::text, ''), $9::uuid)
`

type InsertRollCallGoldBankActivityParams struct {
	GuildID       uuid.UUID
	UserID        uuid.UUID
	Username      string
	Amount        int64
	Note          string
	Kind          string
	RollCallID    uuid.UUID
	ReferenceType string
	ReferenceID   *uuid.UUID
}

func (q *Queries) InsertRollCallGoldBankActivity(ctx context.Context, arg InsertRollCallGoldBankActivityParams) error {
	_, err := q.db.Exec(ctx, insertRollCallGoldBankActivity,
		arg.GuildID,
		arg.UserID,
		arg.Username,
		arg.Amount,
		arg.Note,
		arg.Kind,
		arg.RollCallID,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	return err
}

const insertRollCallGoldDistribution = `-- name: InsertRollCallGoldDistribution :one
INSERT INTO roll_call_gold_distributions (roll_call_id, guild_id, actor_id, request_id, total)
VALUES ($1, $2, $3, $4, $5::bigint)
RETURNING id, created_at
`

type InsertRollCallGoldDistributionParams struct {
	RollCallID uuid.UUID
	GuildID    uuid.UUID
	ActorID    *uuid.UUID
	RequestID  uuid.UUID
	Total      int64
}

type InsertRollCallGoldDistributionRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertRollCallGoldDistribution(ctx context.Context, arg InsertRollCallGoldDistributionParams) (InsertRollCallGoldDistributionRow, error) {
	row := q.db.QueryRow(ctx, insertRollCallGoldDistribution,
		arg.RollCallID,
		arg.GuildID,
		arg.ActorID,
		arg.RequestID,
		arg.Total,
	)
	var i InsertRollCallGoldDistributionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertRollCallGoldPayout = `-- name: InsertRollCallGoldPayout :exec
INSERT INTO roll_call_gold_payouts (distribution_id, user_id, amount, transaction_id)
VALUES ($1, $2, $3::bigint, $4)
`

type InsertRollCallGoldPayoutParams struct {
	DistributionID uuid.UUID
	UserID         uuid.UUID
	Amount         int64
	TransactionID  *uuid.UUID
}

func (q *Queries) InsertRollCallGoldPayout(ctx context.Context, arg InsertRollCallGoldPayoutParams) error {
	_, err := q.db.Exec(ctx, insertRollCallGoldPayout,
		arg.DistributionID,
		arg.UserID,
		arg.Amount,
		arg.TransactionID,
	)
	return err
}

const insertRollCallGoldPot = `-- name: InsertRollCallGoldPot :exec
INSERT INTO roll_call_gold_pots (roll_call_id, guild_id, total)
VALUES ($1, $2, $3::bigint)
`

type InsertRollCallGoldPotParams struct {
	RollCallID uuid.UUID
	GuildID    uuid.UUID
	Total      int64
}

func (q *Queries) InsertRollCallGoldPot(ctx context.Context, arg InsertRollCallGoldPotParams) error {
	_, err := q.db.Exec(ctx, insertRollCallGoldPot, arg.RollCallID, arg.GuildID, arg.Total)
	return err
}

const insertRollCallLootContribution = `-- name: InsertRollCallLootContribution :exec
INSERT INTO bank_contributions (guild_id, user_id, username, amount, note, kind, items, roll_call_id)
VALUES ($1, $2, $3::text, $4::bigint, NULLIF($5::text, ''), 'roll_call_loot',
        $6::jsonb, $7::uuid)
`

type InsertRollCallLootContributionParams struct {
	GuildID    uuid.UUID
	UserID     uuid.UUID
	Username   string
	Amount     int64
	Note       string
	Items      []byte
	RollCallID uuid.UUID
}

func (q *Queries) InsertRollCallLootContribution(ctx context.Context, arg InsertRollCallLootContributionParams) error {
	_, err := q.db.Exec(ctx, insertRollCallLootContribution,
		arg.GuildID,
		arg.UserID,
		arg.Username,
		arg.Amount,
		arg.Note,
		arg.Items,
		arg.RollCallID,
	)
	return err
}

const isRollCallAttendee = `-- name: IsRollCallAttendee :one
SELECT EXISTS(SELECT 1 FROM roll_call_attendees WHERE roll_call_id = $1 AND user_id = $2)
`

type IsRollCallAttendeeParams struct {
	RollCallID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) IsRollCallAttendee(ctx context.Context, arg IsRollCallAttendeeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRollCallAttendee, arg.RollCallID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRollCallAttendees = `-- name: ListRollCallAttendees :many
SELECT ca.id, ca.roll_call_id, ca.user_id,
       COALESCE(NULLIF(member_display_name(c.guild_id, ca.user_id), ''), ca.display_name, '')::text AS display_name,
       COALESCE(NULLIF(u.avatar_url, ''), ca.avatar_url, '')::text                        AS avatar_url,
       ca.notes,
       ca.checked_in_at
FROM roll_call_attendees ca
JOIN roll_calls c ON c.id = ca.roll_call_id
LEFT JOIN users u ON u.id = ca.user_id
WHERE ca.roll_call_id = $1
ORDER BY ca.checked_in_at ASC
LIMIT $3::int OFFSET $2::int
`

type ListRollCallAttendeesParams struct {
	RollCallID uuid.UUID
	PageOffset int32
	PageSize   int32
}

type ListRollCallAttendeesRow struct {
	ID          uuid.UUID
	RollCallID  uuid.UUID
	UserID      uuid.UUID
	DisplayName string
	AvatarUrl   string
	Notes       string
	CheckedInAt time.Time
}

func (q *Queries) ListRollCallAttendees(ctx context.Context, arg ListRollCallAttendeesParams) ([]ListRollCallAttendeesRow, error) {
	rows, err := q.db.Query(ctx, listRollCallAttendees, arg.RollCallID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRollCallAttendeesRow{}
	for rows.Next() {
		var i ListRollCallAttendeesRow
		if err := rows.Scan(
			&i.ID,
			&i.RollCallID,
			&i.UserID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Notes,
			&i.CheckedInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollCallGoldDistributionPayouts = `-- name: ListRollCallGoldDistributionPayouts :many
SELECT user_id, amount
FROM roll_call_gold_payouts
WHERE distribution_id = $1
ORDER BY user_id
`

type ListRollCallGoldDistributionPayoutsRow struct {
	UserID uuid.UUID
	Amount int64
}

func (q *Queries) ListRollCallGoldDistributionPayouts(ctx context.Context, distributionID uuid.UUID) ([]ListRollCallGoldDistributionPayoutsRow, error) {
	rows, err := q.db.Query(ctx, listRollCallGoldDistributionPayouts, distributionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRollCallGoldDistributionPayoutsRow{}
	for rows.Next() {
		var i ListRollCallGoldDistributionPayoutsRow
		if err := rows.Scan(&i.UserID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollCallGoldPots = `-- name: ListRollCallGoldPots :many
SELECT roll_call_id, total, distributed, retracted
FROM roll_call_gold_pots
WHERE guild_id = $1 AND roll_call_id = ANY($2::uuid[])
`

type ListRollCallGoldPotsParams struct {
	GuildID     uuid.UUID
	RollCallIds []uuid.UUID
}

type ListRollCallGoldPotsRow struct {
	RollCallID  uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) ListRollCallGoldPots(ctx context.Context, arg ListRollCallGoldPotsParams) ([]ListRollCallGoldPotsRow, error) {
	rows, err := q.db.Query(ctx, listRollCallGoldPots, arg.GuildID, arg.RollCallIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRollCallGoldPotsRow{}
	for rows.Next() {
		var i ListRollCallGoldPotsRow
		if err := rows.Scan(
			&i.RollCallID,
			&i.Total,
			&i.Distributed,
			&i.Retracted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollCallGoldRecipients = `-- name: ListRollCallGoldRecipients :many
SELECT p.user_id, SUM(p.amount)::bigint AS amount
FROM roll_call_gold_payouts p
JOIN roll_call_gold_distributions d ON d.id = p.distribution_id
WHERE d.roll_call_id = $1 AND d.guild_id = $2
GROUP BY p.user_id
ORDER BY p.user_id
`

type ListRollCallGoldRecipientsParams struct {
	RollCallID uuid.UUID
	GuildID    uuid.UUID
}

type ListRollCallGoldRecipientsRow struct {
	UserID uuid.UUID
	Amount int64
}

func (q *Queries) ListRollCallGoldRecipients(ctx context.Context, arg ListRollCallGoldRecipientsParams) ([]ListRollCallGoldRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listRollCallGoldRecipients, arg.RollCallID, arg.GuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRollCallGoldRecipientsRow{}
	for rows.Next() {
		var i ListRollCallGoldRecipientsRow
		if err := rows.Scan(&i.UserID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollCalls = `-- name: ListRollCalls :many
SELECT id, guild_id, created_by, title,
       COALESCE(description, '') AS description,
       TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
       TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
       COALESCE(image_url, '') AS image_url,
       loot_list, attendance_count,
       (expire_time < NOW())::bool AS is_expired,
       (cancelled_at IS NOT NULL)::bool AS is_cancelled,
       (completed_at IS NOT NULL)::bool AS is_completed,
       completed_at,
       created_at, updated_at
FROM roll_calls
WHERE guild_id = $1
  AND CASE
    WHEN $2::text = 'active'    THEN cancelled_at IS NULL AND expire_time >= NOW()
    WHEN $2::text = 'expired'   THEN cancelled_at IS NULL AND completed_at IS NULL AND expire_time < NOW()
    WHEN $2::text = 'cancelled' THEN cancelled_at IS NOT NULL
    WHEN $2::text = 'completed' THEN completed_at IS NOT NULL
    ELSE true
  END
ORDER BY datetime DESC
LIMIT $4::int OFFSET $3::int
`

type ListRollCallsParams struct {
	GuildID      uuid.UUID
	StatusFilter string
	PageOffset   int32
	PageSize     int32
}

type ListRollCallsRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListRollCalls(ctx context.Context, arg ListRollCallsParams) ([]ListRollCallsRow, error) {
	rows, err := q.db.Query(ctx, listRollCalls,
		arg.GuildID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRollCallsRow{}
	for rows.Next() {
		var i ListRollCallsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Datetime,
			&i.ExpireTime,
			&i.ImageUrl,
			&i.LootList,
			&i.AttendanceCount,
			&i.IsExpired,
			&i.IsCancelled,
			&i.IsCompleted,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRollCallBankItems = `-- name: LockRollCallBankItems :many
SELECT bank_items.id, bank_items.item, (bank_items.locked_by_type IS NOT NULL)::bool AS is_locked
FROM bank_items
WHERE bank_items.roll_call_id = $1::uuid AND bank_items.guild_id = $2
FOR UPDATE
`

type LockRollCallBankItemsParams struct {
	RollCallID uuid.UUID
	GuildID    uuid.UUID
}

type LockRollCallBankItemsRow struct {
	ID       uuid.UUID
	Item     []byte
	IsLocked bool
}

func (q *Queries) LockRollCallBankItems(ctx context.Context, arg LockRollCallBankItemsParams) ([]LockRollCallBankItemsRow, error) {
	rows, err := q.db.Query(ctx, lockRollCallBankItems, arg.RollCallID, arg.GuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockRollCallBankItemsRow{}
	for rows.Next() {
		var i LockRollCallBankItemsRow
		if err := rows.Scan(&i.ID, &i.Item, &i.IsLocked); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRollCallGoldPot = `-- name: LockRollCallGoldPot :one
SELECT roll_call_id, guild_id, total, distributed, retracted
FROM roll_call_gold_pots
WHERE roll_call_id = $1 AND guild_id = $2
FOR UPDATE
`

type LockRollCallGoldPotParams struct {
	RollCallID uuid.UUID
	GuildID    uuid.UUID
}

type LockRollCallGoldPotRow struct {
	RollCallID  uuid.UUID
	GuildID     uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) LockRollCallGoldPot(ctx context.Context, arg LockRollCallGoldPotParams) (LockRollCallGoldPotRow, error) {
	row := q.db.QueryRow(ctx, lockRollCallGoldPot, arg.RollCallID, arg.GuildID)
	var i LockRollCallGoldPotRow
	err := row.Scan(
		&i.RollCallID,
		&i.GuildID,
		&i.Total,
		&i.Distributed,
		&i.Retracted,
	)
	return i, err
}

const lockRollCallState = `-- name: LockRollCallState :one
SELECT title, (expire_time < NOW())::bool AS is_expired,
       (cancelled_at IS NOT NULL)::bool AS is_cancelled,
       (completed_at IS NOT NULL)::bool AS is_completed,
       loot_list
FROM roll_calls WHERE id = $1 AND guild_id = $2
FOR UPDATE
`

type LockRollCallStateParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type LockRollCallStateRow struct {
	Title       string
	IsExpired   bool
	IsCancelled bool
	IsCompleted bool
	LootList    []byte
}

func (q *Queries) LockRollCallState(ctx context.Context, arg LockRollCallStateParams) (LockRollCallStateRow, error) {
	row := q.db.QueryRow(ctx, lockRollCallState, arg.ID, arg.GuildID)
	var i LockRollCallStateRow
	err := row.Scan(
		&i.Title,
		&i.IsExpired,
		&i.IsCancelled,
		&i.IsCompleted,
		&i.LootList,
	)
	return i, err
}

const logRemovedRollCallLoot = `-- name: LogRemovedRollCallLoot :exec
INSERT INTO item_events (guild_id, item_id, kind, actor_id, source, reference_id)
SELECT bi.guild_id, bi.id, 'retracted', $1::uuid, 'roll_call', bi.roll_call_id
FROM bank_items bi
WHERE bi.id = ANY($2::uuid[]) AND bi.guild_id = $3
  AND bi.roll_call_id = $4::uuid AND bi.locked_by_type IS NULL
`

type LogRemovedRollCallLootParams struct {
	ActorID    uuid.UUID
	Ids        []uuid.UUID
	GuildID    uuid.UUID
	RollCallID uuid.UUID
}

func (q *Queries) LogRemovedRollCallLoot(ctx context.Context, arg LogRemovedRollCallLootParams) error {
	_, err := q.db.Exec(ctx, logRemovedRollCallLoot,
		arg.ActorID,
		arg.Ids,
		arg.GuildID,
		arg.RollCallID,
	)
	return err
}

const logRetractedRollCallLoot = `-- name: LogRetractedRollCallLoot :exec
INSERT INTO item_events (guild_id, item_id, kind, actor_id, source, reference_id)
SELECT bi.guild_id, bi.id, 'retracted', $1::uuid, 'roll_call', bi.roll_call_id
FROM bank_items bi
WHERE bi.roll_call_id = $2 AND bi.guild_id = $3 AND bi.locked_by_type IS NULL
`

type LogRetractedRollCallLootParams struct {
	ActorID    uuid.UUID
	RollCallID *uuid.UUID
	GuildID    uuid.UUID
}

func (q *Queries) LogRetractedRollCallLoot(ctx context.Context, arg LogRetractedRollCallLootParams) error {
	_, err := q.db.Exec(ctx, logRetractedRollCallLoot, arg.ActorID, arg.RollCallID, arg.GuildID)
	return err
}

const rejectPendingRequestsForLootItem = `-- name: RejectPendingRequestsForLootItem :execrows
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    review_note = NULLIF($2::text, ''),
    reviewed_at = NOW()
WHERE item_requests.guild_id = $3
  AND item_requests.bank_item_id = $4
  AND item_requests.status = 'pending'
`

type RejectPendingRequestsForLootItemParams struct {
	ReviewerID *uuid.UUID
	ReviewNote string
	GuildID    uuid.UUID
	BankItemID *uuid.UUID
}

func (q *Queries) RejectPendingRequestsForLootItem(ctx context.Context, arg RejectPendingRequestsForLootItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPendingRequestsForLootItem,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.GuildID,
		arg.BankItemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectPendingRequestsForLootItems = `-- name: RejectPendingRequestsForLootItems :execrows
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    review_note = NULLIF($2::text, ''),
    reviewed_at = NOW()
WHERE item_requests.guild_id = $3
  AND item_requests.status = 'pending'
  AND item_requests.bank_item_id = ANY($4::uuid[])
`

type RejectPendingRequestsForLootItemsParams struct {
	ReviewerID  *uuid.UUID
	ReviewNote  string
	GuildID     uuid.UUID
	BankItemIds []uuid.UUID
}

func (q *Queries) RejectPendingRequestsForLootItems(ctx context.Context, arg RejectPendingRequestsForLootItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPendingRequestsForLootItems,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.GuildID,
		arg.BankItemIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectPendingRequestsForRollCallLoot = `-- name: RejectPendingRequestsForRollCallLoot :execrows
UPDATE item_requests SET
    status = 'rejected',
    reviewer_id = $1,
    review_note = NULLIF($2::text, ''),
    reviewed_at = NOW()
WHERE item_requests.guild_id = $3
  AND item_requests.status = 'pending'
  AND item_requests.bank_item_id IN (
      SELECT bi.id FROM bank_items bi
      WHERE bi.roll_call_id = $4 AND bi.guild_id = $3
  )
`

type RejectPendingRequestsForRollCallLootParams struct {
	ReviewerID *uuid.UUID
	ReviewNote string
	GuildID    uuid.UUID
	RollCallID *uuid.UUID
}

func (q *Queries) RejectPendingRequestsForRollCallLoot(ctx context.Context, arg RejectPendingRequestsForRollCallLootParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPendingRequestsForRollCallLoot,
		arg.ReviewerID,
		arg.ReviewNote,
		arg.GuildID,
		arg.RollCallID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeRollCallLoot = `-- name: RemoveRollCallLoot :execrows
DELETE FROM bank_items
WHERE bank_items.id = ANY($1::uuid[]) AND bank_items.guild_id = $2
  AND bank_items.roll_call_id = $3::uuid AND bank_items.locked_by_type IS NULL
`

type RemoveRollCallLootParams struct {
	Ids        []uuid.UUID
	GuildID    uuid.UUID
	RollCallID uuid.UUID
}

func (q *Queries) RemoveRollCallLoot(ctx context.Context, arg RemoveRollCallLootParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeRollCallLoot, arg.Ids, arg.GuildID, arg.RollCallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retractRollCallGoldPot = `-- name: RetractRollCallGoldPot :one
UPDATE roll_call_gold_pots SET
    retracted  = total - distributed,
    updated_at = NOW()
WHERE roll_call_id = $1 AND guild_id = $2 AND retracted = 0 AND distributed < total
RETURNING roll_call_id, guild_id, total, distributed, retracted
`

type RetractRollCallGoldPotParams struct {
	RollCallID uuid.UUID
	GuildID    uuid.UUID
}

type RetractRollCallGoldPotRow struct {
	RollCallID  uuid.UUID
	GuildID     uuid.UUID
	Total       int64
	Distributed int64
	Retracted   int64
}

func (q *Queries) RetractRollCallGoldPot(ctx context.Context, arg RetractRollCallGoldPotParams) (RetractRollCallGoldPotRow, error) {
	row := q.db.QueryRow(ctx, retractRollCallGoldPot, arg.RollCallID, arg.GuildID)
	var i RetractRollCallGoldPotRow
	err := row.Scan(
		&i.RollCallID,
		&i.GuildID,
		&i.Total,
		&i.Distributed,
		&i.Retracted,
	)
	return i, err
}

const retractRollCallLoot = `-- name: RetractRollCallLoot :execrows
DELETE FROM bank_items
WHERE roll_call_id = $1 AND guild_id = $2 AND locked_by_type IS NULL
`

type RetractRollCallLootParams struct {
	RollCallID *uuid.UUID
	GuildID    uuid.UUID
}

func (q *Queries) RetractRollCallLoot(ctx context.Context, arg RetractRollCallLootParams) (int64, error) {
	result, err := q.db.Exec(ctx, retractRollCallLoot, arg.RollCallID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rollCallExists = `-- name: RollCallExists :one
SELECT EXISTS(SELECT 1 FROM roll_calls WHERE id = $1 AND guild_id = $2)
`

type RollCallExistsParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) RollCallExists(ctx context.Context, arg RollCallExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, rollCallExists, arg.ID, arg.GuildID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setRollCallLootList = `-- name: SetRollCallLootList :one
UPDATE roll_calls SET loot_list = $1::jsonb, updated_at = NOW()
WHERE id = $2 AND guild_id = $3
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          (completed_at IS NOT NULL)::bool AS is_completed,
          completed_at,
          created_at, updated_at
`

type SetRollCallLootListParams struct {
	LootList []byte
	ID       uuid.UUID
	GuildID  uuid.UUID
}

type SetRollCallLootListRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) SetRollCallLootList(ctx context.Context, arg SetRollCallLootListParams) (SetRollCallLootListRow, error) {
	row := q.db.QueryRow(ctx, setRollCallLootList, arg.LootList, arg.ID, arg.GuildID)
	var i SetRollCallLootListRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const takeRollCallLootItem = `-- name: TakeRollCallLootItem :one
DELETE FROM bank_items
WHERE bank_items.id = $1 AND bank_items.guild_id = $2 AND bank_items.roll_call_id = $3
  AND bank_items.locked_by_type IS NULL
RETURNING bank_items.item
`

type TakeRollCallLootItemParams struct {
	ID         uuid.UUID
	GuildID    uuid.UUID
	RollCallID *uuid.UUID
}

func (q *Queries) TakeRollCallLootItem(ctx context.Context, arg TakeRollCallLootItemParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, takeRollCallLootItem, arg.ID, arg.GuildID, arg.RollCallID)
	var item []byte
	err := row.Scan(&item)
	return item, err
}

const updateRollCall = `-- name: UpdateRollCall :one
UPDATE roll_calls SET
    title       = $1::text,
    description = CASE WHEN $2::bool THEN NULLIF($3::text, '') ELSE description END,
    datetime    = $4::text::timestamptz,
    expire_time = $5::text::timestamptz,
    image_url   = CASE WHEN $6::bool THEN NULLIF($7::text, '') ELSE image_url END,
    updated_at  = NOW()
WHERE id = $8 AND guild_id = $9
  AND cancelled_at IS NULL AND expire_time >= NOW()
RETURNING id, guild_id, created_by, title,
          COALESCE(description, '') AS description,
          TO_CHAR(datetime    AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS datetime,
          TO_CHAR(expire_time AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS expire_time,
          COALESCE(image_url, '') AS image_url,
          loot_list, attendance_count,
          (expire_time < NOW())::bool AS is_expired,
          (cancelled_at IS NOT NULL)::bool AS is_cancelled,
          (completed_at IS NOT NULL)::bool AS is_completed,
          completed_at,
          created_at, updated_at
`

type UpdateRollCallParams struct {
	Title          string
	SetDescription bool
	Description    string
	Datetime       string
	ExpireTime     string
	SetImageUrl    bool
	ImageUrl       string
	ID             uuid.UUID
	GuildID        uuid.UUID
}

type UpdateRollCallRow struct {
	ID              uuid.UUID
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Title           string
	Description     string
	Datetime        string
	ExpireTime      string
	ImageUrl        string
	LootList        []byte
	AttendanceCount int32
	IsExpired       bool
	IsCancelled     bool
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateRollCall(ctx context.Context, arg UpdateRollCallParams) (UpdateRollCallRow, error) {
	row := q.db.QueryRow(ctx, updateRollCall,
		arg.Title,
		arg.SetDescription,
		arg.Description,
		arg.Datetime,
		arg.ExpireTime,
		arg.SetImageUrl,
		arg.ImageUrl,
		arg.ID,
		arg.GuildID,
	)
	var i UpdateRollCallRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Datetime,
		&i.ExpireTime,
		&i.ImageUrl,
		&i.LootList,
		&i.AttendanceCount,
		&i.IsExpired,
		&i.IsCancelled,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRollCallBankItem = `-- name: UpdateRollCallBankItem :execrows
UPDATE bank_items SET item = $1::jsonb
WHERE bank_items.id = $2 AND bank_items.guild_id = $3
  AND bank_items.roll_call_id = $4::uuid AND bank_items.locked_by_type IS NULL
`

type UpdateRollCallBankItemParams struct {
	Item       []byte
	ID         uuid.UUID
	GuildID    uuid.UUID
	RollCallID uuid.UUID
}

func (q *Queries) UpdateRollCallBankItem(ctx context.Context, arg UpdateRollCallBankItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRollCallBankItem,
		arg.Item,
		arg.ID,
		arg.GuildID,
		arg.RollCallID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
