// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roll_call_template.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRollCallTemplate = `-- name: CreateRollCallTemplate :one
INSERT INTO roll_call_templates (guild_id, name, title, item_template_ids, created_by)
VALUES ($1, $3::text, $4::text, $5::uuid[], $2)
RETURNING id
`

type CreateRollCallTemplateParams struct {
	GuildID         uuid.UUID
	CreatedBy       uuid.UUID
	Name            string
	Title           string
	ItemTemplateIds []uuid.UUID
}

func (q *Queries) CreateRollCallTemplate(ctx context.Context, arg CreateRollCallTemplateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRollCallTemplate,
		arg.GuildID,
		arg.CreatedBy,
		arg.Name,
		arg.Title,
		arg.ItemTemplateIds,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteRollCallTemplate = `-- name: DeleteRollCallTemplate :execrows
DELETE FROM roll_call_templates WHERE id = $1 AND guild_id = $2
`

type DeleteRollCallTemplateParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteRollCallTemplate(ctx context.Context, arg DeleteRollCallTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRollCallTemplate, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRollCallTemplate = `-- name: GetRollCallTemplate :one
SELECT ct.id, ct.guild_id, ct.name, ct.title, ct.created_by, ct.created_at, ct.updated_at,
       (SELECT COALESCE(jsonb_agg(jsonb_build_object(
                   'id', it.id, 'name', it.name, 'description', it.description,
                   'category', it.category, 'rarity', it.rarity) ORDER BY u.ord), '[]'::jsonb)
        FROM unnest(ct.item_template_ids) WITH ORDINALITY AS u(item_id, ord)
        JOIN item_templates it ON it.id = u.item_id AND it.guild_id = ct.guild_id)::jsonb AS items
FROM roll_call_templates ct
WHERE ct.id = $1 AND ct.guild_id = $2
`

type GetRollCallTemplateParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type GetRollCallTemplateRow struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	Name      string
	Title     string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Items     []byte
}

func (q *Queries) GetRollCallTemplate(ctx context.Context, arg GetRollCallTemplateParams) (GetRollCallTemplateRow, error) {
	row := q.db.QueryRow(ctx, getRollCallTemplate, arg.ID, arg.GuildID)
	var i GetRollCallTemplateRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.Name,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Items,
	)
	return i, err
}

const listRollCallTemplates = `-- name: ListRollCallTemplates :many
SELECT ct.id, ct.guild_id, ct.name, ct.title, ct.created_by, ct.created_at, ct.updated_at,
       (SELECT COALESCE(jsonb_agg(jsonb_build_object(
                   'id', it.id, 'name', it.name, 'description', it.description,
                   'category', it.category, 'rarity', it.rarity) ORDER BY u.ord), '[]'::jsonb)
        FROM unnest(ct.item_template_ids) WITH ORDINALITY AS u(item_id, ord)
        JOIN item_templates it ON it.id = u.item_id AND it.guild_id = ct.guild_id)::jsonb AS items
FROM roll_call_templates ct
WHERE ct.guild_id = $1
ORDER BY ct.name ASC
`

type ListRollCallTemplatesRow struct {
	ID        uuid.UUID
	GuildID   uuid.UUID
	Name      string
	Title     string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Items     []byte
}

func (q *Queries) ListRollCallTemplates(ctx context.Context, guildID uuid.UUID) ([]ListRollCallTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listRollCallTemplates, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRollCallTemplatesRow{}
	for rows.Next() {
		var i ListRollCallTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.Name,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRollCallTemplate = `-- name: UpdateRollCallTemplate :one
UPDATE roll_call_templates SET
    name              = $1::text,
    title             = $2::text,
    item_template_ids = $3::uuid[],
    updated_at        = NOW()
WHERE id = $4 AND guild_id = $5
RETURNING id
`

type UpdateRollCallTemplateParams struct {
	Name            string
	Title           string
	ItemTemplateIds []uuid.UUID
	ID              uuid.UUID
	GuildID         uuid.UUID
}

func (q *Queries) UpdateRollCallTemplate(ctx context.Context, arg UpdateRollCallTemplateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateRollCallTemplate,
		arg.Name,
		arg.Title,
		arg.ItemTemplateIds,
		arg.ID,
		arg.GuildID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
