// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUserAuctionsWon = `-- name: CountUserAuctionsWon :one
SELECT COUNT(*) FROM auctions WHERE current_bidder_id = $1 AND status = 'ENDED'
`

func (q *Queries) CountUserAuctionsWon(ctx context.Context, currentBidderID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserAuctionsWon, currentBidderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserCheckins = `-- name: CountUserCheckins :one
SELECT COUNT(*) FROM checkin_attendees WHERE user_id = $1
`

func (q *Queries) CountUserCheckins(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserCheckins, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserEventsAttended = `-- name: CountUserEventsAttended :one
SELECT COUNT(*) FROM guild_events WHERE $1::uuid = ANY(participant_ids)
`

func (q *Queries) CountUserEventsAttended(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserEventsAttended, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserGuilds = `-- name: CountUserGuilds :one
SELECT COUNT(*) FROM members WHERE user_id = $1
`

func (q *Queries) CountUserGuilds(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserGuilds, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserLotteriesWon = `-- name: CountUserLotteriesWon :one
SELECT COUNT(*) FROM lottery_winners WHERE user_id = $1
`

func (q *Queries) CountUserLotteriesWon(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserLotteriesWon, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, username, display_name, avatar_url)
VALUES (
    $1,
    $2,
    $3,
    NULLIF($4::text, ''),
    NULLIF($5::text, '')
)
RETURNING id, email, username,
          COALESCE(display_name, '') AS display_name,
          COALESCE(bio, '')          AS bio,
          COALESCE(avatar_url, '')   AS avatar_url,
          created_at, updated_at
`

type CreateUserParams struct {
	ID          uuid.UUID
	Email       string
	Username    string
	DisplayName string
	AvatarUrl   string
}

type CreateUserRow struct {
	ID          uuid.UUID
	Email       string
	Username    string
	DisplayName string
	Bio         string
	AvatarUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username,
       COALESCE(display_name, '') AS display_name,
       COALESCE(bio, '')          AS bio,
       COALESCE(avatar_url, '')   AS avatar_url,
       created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          uuid.UUID
	Email       string
	Username    string
	DisplayName string
	Bio         string
	AvatarUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCurrentGuildBalance = `-- name: GetUserCurrentGuildBalance :one
SELECT m.guild_id,
       COALESCE(w.balance, 0)::bigint AS balance
FROM members m
LEFT JOIN wallets w ON w.user_id = m.user_id AND w.guild_id = m.guild_id
WHERE m.user_id = $1
ORDER BY m.last_active DESC
LIMIT 1
`

type GetUserCurrentGuildBalanceRow struct {
	GuildID uuid.UUID
	Balance int64
}

func (q *Queries) GetUserCurrentGuildBalance(ctx context.Context, userID uuid.UUID) (GetUserCurrentGuildBalanceRow, error) {
	row := q.db.QueryRow(ctx, getUserCurrentGuildBalance, userID)
	var i GetUserCurrentGuildBalanceRow
	err := row.Scan(&i.GuildID, &i.Balance)
	return i, err
}

const getUserPublicByID = `-- name: GetUserPublicByID :one
SELECT id, username,
       COALESCE(display_name, '') AS display_name,
       COALESCE(avatar_url, '')   AS avatar_url,
       created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserPublicByIDRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	AvatarUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUserPublicByID(ctx context.Context, id uuid.UUID) (GetUserPublicByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserPublicByID, id)
	var i GetUserPublicByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserGuildIDs = `-- name: ListUserGuildIDs :many
SELECT guild_id FROM members WHERE user_id = $1
`

func (q *Queries) ListUserGuildIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserGuildIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var guild_id uuid.UUID
		if err := rows.Scan(&guild_id); err != nil {
			return nil, err
		}
		items = append(items, guild_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username,
       COALESCE(display_name, '') AS display_name,
       COALESCE(avatar_url, '')   AS avatar_url,
       created_at
FROM users
ORDER BY created_at DESC
LIMIT $1
`

type ListUsersRow struct {
	ID          uuid.UUID
	Email       string
	Username    string
	DisplayName string
	AvatarUrl   string
	CreatedAt   time.Time
}

func (q *Queries) ListUsers(ctx context.Context, limit int32) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUserEarnedSpent = `-- name: SumUserEarnedSpent :one
SELECT
    COALESCE(SUM(CASE WHEN amount > 0 THEN amount       ELSE 0 END), 0)::bigint AS total_earned,
    COALESCE(SUM(CASE WHEN amount < 0 THEN ABS(amount)  ELSE 0 END), 0)::bigint AS total_spent
FROM transactions
WHERE user_id = $1
`

type SumUserEarnedSpentRow struct {
	TotalEarned int64
	TotalSpent  int64
}

func (q *Queries) SumUserEarnedSpent(ctx context.Context, userID uuid.UUID) (SumUserEarnedSpentRow, error) {
	row := q.db.QueryRow(ctx, sumUserEarnedSpent, userID)
	var i SumUserEarnedSpentRow
	err := row.Scan(&i.TotalEarned, &i.TotalSpent)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    display_name = CASE WHEN $1::text != '' THEN $1::text ELSE display_name END,
    username     = CASE WHEN $2::text     != '' THEN $2::text     ELSE username     END,
    bio          = CASE WHEN $3::text          != '' THEN $3::text          ELSE bio          END,
    avatar_url   = CASE WHEN $4::text   != '' THEN $4::text   ELSE avatar_url   END,
    updated_at   = NOW()
WHERE id = $5
RETURNING id, email, username,
          COALESCE(display_name, '') AS display_name,
          COALESCE(bio, '')          AS bio,
          COALESCE(avatar_url, '')   AS avatar_url,
          created_at, updated_at
`

type UpdateUserParams struct {
	DisplayName string
	Username    string
	Bio         string
	AvatarUrl   string
	ID          uuid.UUID
}

type UpdateUserRow struct {
	ID          uuid.UUID
	Email       string
	Username    string
	DisplayName string
	Bio         string
	AvatarUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.DisplayName,
		arg.Username,
		arg.Bio,
		arg.AvatarUrl,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserFromKratos = `-- name: UpsertUserFromKratos :one
INSERT INTO users (id, email, username, display_name, avatar_url)
VALUES (
    $1,
    $2,
    $3,
    NULLIF($4::text, ''),
    NULLIF($5::text, '')
)
ON CONFLICT (id) DO UPDATE SET
    email      = EXCLUDED.email,
    avatar_url = COALESCE(EXCLUDED.avatar_url, users.avatar_url),
    updated_at = NOW()
RETURNING id, email, username,
          COALESCE(display_name, '') AS display_name,
          COALESCE(bio, '')          AS bio,
          COALESCE(avatar_url, '')   AS avatar_url,
          created_at, updated_at
`

type UpsertUserFromKratosParams struct {
	ID          uuid.UUID
	Email       string
	Username    string
	DisplayName string
	AvatarUrl   string
}

type UpsertUserFromKratosRow struct {
	ID          uuid.UUID
	Email       string
	Username    string
	DisplayName string
	Bio         string
	AvatarUrl   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Inserts the users row on first touch, or refreshes Kratos-owned fields
// (email, avatar_url) if it already exists. Username/display_name/bio are
// app-editable and are preserved across updates so UpdateMe writes don't
// get clobbered by every GetMe call.
func (q *Queries) UpsertUserFromKratos(ctx context.Context, arg UpsertUserFromKratosParams) (UpsertUserFromKratosRow, error) {
	row := q.db.QueryRow(ctx, upsertUserFromKratos,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i UpsertUserFromKratosRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
