// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBackpackWithdrawal = `-- name: CancelBackpackWithdrawal :one
UPDATE backpack_items SET delivery_requested_at = NULL
WHERE id = $1 AND owner_id = $2 AND guild_id = $3 AND delivery_requested_at IS NOT NULL
RETURNING id, owner_id, guild_id, item, source, source_id,
          COALESCE(note, '') AS note, acquired_at, delivery_requested_at
`

type CancelBackpackWithdrawalParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	GuildID uuid.UUID
}

type CancelBackpackWithdrawalRow struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	GuildID             uuid.UUID
	Item                []byte
	Source              string
	SourceID            *uuid.UUID
	Note                string
	AcquiredAt          time.Time
	DeliveryRequestedAt pgtype.Timestamptz
}

func (q *Queries) CancelBackpackWithdrawal(ctx context.Context, arg CancelBackpackWithdrawalParams) (CancelBackpackWithdrawalRow, error) {
	row := q.db.QueryRow(ctx, cancelBackpackWithdrawal, arg.ID, arg.OwnerID, arg.GuildID)
	var i CancelBackpackWithdrawalRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GuildID,
		&i.Item,
		&i.Source,
		&i.SourceID,
		&i.Note,
		&i.AcquiredAt,
		&i.DeliveryRequestedAt,
	)
	return i, err
}

const countBackpackItems = `-- name: CountBackpackItems :one
SELECT COUNT(*) FROM backpack_items WHERE owner_id = $1 AND guild_id = $2
`

type CountBackpackItemsParams struct {
	OwnerID uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) CountBackpackItems(ctx context.Context, arg CountBackpackItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBackpackItems, arg.OwnerID, arg.GuildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWalletTransactions = `-- name: CountWalletTransactions :one
SELECT COUNT(*) FROM transactions
WHERE user_id = $1 AND guild_id = $2
  AND ($3::text = '' OR type = $3::text)
`

type CountWalletTransactionsParams struct {
	UserID     uuid.UUID
	GuildID    uuid.UUID
	TypeFilter string
}

func (q *Queries) CountWalletTransactions(ctx context.Context, arg CountWalletTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTransactions, arg.UserID, arg.GuildID, arg.TypeFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeliveredItem = `-- name: DeleteDeliveredItem :exec
DELETE FROM backpack_items WHERE id = $1 AND guild_id = $2 AND delivery_requested_at IS NOT NULL
`

type DeleteDeliveredItemParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) DeleteDeliveredItem(ctx context.Context, arg DeleteDeliveredItemParams) error {
	_, err := q.db.Exec(ctx, deleteDeliveredItem, arg.ID, arg.GuildID)
	return err
}

const ensureWallet = `-- name: EnsureWallet :exec
INSERT INTO wallets (user_id, guild_id, balance, currency)
VALUES ($1, $2, 0, 'gold')
ON CONFLICT (user_id, guild_id) DO NOTHING
`

type EnsureWalletParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) EnsureWallet(ctx context.Context, arg EnsureWalletParams) error {
	_, err := q.db.Exec(ctx, ensureWallet, arg.UserID, arg.GuildID)
	return err
}

const getWallet = `-- name: GetWallet :one
SELECT user_id, guild_id, balance, currency, created_at, updated_at
FROM wallets WHERE user_id = $1 AND guild_id = $2
`

type GetWalletParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) GetWallet(ctx context.Context, arg GetWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, arg.UserID, arg.GuildID)
	var i Wallet
	err := row.Scan(
		&i.UserID,
		&i.GuildID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletBalanceForUpdate = `-- name: GetWalletBalanceForUpdate :one
SELECT balance FROM wallets WHERE user_id = $1 AND guild_id = $2 FOR UPDATE
`

type GetWalletBalanceForUpdateParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) GetWalletBalanceForUpdate(ctx context.Context, arg GetWalletBalanceForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getWalletBalanceForUpdate, arg.UserID, arg.GuildID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (user_id, guild_id, type, amount, balance_after, description, reference_id, reference_type)
VALUES (
    $1, $2, $5::text, $3, $4,
    NULLIF($6::text, ''),
    NULLIF($7::text, '')::uuid,
    NULLIF($8::text, '')
)
RETURNING id
`

type InsertTransactionParams struct {
	UserID        uuid.UUID
	GuildID       uuid.UUID
	Amount        int64
	BalanceAfter  int64
	Type          string
	Description   string
	ReferenceID   string
	ReferenceType string
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.UserID,
		arg.GuildID,
		arg.Amount,
		arg.BalanceAfter,
		arg.Type,
		arg.Description,
		arg.ReferenceID,
		arg.ReferenceType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTransactionSimple = `-- name: InsertTransactionSimple :exec
INSERT INTO transactions (user_id, guild_id, type, amount, balance_after, description)
VALUES ($1, $2, $5::text, $3, $4, NULLIF($6::text, ''))
`

type InsertTransactionSimpleParams struct {
	UserID       uuid.UUID
	GuildID      uuid.UUID
	Amount       int64
	BalanceAfter int64
	Type         string
	Description  string
}

func (q *Queries) InsertTransactionSimple(ctx context.Context, arg InsertTransactionSimpleParams) error {
	_, err := q.db.Exec(ctx, insertTransactionSimple,
		arg.UserID,
		arg.GuildID,
		arg.Amount,
		arg.BalanceAfter,
		arg.Type,
		arg.Description,
	)
	return err
}

const listActiveLeadingBids = `-- name: ListActiveLeadingBids :many
SELECT id, COALESCE(item->>'name', '')::text AS item_name, current_bid, end_time
FROM auctions
WHERE guild_id = $1 AND current_bidder_id = $2 AND status IN ('UPCOMING', 'ACTIVE')
ORDER BY end_time ASC
`

type ListActiveLeadingBidsParams struct {
	GuildID         uuid.UUID
	CurrentBidderID *uuid.UUID
}

type ListActiveLeadingBidsRow struct {
	ID         uuid.UUID
	ItemName   string
	CurrentBid int64
	EndTime    time.Time
}

func (q *Queries) ListActiveLeadingBids(ctx context.Context, arg ListActiveLeadingBidsParams) ([]ListActiveLeadingBidsRow, error) {
	rows, err := q.db.Query(ctx, listActiveLeadingBids, arg.GuildID, arg.CurrentBidderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveLeadingBidsRow{}
	for rows.Next() {
		var i ListActiveLeadingBidsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemName,
			&i.CurrentBid,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackpackItems = `-- name: ListBackpackItems :many
SELECT bi.id, bi.owner_id, bi.guild_id, bi.item,
       bi.source, bi.source_id,
       COALESCE(bi.note, '') AS note,
       bi.acquired_at,
       bi.delivery_requested_at,
       COALESCE(
           CASE bi.source
               WHEN 'transfer' THEN member_display_name(bi.guild_id, bi.source_id)
               WHEN 'lottery'  THEN (SELECT l.title FROM lotteries l WHERE l.id = bi.source_id)
               WHEN 'checkin'  THEN (SELECT c.title FROM checkins c WHERE c.id = bi.source_id)
           END,
           ''
       )::text AS source_label,
       COALESCE(bi.locked_by_type, '') AS locked_by_type,
       bi.locked_by_id
FROM backpack_items bi
WHERE bi.owner_id = $1 AND bi.guild_id = $2
ORDER BY bi.acquired_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListBackpackItemsParams struct {
	OwnerID    uuid.UUID
	GuildID    uuid.UUID
	PageOffset int32
	PageSize   int32
}

type ListBackpackItemsRow struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	GuildID             uuid.UUID
	Item                []byte
	Source              string
	SourceID            *uuid.UUID
	Note                string
	AcquiredAt          time.Time
	DeliveryRequestedAt pgtype.Timestamptz
	SourceLabel         string
	LockedByType        string
	LockedByID          *uuid.UUID
}

func (q *Queries) ListBackpackItems(ctx context.Context, arg ListBackpackItemsParams) ([]ListBackpackItemsRow, error) {
	rows, err := q.db.Query(ctx, listBackpackItems,
		arg.OwnerID,
		arg.GuildID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackpackItemsRow{}
	for rows.Next() {
		var i ListBackpackItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.GuildID,
			&i.Item,
			&i.Source,
			&i.SourceID,
			&i.Note,
			&i.AcquiredAt,
			&i.DeliveryRequestedAt,
			&i.SourceLabel,
			&i.LockedByType,
			&i.LockedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT bi.id, bi.owner_id, bi.guild_id, bi.item, bi.source, bi.source_id,
       COALESCE(bi.note, '') AS note, bi.acquired_at, bi.delivery_requested_at,
       COALESCE(member_display_name(bi.guild_id, bi.owner_id), '')::text AS owner_name
FROM backpack_items bi
WHERE bi.guild_id = $1 AND bi.delivery_requested_at IS NOT NULL
ORDER BY bi.delivery_requested_at, bi.id
LIMIT 200
`

type ListPendingDeliveriesRow struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	GuildID             uuid.UUID
	Item                []byte
	Source              string
	SourceID            *uuid.UUID
	Note                string
	AcquiredAt          time.Time
	DeliveryRequestedAt pgtype.Timestamptz
	OwnerName           string
}

func (q *Queries) ListPendingDeliveries(ctx context.Context, guildID uuid.UUID) ([]ListPendingDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingDeliveries, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingDeliveriesRow{}
	for rows.Next() {
		var i ListPendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.GuildID,
			&i.Item,
			&i.Source,
			&i.SourceID,
			&i.Note,
			&i.AcquiredAt,
			&i.DeliveryRequestedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletBalanceChangesSince = `-- name: ListWalletBalanceChangesSince :many
SELECT created_at, amount
FROM transactions
WHERE user_id = $1 AND guild_id = $2
  AND created_at >= $3::timestamptz
ORDER BY created_at ASC
`

type ListWalletBalanceChangesSinceParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
	Since   time.Time
}

type ListWalletBalanceChangesSinceRow struct {
	CreatedAt time.Time
	Amount    int64
}

func (q *Queries) ListWalletBalanceChangesSince(ctx context.Context, arg ListWalletBalanceChangesSinceParams) ([]ListWalletBalanceChangesSinceRow, error) {
	rows, err := q.db.Query(ctx, listWalletBalanceChangesSince, arg.UserID, arg.GuildID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletBalanceChangesSinceRow{}
	for rows.Next() {
		var i ListWalletBalanceChangesSinceRow
		if err := rows.Scan(&i.CreatedAt, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, user_id, guild_id, type, amount, balance_after,
       COALESCE(description, '')       AS description,
       reference_id,
       COALESCE(reference_type, '')    AS reference_type,
       created_at
FROM transactions
WHERE user_id = $1 AND guild_id = $2
  AND ($3::text = '' OR type = $3::text)
ORDER BY created_at DESC
LIMIT $5::int OFFSET $4::int
`

type ListWalletTransactionsParams struct {
	UserID     uuid.UUID
	GuildID    uuid.UUID
	TypeFilter string
	PageOffset int32
	PageSize   int32
}

type ListWalletTransactionsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	GuildID       uuid.UUID
	Type          string
	Amount        int64
	BalanceAfter  int64
	Description   string
	ReferenceID   *uuid.UUID
	ReferenceType string
	CreatedAt     time.Time
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]ListWalletTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions,
		arg.UserID,
		arg.GuildID,
		arg.TypeFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletTransactionsRow{}
	for rows.Next() {
		var i ListWalletTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GuildID,
			&i.Type,
			&i.Amount,
			&i.BalanceAfter,
			&i.Description,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPendingDelivery = `-- name: LockPendingDelivery :one
SELECT id, owner_id, guild_id, item, source, source_id,
       COALESCE(note, '') AS note, acquired_at, delivery_requested_at
FROM backpack_items
WHERE id = $1 AND guild_id = $2 AND delivery_requested_at IS NOT NULL
FOR UPDATE
`

type LockPendingDeliveryParams struct {
	ID      uuid.UUID
	GuildID uuid.UUID
}

type LockPendingDeliveryRow struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	GuildID             uuid.UUID
	Item                []byte
	Source              string
	SourceID            *uuid.UUID
	Note                string
	AcquiredAt          time.Time
	DeliveryRequestedAt pgtype.Timestamptz
}

func (q *Queries) LockPendingDelivery(ctx context.Context, arg LockPendingDeliveryParams) (LockPendingDeliveryRow, error) {
	row := q.db.QueryRow(ctx, lockPendingDelivery, arg.ID, arg.GuildID)
	var i LockPendingDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GuildID,
		&i.Item,
		&i.Source,
		&i.SourceID,
		&i.Note,
		&i.AcquiredAt,
		&i.DeliveryRequestedAt,
	)
	return i, err
}

const requestBackpackWithdrawal = `-- name: RequestBackpackWithdrawal :one
UPDATE backpack_items SET delivery_requested_at = NOW()
WHERE id = $1 AND owner_id = $2 AND guild_id = $3 AND delivery_requested_at IS NULL AND locked_by_type IS NULL
RETURNING id, owner_id, guild_id, item, source, source_id,
          COALESCE(note, '') AS note, acquired_at, delivery_requested_at
`

type RequestBackpackWithdrawalParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	GuildID uuid.UUID
}

type RequestBackpackWithdrawalRow struct {
	ID                  uuid.UUID
	OwnerID             uuid.UUID
	GuildID             uuid.UUID
	Item                []byte
	Source              string
	SourceID            *uuid.UUID
	Note                string
	AcquiredAt          time.Time
	DeliveryRequestedAt pgtype.Timestamptz
}

func (q *Queries) RequestBackpackWithdrawal(ctx context.Context, arg RequestBackpackWithdrawalParams) (RequestBackpackWithdrawalRow, error) {
	row := q.db.QueryRow(ctx, requestBackpackWithdrawal, arg.ID, arg.OwnerID, arg.GuildID)
	var i RequestBackpackWithdrawalRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GuildID,
		&i.Item,
		&i.Source,
		&i.SourceID,
		&i.Note,
		&i.AcquiredAt,
		&i.DeliveryRequestedAt,
	)
	return i, err
}

const sumWalletTransactionsBefore = `-- name: SumWalletTransactionsBefore :one
SELECT COALESCE(SUM(amount), 0)::bigint AS balance
FROM transactions
WHERE user_id = $1 AND guild_id = $2
  AND created_at < $3::timestamptz
`

type SumWalletTransactionsBeforeParams struct {
	UserID  uuid.UUID
	GuildID uuid.UUID
	Before  time.Time
}

func (q *Queries) SumWalletTransactionsBefore(ctx context.Context, arg SumWalletTransactionsBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumWalletTransactionsBefore, arg.UserID, arg.GuildID, arg.Before)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const transferBackpackItem = `-- name: TransferBackpackItem :one
UPDATE backpack_items SET
    owner_id    = $1,
    source      = 'transfer',
    source_id   = $2,
    note        = NULLIF($3::text, ''),
    acquired_at = NOW()
WHERE backpack_items.id = $4
  AND backpack_items.owner_id = $2
  AND backpack_items.guild_id = $5
  AND backpack_items.locked_by_type IS NULL
  AND backpack_items.delivery_requested_at IS NULL
RETURNING backpack_items.id, backpack_items.owner_id, backpack_items.guild_id, backpack_items.item,
          backpack_items.source, backpack_items.source_id,
          COALESCE(backpack_items.note, '') AS note, backpack_items.acquired_at
`

type TransferBackpackItemParams struct {
	ToUserID   uuid.UUID
	FromUserID *uuid.UUID
	Note       string
	ID         uuid.UUID
	GuildID    uuid.UUID
}

type TransferBackpackItemRow struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	GuildID    uuid.UUID
	Item       []byte
	Source     string
	SourceID   *uuid.UUID
	Note       string
	AcquiredAt time.Time
}

func (q *Queries) TransferBackpackItem(ctx context.Context, arg TransferBackpackItemParams) (TransferBackpackItemRow, error) {
	row := q.db.QueryRow(ctx, transferBackpackItem,
		arg.ToUserID,
		arg.FromUserID,
		arg.Note,
		arg.ID,
		arg.GuildID,
	)
	var i TransferBackpackItemRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GuildID,
		&i.Item,
		&i.Source,
		&i.SourceID,
		&i.Note,
		&i.AcquiredAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :exec
UPDATE wallets SET balance = $1, updated_at = NOW() WHERE user_id = $2 AND guild_id = $3
`

type UpdateWalletBalanceParams struct {
	Balance int64
	UserID  uuid.UUID
	GuildID uuid.UUID
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, updateWalletBalance, arg.Balance, arg.UserID, arg.GuildID)
	return err
}
