DROP TABLE IF EXISTS raffle_winners CASCADE;
DROP TABLE IF EXISTS raffle_tickets CASCADE;
DROP TABLE IF EXISTS raffles CASCADE;
DROP TABLE IF EXISTS bids CASCADE;
DROP TABLE IF EXISTS auctions CASCADE;
DROP TABLE IF EXISTS item_events CASCADE;
DROP TABLE IF EXISTS backpack_items CASCADE;
DROP TABLE IF EXISTS withdrawal_requests CASCADE;
DROP TABLE IF EXISTS fund_requests CASCADE;
DROP TABLE IF EXISTS item_requests CASCADE;
DROP TABLE IF EXISTS bank_items CASCADE;
DROP TABLE IF EXISTS bank_contributions CASCADE;
DROP TABLE IF EXISTS roll_call_gold_payouts CASCADE;
DROP TABLE IF EXISTS roll_call_gold_distributions CASCADE;
DROP TABLE IF EXISTS roll_call_gold_pots CASCADE;
DROP TABLE IF EXISTS roll_call_attendees CASCADE;
DROP TABLE IF EXISTS roll_call_templates CASCADE;
DROP TABLE IF EXISTS roll_calls CASCADE;
DROP TABLE IF EXISTS item_templates CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS guild_bank CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS wallets CASCADE;
DROP TABLE IF EXISTS guild_events CASCADE;
DROP TABLE IF EXISTS announcements CASCADE;
DROP TABLE IF EXISTS activity CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS invitations CASCADE;
DROP TABLE IF EXISTS member_role_changes CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS guild_logos CASCADE;
DROP TABLE IF EXISTS guilds CASCADE;
DROP TABLE IF EXISTS user_preferences CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS acting_admin_id();
DROP FUNCTION IF EXISTS assign_member_display_name();
DROP FUNCTION IF EXISTS gold_amount(BIGINT);
DROP FUNCTION IF EXISTS log_backpack_item_event();
DROP FUNCTION IF EXISTS log_bank_item_event();
DROP FUNCTION IF EXISTS log_item_request_event();
DROP FUNCTION IF EXISTS member_display_name(UUID, UUID);
DROP FUNCTION IF EXISTS notification_enabled(UUID, TEXT);
DROP FUNCTION IF EXISTS notification_user_name(UUID);
DROP FUNCTION IF EXISTS notify_auction_cancelled();
DROP FUNCTION IF EXISTS notify_auction_ended();
DROP FUNCTION IF EXISTS notify_auction_outbid();
DROP FUNCTION IF EXISTS notify_backpack_changed();
DROP FUNCTION IF EXISTS notify_backpack_item_received();
DROP FUNCTION IF EXISTS notify_bank_request_reviewed();
DROP FUNCTION IF EXISTS notify_bank_request_submitted();
DROP FUNCTION IF EXISTS notify_bid_changed();
DROP FUNCTION IF EXISTS notify_delivery_changed();
DROP FUNCTION IF EXISTS notify_gold_transfer_received();
DROP FUNCTION IF EXISTS notify_guild_row_changed();
DROP FUNCTION IF EXISTS notify_item_delivered();
DROP FUNCTION IF EXISTS notify_live_event(TEXT, UUID, UUID, TEXT, TEXT);
DROP FUNCTION IF EXISTS notify_loot_assigned();
DROP FUNCTION IF EXISTS notify_member_role_changed();
DROP FUNCTION IF EXISTS notify_notification_changed();
DROP FUNCTION IF EXISTS notify_published_announcement_changed();
DROP FUNCTION IF EXISTS notify_raffle_cancelled();
DROP FUNCTION IF EXISTS notify_raffle_rows_changed();
DROP FUNCTION IF EXISTS notify_raffle_won();
DROP FUNCTION IF EXISTS notify_roll_call_gold_received();
DROP FUNCTION IF EXISTS notify_wallet_changed();
DROP FUNCTION IF EXISTS notify_withdrawal_request_reviewed();
DROP FUNCTION IF EXISTS notify_withdrawal_request_submitted();
DROP FUNCTION IF EXISTS unique_member_name(UUID, TEXT, UUID);

DROP EXTENSION IF EXISTS "uuid-ossp";
