services:
  postgres:
    image: postgres:17.6
    environment:
      POSTGRES_DB: guma
      POSTGRES_USER: guma
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guma"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:8.2.1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  kratos:
    image: oryd/kratos:v1.3.1
    # environment:
      # - DSN=postgres://kratos:kiatest@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - "4433:4433" # Public API
      - "4434:4434" # Admin API
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4433/health/alive"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos/
    command: serve --config /etc/config/kratos/kratos.yaml
    # entrypoint: sleep infinity

  nginx:
    image: nginx:stable
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kratos
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  minio_data:
