services:
  # a toolbox container for development
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    depends_on:
      - postgres
      - redis
      - minio
      - kratos
    environment:
      - DATABASE_URL=postgres://guma:password@postgres:5432/guma?sslmode=disable
      - KRATOS_ADMIN_URL=http://kratos:4434
